### ISSUE TITLE
PostGresSQL has issues with passwords with spaces

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#103]
From >> https://www.hmailserver.com/forum/viewtopic.php?f=7&t=28308&p=176265#p176265

<<Quote>>
Just a quick bug report, ignore/delete if known:

Tried to set up hMailServer with a locally hosted PostgreSQL server. When the PostgreSQL user had spaces in the password I got an error when attempting to create the database, saying that it's missing a '=' after the token 'sometoken', sometoken being the first word of the passphrase (apologies for not pasting the precise error, writing this from memory).

After removing all spaces the tables got created as expected.

**Comment by martinknafve** [comment]
Not known. Will fix.

**Comment by martinknafve** [comment]
Fixed in upcoming 5.7.0.
