### ISSUE TITLE
Backup only database structure without messagesfolder

### ISSUE THREAD

**Issue by PrismaComputer** [hmailserver/hmailserver#104]
Bill48105 did a change to an experimental build and added a setting named:

[Settings] BackupMessagesDBOnly=0 ;Defaults to 0 or disabled

This setting modifies the behaviour of the built-in full (message) backup. The aim is to backup the settings+file informations but not the data (files) folder.
This setting is optimal for migration purposes and backup scenarios where the data (files) folder is backed up separately. Because the XML-structure is used, this "dump" is database type independent.

The problem is, the data (files) folder has to be renamed, before the restore is started. Background: During the restoring process the data folder will be wiped out.

So, here is the request:
1. Please put BackupMessagesDBOnly or something similar in a stable release
2. Give it a own GUI Checkbox
3. Prevent deletion of the data (files) folder on restore if no messagefiles are stored in the backup file.

Also requested from mattg here:
https://www.hmailserver.com/forum/viewtopic.php?f=2&t=17961

**Comment by martinknafve** [comment]
Since hMailServer is no longer being actively developed, enhancements will only be included if authored as a PR with automated tests.
