### ISSUE TITLE
Restore only possible when backupfile selected by filepicker

### ISSUE THREAD

**Issue by PrismaComputer** [hmailserver/hmailserver#106]
![nostart](https://cloud.githubusercontent.com/assets/9677018/8106309/580750e6-1040-11e5-986f-3c20457048ee.jpg)
A restore is only possible when the backupfile is selected by filepicker. To type the path+file is not enough. Reason: After the backupfile is selected some checks are done and afterwards the button "Start" will be enabled.

You'll possibly ask "AND? So what?" -> On a server core machine there is no filepicker and you have to type the path -> "Start" stays grey -> The restore is broken on server cores. A really little improvement would help: Check the backupfile also "on leave" of the edit control or on ENTER.

Workaround: Use hMailAdmin remotely + select a network path on the mailserver -> the restore process will access the mailserver itself by network -> slow.

**Comment by martinknafve** [comment]
Fixed in upcoming 5.7.0. You'll be able to type in the file name manually.

**Comment by PrismaComputer** [comment]
THX!! Just for your statistics: Let's assign it to Milestone 5.7. One more officially solved problem.
Cheers Greg
