### ISSUE TITLE
Alias emails are not signed with DKIM

### ISSUE THREAD

**Issue by ghost** [hmailserver/hmailserver#110]
Account: main.example.server
|- Name: sub1.example.server, sub2.example.server

Expected result:
Alias FQDN(account - name) should be signed with main account's DKIM key.

Actual result:
If I send email from xxx@main.example.server, hMailserver signed it with DKIM.
Howver, if I send email from xxx@sub2.example.server, hMailserver never sign it.

**Comment by OutbackMatt** [comment]
Yes, they are different sub-domains.
That is what I would expect

If you had DKIM established for 'example.server' than I'd expect sub-domains to be signed

**Comment by DizzyGrizzly** [comment]
I have the same issue but while using different FQDN's as domain aliases. 
DKIM does not sign outgoing email from domain aliases while it could and should (all settings correct and in place).
For example with one single user@ (owner) and two domains: 
as default domain1.com (max 1 domain),
and all additional domains must be aliases like domain2.org, domain3.xyz etc. ;
Very useful for admins whom wish to have only one single admin@ inbox for all its many domains.
At the moment none of the aliased domains can send DKIM signed emails.
Seen this as a poppular nice to have feature by others as well.
