### ISSUE TITLE
Let user to set other DNS

### ISSUE THREAD

**Issue by espress0** [hmailserver/hmailserver#111]
https://www.hmailserver.com/forum/viewtopic.php?t=22436

I can't use, or set my DNS. There's many reasons, some people live in restricted countries
where DNS traffic is unreliable, filtered, blocked, etc.
I want hMailserver to use other DNS server(e.g., dnscrypt-proxy).
So, please add something like this:

[X] Don't use system DNS for lookup
Specify DNS server(IP:Port format): [ 127.0.0.1:5335 ]

**Comment by OutbackMatt** [comment]
Pretty sure that if you add this to the bottom of your hmailserver.in, and then uncomment the first line by removing the ':' at the start of that line, that you will achieve what you need.

;DnsServers=192.168.1.33
; MUST BE IP! ONLY 1 ALLOWED FOR NOW!
; Allows over-ride of DNS servers
; Default is use Windows system DNS



I'd also like these type of queries via the user forum please >> https://www.hmailserver.com/forum/

**Comment by espress0** [comment]
Cool, but how can I specify port? Not 53/udp.

**Comment by espress0** [comment]
https://www.hmailserver.com/forum/viewtopic.php?f=2&t=22436
https://www.hmailserver.com/forum/viewtopic.php?f=2&t=17123
https://www.hmailserver.com/forum/viewtopic.php?t=19015

Wow, many ppl want this feature.

> I'd also like these type of queries via the user forum please
If I'm the forum admin, I'll just close official forum(phpBB) and move to github.

**Comment by OutbackMatt** [comment]
If you can create a DNS on a custom port, why don't you just get windows to connect to that DNS??

**Comment by martinknafve** [comment]
I would also want to know why you wouldn't just configure Windows to use the DNS which works for you. If some DNS server isn't usable for you, I assume you would not configure Windows to use it anyway?

**Comment by espress0** [comment]
> why you wouldn't just configure Windows

Reason is simple; I DONT WANT TO DO IT.

I'm using restricted DNS server for windows(Only to serve 'A' request, ignore other such as 'MX' and advertisement hosts),
and I don't want Windows to use freedom(normal) DNS server.
I have other reasons, but this is a off-topic I think.

I want hMailserver to use freedom DNS server, to query "MX","TXT","A","SPF", etc.
I can set up dnscrypt-proxy only for hMailserver.

;DnsServers=192.168.1.33

If this settings are existed, why I can't set a port?

DnsServers=127.0.0.1:54 (UDP dnscrypt-proxy)

**Comment by PrismaComputer** [comment]
Don't get me wrong, but without further info your usecase sounds not really reputable. But anyway, assuming you have serious reasons, why don't you install a bind server https://www.isc.org/downloads directly on the mailserver? Hmailserver should be able to use Bind with DNSServers=127.0.0.1 and bind should be able to forward to wherever you want.

Not tested but should work...

**Comment by martinknafve** [comment]
There's no setting in hMailServer to change the DNS server it use. It may have been part of some experimental "3rd party" build. hMailServer assumes that Windows is configured to use a fully functional DNS server - not a DNS server which blocks queries. The only workaround to this issue is to use an email server which does not block queries. I agree with @PrismaComputer that you haven't really explained *why* you need this feature, just that you want it. I can't implement things based on that.
