### ISSUE TITLE
Copyright notice in about help says 2012

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#112]
Copyright notice in about >> help says (c) 2012

(Not that this matters much)

**Comment by martinknafve** [comment]
Thanks! Actually, a year in a copyright statement may refer to the "original year the copyright was claimed" (or something along those lines - but that wasn't 2012 anyways. hmm). Either way, it's not necessary for software to provide explicit copyright information like this. It's implicit. So I simply removed the statement. :)
