### ISSUE TITLE
Provide ZIP package for easy upgrade.

### ISSUE THREAD

**Issue by espress0** [hmailserver/hmailserver#114]
I don't want to run installer again, so please add hmailserver.zip.

So I can copy SQL/bin files to current hmailserver directory... easy upgrade.

**Comment by OutbackMatt** [comment]
But there is more to an upgrade than simply copying bin folder contents...

Most upgrades also run as a minimum some database queries, also the PHPWebAdmin is updated every release. Running the installer 'again' is a very easy update.

(please have this type of discussion in the official user forum)

**Comment by PrismaComputer** [comment]
+1 impossible, forgotten or manual database updates with human failures and problems a unsupportable.

**Comment by martinknafve** [comment]
I won't spend time on this. It takes less than a minute to deploy using the installer, and if you want to speed up that create a batch script and run it in silent mode.
