### ISSUE TITLE
valid address syntax changed between 5.3.3 and latest version

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#117]
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=28446&p=177532#p177532

Unsure if this important or not.
User in this case has a solution, no other users yet mentioned this.

However may well be a RFC compliance issue..

**Comment by martinknafve** [comment]
Thanks. This is actually the sending software which does not follow the RFC. hMailServer just has stricter validation in place, which causes this. Please see forum thread.
