### ISSUE TITLE
Potential Memory Leak when dealing with errors from large emails

### ISSUE THREAD

**Issue by bighossbiz** [hmailserver/hmailserver#118]
I have been trying to identify the cause of errors with hMailServer; and found an error that was mildly elusive, however I am now able to replicate it 100%.

hMail has been using more and more ram; eventually consuming the 2GB a 32 bit application can consume, and throwing many errors when dealing with large emails (20MB+). It turns out they're related.

System Setup: hMail 5.6.3-B2249 on W2K3 with mysql server using network drive for data directory/log directory. (Will test on W2K8 soon)
Clients affected are MS Outlook 2010, Thunderbird (Win, OSX, Linux), Apple Mail (iOS), MailDroid (Android), K9Mail (Android), various manufacturer default email applications (Android)

Setup:
1 Using K9Mail for Android
(because it does not retry after a failure, otherwise, with Thunderbird, etc, they will keep retrying and ballooning memory usage sometimes several hundred MB).
2. Setup to hmail over SSL connection over IMAP
3. Send an email to email account for testing so email client reports size is over 20MB (around 17MB of files)
4. Using client check email
5. Try to open email, and view download whole message

Watching TaskManager, hmail's memory stats will rise in the VM Size 20-30MB
hMail will then throw the following errors:
"ERROR" 4024    "2015-07-27 21:30:37.611"       "Severity: 3 (Medium), Code: HM4227, Source: File::ReadFile, Description: An unknown error occurred while reading file from disk."
"ERROR" 4024    "2015-07-27 21:30:37.631"       "Severity: 3 (Medium), Code: HM5042, Source: File::ReadTextFile, Description: An unknown error occurred while reading a text file from disk."
"ERROR" 4024    "2015-07-27 21:30:37.651"       "Severity: 1 (Critical), Code: HM5062, Source: IMAPFetch::ReportCriticalError_, Description: ERROR HM10001 - IMAP FETCH: Error when loading MIME message. - \\VBOXSVR\email\data\domainname.com\username\63\{6314FC7B-1514-4CA9-A58E-1D478EDF112F}.eml"
"ERROR" 4024    "2015-07-27 21:30:37.891"       "Severity: 3 (Medium), Code: HM5136, Source: TCPConnection::AsyncReadCompleted, Description: An error occured while parsing data. Data length: 34, Data: 4 UID FETCH 5229 (UID BODY.PEEK[]). Remote IP: 198.xxx.xxx.xxx"
"ERROR" 4024    "2015-07-27 21:30:37.921"       "Severity: 2 (High), Code: HM4208, Source: ExceptionHandler::Run, Description: An error occured while executing 'IOCPQueueWorkerTask'"

The email client will notify there was an error, and stop the download. hMail's VM Size will increase aproximately the size of the email data file, and will not free the memory like normal after a succesful transfer of a smaller email (say 10MB)

**Comment by martinknafve** [comment]
A while back you received a special build containing fixes to file access. This build solved an issue which so far only been reported to you, which occurred when reading files. If I recall correctly, we were not really able to figure out exactly why it occurs. I intended to include these fixes in version 5.7 - they are not included in current official releases. So I assume you upgraded from the version you were using to the latest version were these fixes were not included, and you started getting this issue again.

Sounds like I should create a 5.6 build with these fixes, since 5.7 is still some time away.

**Comment by bighossbiz** [comment]
I did not realize you ommited these the changes from the production build. I thought we had a regression case. My apologies.
I did in fact upgrade due to the security improvements and the official utf8mb4 support that upon review seemed nessesary.
If you would be willing to provide a special build, that would be very much appreciated.

**Comment by jackfagner** [comment]
@martinknafve , we have the same problem (I think):

    "ERROR"	1244	"2015-07-31 09:51:05.756"	"Severity: 3 (Medium), Code: HM5136, Source: TCPConnection::AsyncReadCompleted, Description: An error occured while parsing data. Data length: 45, Data: 62.316 UID FETCH 1 BODY.PEEK[]<39156.5503874>. Remote IP: [aa.bb.cc.dd]"
    "ERROR"	1244	"2015-07-31 09:51:05.772"	"Severity: 2 (High), Code: HM4208, Source: ExceptionHandler::Run, Description: An error occured while executing 'IOCPQueueWorkerTask'"
    "ERROR"	1244	"2015-07-31 09:51:05.913"	"Severity: 1 (Critical), Code: HM5519, Source: StackLogger::Log, Description: An error has been detected. A mini dump has been written to [...]\minidump_2015-07-31 095105_{4D55B7A9-FDD0-448F-A1CE-92383BXXXXXX}.dmp"

**Comment by martinknafve** [comment]
Does anyone of you have the time to try out the latest 5.6.4 build?

https://build.hmailserver.com/repository/download/HMailServer_BuildHMailServer56/407:id/hMailServer-5.6.4-B2289.exe?guest=1

**Comment by bighossbiz** [comment]
I'll download and install later this evening. Is there anything special to note or look for with this build?

**Comment by jackfagner** [comment]
@bighossbiz , did you test the latest 5.6.4 build?

**Comment by bighossbiz** [comment]
@jackfagner I did have a couple hours to test, and I'm sorry for my delayed feedback; however I wanted to exhaust all possible configuration options before reporting back with my findings (however I have not had the opportunity)

I have tested the new build and yes it does solve the memory leak issue and the errors reported; however, I noticed approximately a 30-50% performance loss in loading large emails from the testing VM environment.
I was looking for known issues and performance and noticed loading messages seemed to take longer, so I cleared Thunderbird message cache, and timed the time it took to download the message from hMailServer running in a VM on the local computer. One message took around a minute, running hMS 5.6.3. Using the test build 5.6.4; it took the same message 1:22. The message was listed as 30MB.

I was reluctant to migrate the production server until I could find the source of the degraded performance (whether hMS software or OS related) to report my fidings.

Also with my testing, I have run into a small problem with my specific scenario. Upon setting up a fresh VM I could no longer reproduce the symptoms. I then created a clone of the production system, and began receiving the errors once more. After doing a VirtualBox Guest Addons upgrade; I no longer received the errors. I rolled back the VM snapshot, and uninstalled the old version of Guest Addon Drivers, and rebooted, and reinstalled the old Guest Addon Drivers and the error again has not resurfaced.

On the production system, I performed the 'fix' of remove reinstall and it has been running smoothly now for about a week and using around 70MB.

I still have a VM image of the state where my errors were occurring

**Comment by broerse** [comment]
We just tested with 5.6.4-B2289 and it does not solve our problem. We see the hMailServer memory use grow to about 1.1 Gb when the HM4208 occurs. The errors are only with mails bigger then 10 Mb.

**Comment by broerse** [comment]
hMailServer 5.6.7 - Build 2425 (BETA)  also does not solve this. @martinknafve is it possible that you take a remote look? We will pay for support.

**Comment by martinknafve** [comment]
Can you tell me roughly how many users and messages are hosted on the server?

**Comment by broerse** [comment]
Yes about 40 users and 400000 mails.

**Comment by broerse** [comment]
Switching from Outlook 2010 to Outlook 2016 seems to be the change that started the errors.

**Comment by martinknafve** [comment]
Are you using a virus scanner, any custom scripts or anything like that?
If you restart the server, how quickly does the memory grow?

**Comment by broerse** [comment]
We are not using a virus scanner or a custom script. If the clients are on it takes max 2 minutes before the errors are logged.

**Comment by martinknafve** [comment]
Can you send me the error logs and dump file to me at martin@hmailserver.com?

**Comment by broerse** [comment]
Yes will mail it in a few minutes. Will have to connect to the customer.

**Comment by broerse** [comment]
Just mailed

**Comment by martinknafve** [comment]
I have not received it. Can you email an copy to knafve@gmail.com as well in case there's some anti spam mechanism blocking it?

**Comment by broerse** [comment]
14 Mb mail ... Mailed a link now,

**Comment by bighossbiz** [comment]
Was this resolved with a new patch?

**Comment by broerse** [comment]
No it was not. @martinknafve is helping and we are still searching. @bighossbiz doe you see this on fast hardware?

**Comment by bighossbiz** [comment]
Hi Martin(s)
      
      The servers I was originally seeing this occurring on was an older
      HP Proliant G3 running 2.8GHz with Win2k3 over a network attached
      storage array.
      
      Then the second machine to have this happen to is a newer HP
      Proliant G5 with Win2k8-R2 running 3GHz under VirtualBox hosted on
      Linux.. So the underlying hardware isn't super fast, but being
      virtualized has helped with the system IO speeds. Also the storage
      array is also solid state media, also helping with the storage
      access speeds.
      
      If it helps I can supply the hmail minidumps I've received
      recently, logs, etc. The issue had been resolved for a period
      (some time ago) but due to server upgrades, and security updates,
      hmailserver software was upgraded and soon thereafter it began
      exhibiting these errors again - due to the lack of documentation
      to *not* update the server.
      
      If there is anything else I can do to help, I'd be more than happy
      to.
      
      Don Grantham
Systems Administrator
Big Hoss Hosting.com
(269)-330-5298
      On 2/6/2018 12:32 PM, Martin Broerse wrote:
    
    
      No it was not. @martinknafve
        is helping and we are still searching. @bighossbiz doe you see this on fast
        hardware?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hmailserver/hmailserver","title":"hmailserver/hmailserver","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/hmailserver/hmailserver">"https://github.com/hmailserver/hmailserver"</a>}},"updates":{"s
nippets":[{"icon":"PERSON","message":"@broerse in #118: No it was not. @martinknafve is helping and we are still searching. @bighossbiz doe you see this on fast hardware?"}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/hmailserver/hmailserver/issues/118#issuecomment-363501086">"https://github.com/hmailserver/hmailserver/issues/118#issuecomment-363501086"</a>}}}

**Comment by broerse** [comment]
@bighossbiz  We where first thinking this errors started when we switched to Outlook 2016 but now we also see this error at a customer with Outlook 2010. The only thing that changed for that customer was that we moved the virtual server where hMailserver was installed on to new super fast hardware. And we installed newer windows updates. So the common thing is new windows updates and storage change from normal Hard Drives to SSD. The other common thing is CPU speed increase but if you have the same errors we have this does not seem to be the cause. I hope we will find the cause soon.

**Comment by bighossbiz** [comment]
That.. is very good hunch, and I just went through my error logs and I 
see some similar correlation there - 90% of the listed IP addresses are 
with known users of Outlook. The other 10% are mobile carriers, so 
either Outlook phone app, or tethering use but nothing definitive.

**Comment by alemau5** [comment]
Hello @broerse did you have any luck solving this issue? I'm having this same problem when loading 10+MB messages where RAM usage goes beyond 3GB, and I had to disable IMAP IDLE, otherwise outlook, apple mail, etc, aren't able to retrieve messages, unless they're restarted.

**Comment by broerse** [comment]
@alemau5 We have this memory leak problem at 6 different companies now. Companies with Outlook 2016 always get this leak more but it also happens with one company that uses only Outlook 2010. Until this is fixed we worked around this by setting "Settings=>Performance=>Treading=>Max number of command treads" to 200 and restart hMailserver every hour.  We send log files and data from one company to @martinknafve and he is working on this memory leak but we will have to wait until he finds the problem.

**Comment by alemau5** [comment]
Oh thanks @broerse I followed your tips and set my hMailserver to restart every 15 minutes, which is about the time IMAP IDLE starts to fail, also thanks @martinknafve for the great work so far!
