### ISSUE TITLE
Text on Backup page of admin GUI is incorrect

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#121]
This statement needs updating 

"This functionality is designed to be used in small installations with less than 1GB of eMail data.
If you installation is larger than this, please consult documentation for usage of ext"

**Comment by martinknafve** [comment]
Thanks. Fixed for 5.7.

**Comment by jimimaseye** [comment]
Martin: for clarification:  have you simply changed/removed the WORDING or have you also removed the _actual_ limitation of the DATA being no larger than 16GB?
