### ISSUE TITLE
Setup only administrative tools not working correctly

### ISSUE THREAD

**Issue by PrismaComputer** [hmailserver/hmailserver#122]
The setup of at least 5.6.4 is not able to install only the administrative tools. Several error messages appear:
* libeay32.dll missing
* ssleay32.dll missing
* msvcp120.dll missing
* msvcr120.dll missing

Once the administrative tool is started, the application is not able to connect to a server. A message similar to "type is not allowed to be NULL" appears.

A full setup installs the administrative tools correctly, administering a remote server is also possible.

**Comment by martinknafve** [comment]
I tried to install just the administrative tools and got no errors. Tried both with latest 5.6.4 and 5.6.5. Were you getting these errors during the installation or afterwards? None of these files are actually required for the administrative tools, the four files are only needed by the server-part of the software.

**Comment by PrismaComputer** [comment]
Yes, may be they are only required for the server part. But setup is missing them even though only the Tools should be required. Tested right now with 5.6.4-B2283 with naked Win10 and .NET 4.0 (including 3.5 and 2.0) already installed. Same popups.

**Comment by martinknafve** [comment]
Would it be possible to show a screenshot so I really understand what you're seeing?

**Comment by PrismaComputer** [comment]
[IMG]http://i67.tinypic.com/28ugsog.jpg[/IMG]

**Comment by martinknafve** [comment]
Fixed in 5.6.5
