### ISSUE TITLE
MultiInstance Feature

### ISSUE THREAD

**Issue by decentury** [hmailserver/hmailserver#125]
Hi, iam Dave/Dravion in the hMailserver Forum.
I know something was allready asking for this feature but jimi the mod in the forum leads me to here, so here iam ;d

Here my arguments why iam thinking multiinstancing would be good feature request:

1) SMTP-Server instances runing independently.
2) Any Instance has its own SQL-Database.
3) Multiple Computers can act as SMTP-Grid.
4) Avaiability depends not on a single instance.

Performance:
The szenario: You want to sent a giant newsletter with 500.000 Million recipients.A single hMailserver needs forever to compute this task.
A grid, connected with many SMTP instances but one SQL-Database as source can organize the rask diffrently. MTA 1) delivers all newsletter to Sidney while MTA 2) delivers to the New York rregion ect. MTA 5) is failing and down for maintenance but MTA 6) takes over MTA 5) task. 
If MTA 5) is repaired and ready agai, it autointegrates into the grid and signals avaiability.

Forum discussion:
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=28677

**Comment by Ted-CAcert** [comment]
I'm not sure if the post above is including this, but I'd love to build this scenario:
- Two hMail processes running on different machines
- They share the same SQL database
- One process handles IMAP
- The other process handles SMTP sending and receiving

Ideally there could even be more than one machine doing SMTP (which seems to be the focus of the above post), or more IMAP servers in a Network Load Balance (NLB) setting, but just splitting IMAP and SMTP functionality to two different machines would already be a great feature for me.

**Comment by OutbackMatt** [comment]
I think that this can be done currently. I replied in the forum.
I misunderstood what was being requested in the forum thread.

**Comment by martinknafve** [comment]
hMailServer 5.x won't include more features in this area. hMailServer 6 will support this, but timewise that's pretty far away.

**Comment by Dravion** [comment]
Hi Martin. Cool. Do we have a little Roadmap so we can see whats in the Loop and to be expected in the next releases?
