### ISSUE TITLE
POP3 TOP command does not escape single dot on a line

### ISSUE THREAD

**Issue by afterlogic** [hmailserver/hmailserver#126]
Hi,

In POP3, single dot on a line must be escaped with two dots. In hMailServer, this works with RETR but not with TOP command (when TOP also requests some body lines).

![scrshot_single_dot](https://cloud.githubusercontent.com/assets/4507359/10906626/2366506a-8234-11e5-81d4-b725d071e84d.png)

**Comment by martinknafve** [comment]
Fixed in hMailServer 5.7.0.
