### ISSUE TITLE
Problem with "From" and "Sender" headers

### ISSUE THREAD

**Issue by cziegenberg** [hmailserver/hmailserver#13]
# Background

I have an existing e-mail account, but my provider doesn't allow to use external domains. So I set up a hMailserver, configured the new domain and forward all messages to the existing address (catch-all).

Receiving messages worked great, but sending was still a problem, because I had to use alias sender addresses: Thunderbird wasn't a problem, but when I used aliases in Outlook 2010, all messages where sent "on behalf of" ("primary@domain.tld on behalf of alias@domain.tld").

I checked the mail and saw that Outlook sends the message with the following headers:
From: alias@domain.tld
Sender: primary@domain.tld
# My solution

I wrote a script to replace the "Sender" header:

```
Sub OnAcceptMessage(oClient, oMessage)
    oMessage.HeaderValue("Sender") = oMessage.FromAddress
    oMessage.Save
End Sub
```

This didn't work. After some logging I found out that the "oMessage.FromAddress" had the value of the "Sender" header, while "oMessage.From" had the value of the "From" header. So I changed my script:

```
Sub OnAcceptMessage(oClient, oMessage)
    oMessage.HeaderValue("Sender") = oMessage.From
    oMessage.Save
End Sub
```
# The problems

This works great now, but I'm a bit confused why two different headers are used for these properties. Also your documentation (https://www.hmailserver.com/documentation/latest/?page=com_object_message) doesn't help, because it says that the "sender" is used (which is not always the case, because sometimes the "From" header is used) and it's not clear (for me) what's the difference between "the sender" and "the sender _address_":

```
string From - The sender of the e-mail.
string FromAddress - The sender address of the message.
```

Also it seems that oMessage.Headers doesn't contain the "From" and the "Sender" header.
# Suggestions
- Update documentation to explain the difference between both properties and their source headers.
- Think about adding new properties to differ between the value of the "From" and the "Sender" header
- Add "From" and "Sender" to the header collection (and/or document filtered headers)

**Comment by funbsd** [comment]
Is it possible to change sender in envolpe?
I relay all mail to exchange with authentication, and it response "Client does not have permissions to send as this sender".
