### ISSUE TITLE
 the diagnostics don't work if you set the outgoing port to 465 and set SSL in SMTP relayer.

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#130]
the diagnostics don't work if you set the outgoing port to 465 in SMTP relayer and select SSL

Seems reproducable for a few versions.

Doesn't affect hmailserver from running. changing port number in SMTP relayer allows the diagnostics to run. Diagnostics work fine for port 587 and port 25

**Comment by martinknafve** [comment]
This has been fixed in upcoming 5.7.0.
