### ISSUE TITLE
Make setup add version to add/remove programs

### ISSUE THREAD

**Issue by andrejohansson** [hmailserver/hmailserver#132]
When installing hMailServer does not write version information to windows add/remove programs. This breaks the ability to manage the software automatically using provisioning tools like SaltStack, Ansible, Chef, Puppet since they cannot easily read out which version is installed and if they need to upgrade.

Version and name should be in separate fields.

![2015-11-13 10_25_42-dvs-eu-hmsr cloudapp net_3389 - remote desktop connection](https://cloud.githubusercontent.com/assets/2828428/11142898/f7597b9a-89f0-11e5-87e2-809fbc82847c.png)

**Comment by martinknafve** [comment]
Will be fixed in 5.7.
