### ISSUE TITLE
It would be nice if one could change an active directory password in hmailserver

### ISSUE THREAD

**Issue by dswartz** [hmailserver/hmailserver#136]
So hmailserver has a COM method that a plugin for roundcube can use to change your hmailserver password (as a user).  If hmailserver is configured to authenticate via Active Directory, there is no clean and easy way I have been able to find.  It shouldn't be that difficult - from googling, I have seen code snippets that are a dozen or so lines using standard Active Directory API.  I may take a look at doing this...

**Comment by martinknafve** [comment]
I consider changing the AD password outside the scope of an email server. I agree it might not be very hard to implement, but I don't think it fits well within hMailServer to have this logic.

**Comment by dswartz** [comment]
Well, I obviously don't agree :)  We already support authenticating with an AD server, so the capability had to be added to hmailserver.  There is also the capability to change a user password in the admin GUI (which also supports plugins like the roundcube change_password plugin).  If you have been given AD credentials that allow you to change passwords (or maybe you provide the existing password), it's a one-stop shopping thing (e.g. not having to login to an AD host to do this.)  If someone uses something like roundcube, this would be very helpful. But your call, of course :)
