### ISSUE TITLE
Out-of-office / vacation message only allows up to 1000 character text entry

### ISSUE THREAD

**Issue by dswartz** [hmailserver/hmailserver#137]
See forum post https://www.hmailserver.com/forum/viewtopic.php?f=7&t=29040.

**Comment by martinknafve** [comment]
This issue is caused by the fact that the hMailServer database schema for SQL Server is limited to 1000 and the validation logic is executed for all database backends. The fix to the problem would be to update the MSSQL schema for MSSQL to ntext and then remove the validation of the length.

**Comment by martinknafve** [comment]
This is not something I will change in the foreseeable feature.
