### ISSUE TITLE
Hmailserver screws up X-Spam-Report header formatting when adding x-hmailserver headers

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#138]
When Hmailserver adds some function headers (defined by user configuration) such as X-hMailServer-Spam, X-hMailServer-Reason-Score,  it completely messes up the Spamassassin X-Spam-Report header formatting previously put there correctly by spamassassin.

I have tested and confirmed this many times.  Up to HMS 5.6.4.

This single post demonstrates: https://www.hmailserver.com/forum/viewtopic.php?p=177517#p177517

**Comment by martinknafve** [comment]
Same as https://github.com/hmailserver/hmailserver/issues/115
