### ISSUE TITLE
Email files on MS SQL FileTable 

### ISSUE THREAD

**Issue by juleswnfld** [hmailserver/hmailserver#141]
Hi,
While I read you considerations of using the file system for email storage and I agree with the 50 KB reading into memory, I would suggest for MS SQL database repository to use the FileTable feature.
As you may know, it actually keeps the bytes on file system, but file info in a table.
You can benefit from full database backups that get the files as well.
And FileTable feature is included in the Express edition and not counted in the 10 GB space limit.

Please consider it, I could help if needed.
Best regards.

**Comment by martinknafve** [comment]
This will not be implemented in hMailServer 5.x. hMailServer supports several different database engines, and implementing support to store messages in file tables would make the implementation a lot more complex (there's a lot of implementation relying on the fact that messages are stored on disk).

hMailServer 6.x might include the possibility to implement this.
