### ISSUE TITLE
Uninstall / reinstall overwrites eventhandlers.vbs

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#142]
I had occasion to uninstall, restart and the re-install hMailserver (5.6.5-B2293)

My eventhadlers.vbs was overwritten with the default blank one.

This didn't happen with an install over the top of the same version (like an upgrade).

hmailserver.ini stayed the same, not data loss that I can see, just the eventhandlers.vbs was overwritten. Noticed almost immediately as my rules that fired scripts started to log errors.

(I had a backup, so no problem for me, just informational bug report)

**Comment by hmailserver** [comment]
Fixed in the next 5.6.5 build.
