### ISSUE TITLE
Entering Duplicate name in IP RANGE gives uncontrolled error

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#143]
When trying to manually enter different IP RANGES, and you enter a NAME that is identical to an existing IP RANGE, then an error similar to the following is issued (in this case from the MySQL database handler):

> 
> **Source: DALConnection::Execute**
>  **Description: MySQL: Duplicate entry** 'Hacker in Netherlands' for key 'rangename' (Additional info: UPDATE hm_securityranges SET rangename='Hacker in Netherlands', rangepriorityid=20, rangelowerip1=1509469059, rangelowerip2=NULL, rangeupperip1=1509469059, rangeupperip2=NULL, rangeoptions=136192, rangeexpires=1, rangeexpirestime='2016-12-01 17:04:39' WHERE rangeid = 123)

I understand that maybe the code restricts to have unique names (although is it really not possible to use unique identifiers instead?), BUT the main point is that the GUI could issue a more controlled on screen error/restriction informing the user and prompting for re-input.  (Currently it just goes "Failed to save - see Error log for details" before returning back to menu.  This means the user then has to source out and review the error logs (just to see the cause) for something that could simply have been issued to screen.

**Comment by hmailserver** [comment]
Fixed in next 5.6.5-build.
