### ISSUE TITLE
Account level rule 'reply' behaves inconsistently

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#144]
In this thread>> https://www.hmailserver.com/forum/viewtopic.php?f=2&t=11832&start=60

Account rule action 'reply' sends mail from the daemon, not from the account. This is inconsistent with the way that auto-reply and forward works. Both of these send from the relevant account.

**Comment by jimimaseye** [comment]
this post and onwards is more apt: https://www.hmailserver.com/forum/viewtopic.php?p=182810#p182810

**Comment by martinknafve** [comment]
Since hMailServer is no longer being actively developed, enhancements will only be included if authored as a PR with automated tests.
