### ISSUE TITLE
2nd Admin Remote Access Protocoll

### ISSUE THREAD

**Issue by Dravion** [hmailserver/hmailserver#147]
Hi.
In my tests on Windows Server core i noticed the hmailserver.exe can run own its own if installed manually without the InnoDB installer (in my case with MySQL). But if it comes to Remote Administration there is no way to maintain the installation. I think it would be cool if we had  just a plain TCP/IP Port with command Tokens to do the same Admin Operations then as COM/DCOM and or just a hmailserver.conf file as alternative for Datacenter requirements.

**Comment by OutbackMatt** [comment]
Hey Dravion, I've set some robot scripts to perform tasks, when a specific account sends an email to another specific account, with a nominated subject line. Each subject performs a different task.

Also, is running a web server an option for you on server core (Apache works on core server versions), and then using the supplied PHPWebAdmin

**Comment by Dravion** [comment]
Hmm thats not excactly what iam looking for. Iam working on this feature a while now and would love to hear some feedback from Martin about it. The idea is very simple: Just using the same techique for remote management as we do for smtp (for instance: helo hms.mydomain.com, MAIL FROM: blahsame ect) but only diffrent command tokens.

**For example:**
CONNECT:127.0.0.1:6011
LOGIN: admin_user:admin_password
ADDUSER: loginname=donald;password=blah1
COMMIT
QUIT
(admin client disconnects from server)

_Bennefits: _
Access from most  OS/Devices with or without OLE/ActiveX/COM/DCOM support, no need for external thirdparty software components, it it much faster as DCOM because no marshalling 
and ole conversions is needed.

**Comment by martinknafve** [comment]
This is not something I will implement in the forseable feature. Since you've started on your own email server, I assume this is something which you'll add there as well.
