### ISSUE TITLE
hMailserver and Return-Path

### ISSUE THREAD

**Issue by baurez** [hmailserver/hmailserver#148]
Hi,

I'm using hmailserver for several years with a program of bulk/commercial mailing campains.

I started to threat automatically bounce message and for this I modified my program to add a Return-Path header to my message... but now I'm with 2 return-path headers.
- One from hmailserver who take the FROM address
- Another who is mine...

Is this a normal behavior ? How could I pass through ?

Thx !

**Comment by OutbackMatt** [comment]
This type of query should be on the forum please >> https://www.hmailserver.com/forum/

hMailserver doesn't add a return-path. This is set by your mail client
