### ISSUE TITLE
hMailServer IMAP returning incorrect SEARCH results based on location of NOT DELETED command.

### ISSUE THREAD

**Issue by jimxms** [hmailserver/hmailserver#149]
hMailServer appears to have issues with IMAP 'SEARCH' commands when the location of the 'NOT DELETED' flag is at the end of the SEARCH string. For example, on my mailbox if I perform the following command via telnet:

`UID SEARCH (OR FROM "eBay" (OR SUBJECT "eBay" (OR TO "eBay" (OR CC "eBay" BODY "eBay")))) NOT DELETED`

This will return UID's for the entire contents of my Inbox, regardless of whether it contains the 'eBay' anywhere in the email or not.

However, the following command:

`UID SEARCH NOT DELETED (OR FROM "eBay" (OR SUBJECT "eBay" (OR TO "eBay" (OR CC "eBay" BODY "eBay"))))`

Returns the correct result of one email.

I became aware of this issue when I attempted to search for items on my iPhone (iOS 9.2.1) connected to hMailServer (5.6.3-B2249) via IMAP. I would briefly get the correct results (from iOS searching local cache first) then as soon as it would query IMAP, I would get all emails from my inbox returned as incorrect results.

I posted about this issue on the hMailServer forums, documenting all of my testing right down to locating the issue.

https://www.hmailserver.com/forum/viewtopic.php?f=10&t=29203&p=184002#p184002

**Comment by martinknafve** [comment]
Fix will be included in next 5.6.5 build.
