### ISSUE TITLE
New OpenSSL build 1.0.1s and 1.0.2g kills hmailserver on all versions

### ISSUE THREAD

**Issue by raidensnake** [hmailserver/hmailserver#154]
I noticed hmailserver refuses to start since openassl disabled support for ssl v2 and ssl v3 as default to mitigate DROWN as mentioned here.
http://www.openssl.org/news/secadv/20160301.txt

**Comment by martinknafve** [comment]
hMailServer runs with both SSLv2 and SSLv3 disabled, so I don't think the DROWN issue is applicable. Either way, if you go to the hMailServer download page there's a new build bundling 1.0.1s of OpenSSL.
