### ISSUE TITLE
GUI: Add/Edit IP RANGE missing a 'cancel' button

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#156]
View 'Advanced - IP RANGE' summary list.  Click "ADD" to gain new entry screen, or "EDIT" on an existing entry.

There is no obvious 'back out'/cancel from this screen without clicking elsewhere on the left hand pane outside of IP RANGES and then clicking back to  IP RANGES.

Suggestion/mod:  Add a CANCEL button (to abort the add/edit.)

**Comment by martinknafve** [comment]
This does not just apply to IP ranges, but to all parts of the hMailServer user interface where you're adding or editing objects, right?

**Comment by jimimaseye** [comment]
Correct (from the few Ive tested - DOMAINS, ACCOUNTS, IP RANGES, ROUTES)

**Comment by martinknafve** [comment]
I won't fix this one, due to lack of time on my part.
