### ISSUE TITLE
Bug with Reverse IP (Query Failure 9560)

### ISSUE THREAD

**Issue by superman20** [hmailserver/hmailserver#157]
When hMailServer performs a reverse IP lookup, it is possible for the returned DNS record to be a classless IN-ADDR.ARPA delegation per [RFC 2317](http://www.rfc-editor.org/rfc/rfc2317.txt).  hMailServer does not handle these kinds of records and results in a Query Failure 9560 with the following debug output:

> "SMTPD"   3532   101   "2016-04-12 20:31:02.741"   "107.6.67.234"   "SENT: 354 OK, send."
> 
> "TCPIP"   3532   "2016-04-12 20:31:03.068"   "DNS - Query failure. Treating as temporary failure. Query: 234.232/29.67.6.107.in-addr.arpa, Type: 12, DnsQuery return value: 9560."
> 
> "DEBUG"   3532   "2016-04-12 20:31:03.068"   "Could not retrieve PTR record for IP (false)! 107.6.67.234"

Please see [this thread](https://www.hmailserver.com/forum/viewtopic.php?f=7&t=29601) in the forums for a detailed analysis (especially the last few postings).

I have identified the bug to be in function `DNSResolver::Resolve_`.  As an example, the IP address 107.6.67.234 will return successful DNS records from the API call.  However, for these types of IP's the DNS record contains the RFC 2317 classless in-addr.arpa delegation (in this case, "234.232/29.67.6.107.in-addr.arpa").  hMailServer is unaware of these types of records so it tries to find an exact string match for "234.67.6.107.in-addr.arpa" on line
`if (pDnsRecord->wType == wType && sSearchFor.Equals(name))`
hMailServer should instead recognize these types of records and determine that "234.67.6.107.in-addr.arpa" is included in "234.232/29.67.6.107.in-addr.arpa" and proceed with a positive match.

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, and this is a very old issue (which does not seem to affect many people), I will close this issue without action.
