### ISSUE TITLE
hMailServer.Message - subject and body not populated during API read

### ISSUE THREAD

**Issue by JadaVonRuth** [hmailserver/hmailserver#158]
`hMailServer.Message result = account.Messages.get_ItemByDBID(msgid);`

result.Subject - null
result.Body - null
result.HTMLBody - null

Subject and body are sometimes not populated for no reason even though emails message has body and subject for sure and ID of the message matches. It happens with outlook and exchange emails and some others but more probably it has to do with messagelocked = 1 in the database row of the message. SQL database has also table hm_message_metadata which is never filled. I havent found anything about it in your documentation. It would be much helpful if this would work properly.

**Comment by JadaVonRuth** [comment]
I am also experiencing another issues - hMailServer.Message.From contains wrong characters which are correct in embedded eml. Chars like "č" are mistreated as "è" and other diacritic chars like "ěščřž" are mistreated as "ì¹èø¾". Those are very common in czech language.. The same is for hMailServer.Message.Body

**Comment by martinknafve** [comment]
Closing since there's no plans to fix this. hMailServer is no longer under active development, and since it's not a critical bug it will be left without action.
