### ISSUE TITLE
Enhance table hm_messages - add & fill columns by system

### ISSUE THREAD

**Issue by JadaVonRuth** [hmailserver/hmailserver#159]
Optionaly get a possibility of direct reading basic metadata of emails from the database to get all the information about:

email adresses - from & to with the display names in separate columns
text perex containing first 100 chars of the email
read flag as bit
attachment flag as bit
incoming / outgoing flag as bit

This would improve the possibilities of hmailserver for realtime notifications and speedlisting where using 1 single SQL query I can eg. get all new unread messages with basic info for any user without having to iterate over all accounts and messages via pop3 or imap and parsing their bodies to get so little (there could be hundreds of accounts and thousands of emails), it also speeds up any client application because is is not much CPU and time consuming as the other methods.

**Comment by OutbackMatt** [comment]
Wouldn't this be achieved with a cut down version of the delivery log script??
https://www.hmailserver.com/forum/viewtopic.php?f=20&t=13890

**Comment by JadaVonRuth** [comment]
Yes it would but only if table hm_deliverylog had "messageid" column to be be joinable with table hm_messages. But documentation says this is executed before it is written to the database so ID of the message is not accessible. And without information about mailbox and folder it would be just a log totally separated from accounts context.

**Comment by martinknafve** [comment]
Nothing will be done with this in the near future, so I'm closing this for now without action (mainly due to lack of time).
