### ISSUE TITLE
Enhancement Request:  add a Comments/Description text box for RULE definitions

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#162]
Add a non-compulsory DESCRIPTION comments box to each rule (global and account level)  in order to optionally add descriptive text to each definition (similar to the existing description text box in ROUTES definitions). It helps to easily identify what the different rules are for without having to decipher them by Title name and condition/action definition. (Useful when you have multiple Rules in place and you dont want to duplicate them or create unwanted rules  - and also when you want to review them).
Suggestion: Maybe the Narrative Text could be saved in to a new table (eg, HM_NARRATIVE) that could hold links to other table records that could also have similar helpful narratives added (such as DNSBL definitions, IP RANGES, and Incoming Relays) - all with a new DESCRIPTION box added to their appropriate edit screens.  The addition table should be easy to implement/create on upgrade, will have a tiny footprint (containing a handful of records at best)  and an absence of records will not 'break' backward compatibility.

Graphical Suggestion:
![Image of DecriptionBox](https://www.hmailserver.com/forum/download/file.php?id=2712&mode=view)

**Comment by martinknafve** [comment]
Since hMailServer is no longer being actively developed, enhancements will only be included if authored as a PR with automated tests.
