### ISSUE TITLE
SMTP server error "550 Unsupported ESMTP extension" on MAIL FROM:... AUTH=<>   [with fix]

### ISSUE THREAD

**Issue by jsdza** [hmailserver/hmailserver#164]
hMailserver SMTP server erroneously aborts an inbound ESMTP connection if the MAIL FROM line contains the parameter "AUTH=<>"

This parameter should be ignored, however hMailserver is not parsing it correctly because of the following typo at line 473 of SMTPConnection.cpp:

`473:       else if (parameter.Left(**5**).CompareNoCase(_T("AUTH")) == 0)
`
where '5' should really be '4' (no of chars in "AUTH").  
Correcting the count to 4 resolves the problem.
_(Apologies for not submitting a proper patch for this 1 character fix)_

**Comment by martinknafve** [comment]
Thanks, fixed. Please note that this issue only exists in master branch, which is not a released version. In other words, please be aware that there may be more issues in this branch.

**Comment by jsdza** [comment]
Most welcome.  Thanks for a truly impressive piece of software (both inside and out!)
