### ISSUE TITLE
Hmailserver service install set to IGNORE_SHUTDOWN causing errors.

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#166]
When the system is shutdown/restarted (maybe due to manual shutdown or automatic Windows Update overnight) it is quite common to see errors similar to the following appear:

> "ERROR"	4224	"2014-12-10 21:14:50.985"	"Severity: 2 (High), Code: HM5033, Source: DALRecordset::Open, Description: **MySQL: Query execution was interrupted (Additional info: select * from hm_fetchaccounts where fanexttry <= NOW() and falocked = 0 and faactive = 1 order by faid asc)**"
"ERROR"	4556	"2015-12-03 08:22:47.191"	"Severity: 2 (High), Code: HM5033, Source: DALRecordset::Open, Description: **MySQL: Query execution was interrupted (Additional info: select * from hm_fetchaccounts where fanexttry <= NOW() and falocked = 0 and faactive = 1 order by faid asc)**"
"ERROR"	4556	"2015-12-03 08:22:47.362"	"Severity: 2 (High), Code: **HM5033, Source: DALRecordset::Open, Description: MySQL: Query execution was interrupted** (Additional info: SELECT  *  FROM hm_accounts WHERE accountaddress = 'sales@mydomain.com')"
"ERROR"	4556	"2015-12-03 08:22:47.362"	"Severity: 2 (High), Code: **HM5033, Source: DALRecordset::Open, Description: MySQL: Query execution was interrupted** (Additional info: SELECT  *  FROM hm_accounts WHERE accountaddress = 'sales@mydomain.com')"

This has been seen and discussed many times on the forum.

It happens due to the DATABASE service (eg, MySQL) actually being shutdown (by windows) whilst the Hmailserver service remains up - and __this is despite the Hmailserver service having a DEPENDENCY__ on the associated database service ("MySQL") in the service property (as assigned usually at installation stage).  In other words, being dependent on the database service doesnt make a difference - HMS never shuts down before the MySQL and consequently the above error can happen (quite regularly actually) at system shutdown time due the HMS trying to access a database that has since been stopped.

The cause seems to be that the Hmailserver service is set with the property of "IGNORE_SHUTDOWN" which prevents the service from being stopped by a system shutdown in the controlled way.
In context, to demonstrate:

> **sc query mysql**
> 
> SERVICE_NAME: mysql
>         TYPE               : 10  WIN32_OWN_PROCESS
>         STATE              : 4  RUNNING
>                                 (STOPPABLE, PAUSABLE, **ACCEPTS_SHUTDOWN**)
>         WIN32_EXIT_CODE    : 0  (0x0)
>         SERVICE_EXIT_CODE  : 0  (0x0)
>         CHECKPOINT         : 0x0
>         WAIT_HINT          : 0x0

Here you can see that MySQL, like many other 'normal' services, have the service property as "ACCEPTS_SHUTDOWN".

However:

> **sc query hmailserver**
> 
> SERVICE_NAME: hmailserver
>         TYPE               : 10  WIN32_OWN_PROCESS
>         STATE              : 4  RUNNING
>                                 (STOPPABLE, NOT_PAUSABLE, **IGNORES_SHUTDOWN**)
>         WIN32_EXIT_CODE    : 0  (0x0)
>         SERVICE_EXIT_CODE  : 0  (0x0)
>         CHECKPOINT         : 0x0
>         WAIT_HINT          : 0x0

You see that hmailserver has this property that prevents its controlled termination at shutdown time.

Hmailserver service needs to be installed with the appropriate property of "**ACCEPTS_SHUTDOWN**" to allow it to be shutdown before the database service and therefore preventing the errors as details above.

(For the record I personally dont have any knowledge on how services are created or how you go about making this change.  I have tried googling extensively but remain clueless - I imagine it might be something to do with process ownership 'SYSTEM, 'LOCAL' etc... (but who knows).  All I know is that there are process created that 'ACCEPTS_SHUTDOWN', is 'PAUSABLE' etc, and there are those (such as HMS) that do not.  Obviously there is a difference in the creating of the service.)

**Comment by martinknafve** [comment]
Fixed. But the issue was not related to the installation of the Windows service. When a Windows service has started, it notifies Windows that it's running and what control operations it accepts. This is where hMailServer was previously only accepting STOP requests, but now it also accepts SHUTDOWN requests.
