### ISSUE TITLE
Ability to have HMS display current OpenSSL in actual use

### ISSUE THREAD

**Issue by Blitz2016** [hmailserver/hmailserver#169]
It seems easy enough to upgrade HMS to the latest OpenSSL libraries. Problem is corporate audits. More and more as security becomes paramount, corporate auditors are going to want to see physical proof that critical services, such as HMS, are running the latest version of security.

Even if under the "Status" tab included is current version of OpenSSL running would do. Taking a screenshot of the Status page and attaching it to the audit forms should satisfy corporate auditors.

Like it or not kids, corporate audits are critical and will play a huge part in keeping our jobs. Corporate VP's want their vacation photos (etc.) kept private and if they show up on a hacker site, they will be looking for scalps. If we can prove OpenSSL is current, we can hopefully survive.

**Comment by jimimaseye** [comment]
From: https://www.hmailserver.com/forum/viewtopic.php?f=2&t=29785

**Comment by martinknafve** [comment]
This won't be implemented, due to lack of time on my part.

**Comment by jimimaseye** [comment]
@RvdHout @OutbackMatt Simple to include?  Worth doing?  Or verging on moving from 'simple uncluttered' interface to 'cluttered with barely useful' display?
