### ISSUE TITLE
Enhancement Request: Make default path for DKIM certificate to be root of the DOMAIN data directory

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#170]
Currently, when entering a DKIM certificate, you browse to point to your file and it records the full path.  If, however, a backup is performed, that setting is maintained (including the full path) but the file is not necessarily included.  Furthermore, upon restore after a migration, that path may not be valid and therefore the certificate file is not found.  This results in big crashes such as:

> "ERROR" 1908 "2016-04-05 11:38:03.606" "Severity: 3 (Medium), Code: HM5026, Source: PersistentMessage::_WriteDataToMessageFile, Description: Message retrieval failed because message file C:\hmailserver\Data--PATH TO FILE--.eml did not exist."
> "ERROR" 1896 "2016-04-05 11:42:51.582" "Severity: 3 (Medium), Code: HM4227, Source: File::ReadFile, Description: An unknown error occurred while reading file from disk."
> "ERROR" 1896 "2016-04-05 11:42:51.582" "Severity: 2 (High), Code: HM4208, Source: ExceptionHandler::Run, Description: An error occured while executing 'Task-DeliveryTask', Message: Attempt to read from file which has not been opened."

My suggestion is to make the DEFAULT path to look for the certificate file to be in the root of the DOMAIN in the data directory (with an advisory/suggestion to do so).  eg:

[DATA directory]
......|--- DOMAIN1
..............|- "dkim.domain1.pem"  (Certificate file here)
..............|- AA
..............|- AB
..............|- etc
......|--- DOMAIN2
..............|- "dkim.domain2.pem" 
..............|- AA
..............|- AB
..............|- etc

Benefits:
1, Keeping it in the root of the DOMAIN data directory ensures it is included automatically in backup/restore operations and it will not get missed or forgotten in migrations.  So simply not stating a path and just having certificate file (eg, "dkim.yourdomain.pem") **without** a path means it looks in this data root of the individual domain and this in turn means it will always be included in backups/restores and migrations and you wouldnt have the problem of misconfiguration (leading to the above errors).

2, The proposed change doesnt affect EXISTING installations where people have pointed to a certificate file with full path as the inclusion of the path will override the default 'assumed' path.  Also, users still have the option to place a certificate where they like by stating the path.  (It leaves them free to not state a path or have its location assumed as above).  So they can still upgrade without a problem.

3,  New installations/setups (with an advisory to use this proposed directory) can place the file in the Domain root safe in the knowledge future backup/restore/migrations will never cause them a problem.

Example (one of many) of someone with this problem: https://www.hmailserver.com/forum/viewtopic.php?f=7&t=2953

**Comment by OutbackMatt** [comment]
I use a sub folder of the external's folder, like ,,/hMailserver/Externals/certs
Perhaps we should have a certificates folders in the hMailserver.ini like we already have a data folder, a log folder a temp folder  etc

**Comment by martinknafve** [comment]
Since hMailServer is no longer being actively developed, enhancements will only be included if authored as a PR with automated tests.
