### ISSUE TITLE
DKIM on rule 'reply' not applied

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#172]
Scenario:

1, DKIM signing setup and enabled - Sending an email with email client signs the email correctly (with the usual "dkim-signature:" header).

2, Set up an Account Rule with a "REPLY (email)" as an action (all fields filled correctly).

BUT the received reply email (sent by the rule) does not get DKIM signed.

Full details and headers showing the problem here: https://www.hmailserver.com/forum/viewtopic.php?f=7&t=29799

**Comment by RvdHout** [comment]
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=33976&p=211807#p211807

**Comment by martinknafve** [comment]
Included in 5.7.
