### ISSUE TITLE
hMailServer executable versions not set

### ISSUE THREAD

**Issue by YasharF** [hmailserver/hmailserver#174]
The file versions for hMailServer executables seem to be not set correctly.  On hMailServer 5.6.5 - Build 2360, when right clicking on the files in windows explorer and going to the details tab, the following versions are being reported instead of 5.6.5.2360:

hMailServer.exe -  File version 1.0.0.1 , product version 1.0
hMailAdmin.exe -  File version 5.0.0.0 , product version 5.0.0.0.

**Comment by YasharF** [comment]
I think the issue are all of these folks:  https://github.com/hmailserver/hmailserver/search?utf8=%E2%9C%93&q=AssemblyVersion

reference: http://stackoverflow.com/questions/23358599/visual-studio-2013-version-number-for-exe-file

**Comment by martinknafve** [comment]
Thanks. This issue has already been fixed for hMailServer.exe in 5.7, but I'll fix it for hMailAdmin and the other tools as well.
