### ISSUE TITLE
Enhancement: Reject BACKUP PATH if within current data directory.

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#175]
Some people are a little bit stupid and shouldnt be given any sharp implements and or anything breakable, and needs adult supervision.

Enhancement Suggestion: Implement a check (and rejection where necessary) to ensure that their chosen BACKUP DESTINATION PATH isnt actually within the Hmailserver DATA directory.  Otherwise looping and errors occur, and general confusion ensues to such individuals.

Genuinely:  https://www.hmailserver.com/forum/viewtopic.php?p=186428#p186428

**Comment by martinknafve** [comment]
This won't be implemented, due to lack of time on my part.

**Comment by jimimaseye** [comment]
@RvdHout   I think this seems an easy one and something you can quickly apply?  (A straight IF condition check on the path being quoted at the time of entry)
