### ISSUE TITLE
Diagnostic reports error: Could not connect...since this would mean connecting to myself

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#177]
In 5.7 a diagnostic reports the error:

> Trying to connect to TCP/IP address 85.214.126.1 on port 25.
> ERROR: It was not possible to connect. **Error: Could not connect to 85.214.126.1 on port 25 since this would mean connecting to myself.**

Whereas in 5.6 it reads correctly as

> Trying to connect to TCP/IP address 85.214.126.1 on port 25.
> Received: 220 mail.eckgold.eu ESMTP.
> Connected successfully.

Error seems to be in current 5.7 offering.
Full details: https://www.hmailserver.com/forum/viewtopic.php?f=10&t=29861

**Comment by martinknafve** [comment]
Fixed in 5.7, build Build 2483.
