### ISSUE TITLE
Enhancement: AUTO-BAN screen - change "Minutes to auto-ban" literal text

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#179]
The screen itself is not fully explanatory by the choice of literals in the English version of of the 'auto-ban' screen.  (I am very aware of the screen, advise on it, and even now after years of using it I still have to keep referring to the manual to actually decipher the fields due to the confusion highlighted below).

In particular "Minutes to Autoban".

The confusion:  When reading it initially it interprets as in "How many **minutes to wait before we autoban** the address?"  This causes the confusion about what the value is supposed to be (and actually can be confused for the 2nd field 'minutes before reset').  Obviously this is not what is meant (I think the thought process when initially choosing the wording was "_how many **minutes to autoban** the address for?_")

Proposal:

Could we change the literal 642 in the ENGLISH language form from:

`String_642=Minutes to auto-ban`

to

`String_642=Auto-ban period (minutes)`

"Auto-ban period (minutes)" is very clearly stating the period that autoban remains in effect (and doesnt need to be looked up in the documentation  every time).

Further enhancement may be also changing
`String_641=Minutes before reset`

to 
`String_641=Invalid login period (minutes)`

I believe this proposal to be far clearer and evident without the need for referral to documentation to clear confusiuon.

**Comment by jimimaseye** [comment]
IMPORTANT:  there is a bug that the AUTOBAN screen fails to display the language.ini file for these literals (and they seem hardcoded) fhttps://github.com/hmailserver/hmailserver/issues/179.  So the bug needs fixing to allow the above proposed changes to take effect.

**Comment by martinknafve** [comment]
Since hMailServer is no longer being actively developed, enhancements will only be included if authored as a PR with automated tests.
