### ISSUE TITLE
Mailbox unavailable. The server response was: A valid address is required.

### ISSUE THREAD

**Issue by nicosha** [hmailserver/hmailserver#184]
Hello.

I've got a problem with HMailServer. I use mailbox aliases  contains valid symbols "|" and "?" . For example: etikhonov+va|id?@gmail.com

And HMailServer return error:
Mailbox unavailable. The server response was: A valid address is required.

Could you please fix your regexp expression for checking validation?

Thank you

**Comment by martinknafve** [comment]
Thanks for your report. This (handling of special characters  in the email address) was fixed a couple of weeks ago for hMailServer 5.6.5.
