### ISSUE TITLE
Application logging fails to show service shutdown/startup

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#185]
Under 5.6.4, if the external HMS service was stopped and restarted at OS level, applcation log would show:

> "APPLICATION"	2136	"2016-06-20 20:00:00.635"	"Stopping servers..."
> "APPLICATION"	2136	"2016-06-20 20:00:01.274"	"Servers stopped."
> "APPLICATION"	4208	"2016-06-20 20:00:39.806"	"Starting servers..."
> "APPLICATION"	4208	"2016-06-20 20:00:40.259"	"Servers started."

Very useful when tracking through logs (for example in the case of a time delay).

However, under 5.6.5 b2367 a stop and restart of the service fails to how any such logging at all.  Therefore if you are experiencing lengthy delays operation, and review the log to analyse and see why, you will never see the real cause (being the service has been stopped).

(The service could have been stopped for all manner of reasons and sometimes even your own memory can let you down).

**Comment by martinknafve** [comment]
I did a clean install of 5.6.5 b2367 and enabled application logging. I then restarted the hMailServer service (using NET STOP/NET START and saw the following in the logs:
```
"APPLICATION"	10716	"2016-06-21 07:22:47.062"	"Stopping servers..."
"APPLICATION"	10716	"2016-06-21 07:22:47.065"	"Servers stopped."
"APPLICATION"	7716	"2016-06-21 07:22:51.785"	"Starting servers..."
"APPLICATION"	7716	"2016-06-21 07:22:52.057"	"Servers started."
```

So it seems to work for me. Can you confirm that you've got application logging enabled?

**Comment by jimimaseye** [comment]
I shouldnt even respond due to the highest level of embarrassment.  It wasnt that I didnt have Application logging, it was worse than that.

I was stopping and starting the wrong service!!  And I tried this over and over again and just couldnt understand why it wasnt logging.

Oh the shame.

Sorry.
