### ISSUE TITLE
Feature request to enable group and distribution list selections in admin user account panel

### ISSUE THREAD

**Issue by visualperception** [hmailserver/hmailserver#187]
Feature request to enable group and distribution list selections in admin user account panel

the idea being simplify admin of an account and to be able to more easily categorise your accounts by for example, department, and to more easily search for user name if you know which category/dept the user is in. Doesn't require any databse mods and so is only an admin gui/web change.

see topic : https://www.hmailserver.com/forum/viewtopic.php?f=2&p=188191#p188191

**Comment by martinknafve** [comment]
Closing this, since this won't be done in the near future due to lack of time.
