### ISSUE TITLE
PHPWebAdmin With IIS 8.5 on WS 2012R2

### ISSUE THREAD

**Issue by MrGadget1024** [hmailserver/hmailserver#190]
Please update documentation for IIS 8.5 Win Server 2012 IIS 8.5
- IIS App pool runs under Network Service - needs full rights to PHPWebAdmin folder
  ------ No need for IIS_IUSRS to be granted anything special.
- Can use the PHPWebAdmin folder where hMailServer installed, just give rights as above
- No need to mess with DCOM Config - Install PHP 7 from Web Platform Installer and it's done
  ------ PHP Manager is added to server level IIS - can enable php_com_dotnet.dll from there.
  ------ register_globals was deprecated and doesn't exist in PHP 7.x

https://www.hmailserver.com/documentation/latest/?page=howto_install_phpwebadmin

**Comment by OutbackMatt** [comment]
I have updated the documentation.
Please check and offer further clarification...

FYI, I use IIS10 and PHP 5.4.xx on my Windows 10 Pro machine, and the php_com_dornet.dll was the same as you wrote.

Thanks
