### ISSUE TITLE
Restore browsing gives error on core server

### ISSUE THREAD

**Issue by tunis78** [hmailserver/hmailserver#191]
On a 2012r2 Core hyper-v server browsing to a backup file gives error:

`Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111.`

Restore option and start button are all grayed out, so I cannot type in manually the path and start restoring.

**Comment by tunis78** [comment]
I saw manually typing of path was added to 5.7.0.

**Comment by martinknafve** [comment]
The error you're getting indicates an issue with the Windows install rather than hMailServer. This is an old bug, and due to lack of time I won't spend time investigating this.
