### ISSUE TITLE
hMailServer.sdf - password unknown

### ISSUE THREAD

**Issue by Dravion** [hmailserver/hmailserver#197]
Hi,
I cannot access this MSSQL CE compact Databasefile because it says its password protected but the DB-Password is not the same then the Inno Installer requested durning installation:

[Database]
Type=MSSQLCE
Username=
Password=-...<-- what password is this?

Its automatically set by the InnoInstaller i gues, but as allready mentioned, its not the same
password then COM Login Administrator -why? For any other DB its the same password  for
the COM API and the DB-Login.

**Comment by martinknafve** [comment]
The database password in hMailServer.ini is stored encrypted using Blowfish. You can decrypt it using the script hMailServer\Addons\Utilities\DecryptBlowfish.vbs (it first asks you for your hMailServer Administrator password, and then the encrypted string). The database password and the COM login password are only the same if you enter the same password when you set up hMailServer Administrator.

The database password is used by hMailServer to authenticate towards the database. The password encryption scheme is not secret nor is the key used to encrypt it. The intention is to just make it slightly less obvious if someone happens to see the string over your shoulder.

The hMailServer Administrator / COM password is used by you as a user to authenticate towards hMailServer.

The two passwords have no relation to eachother. You could use the same passwords, but as a general rule it's better to have separate passwords for separate services.

**Comment by Dravion** [comment]
Iam not quite sure you understand me correctly.
 I want to open "hMailServer.sdf" with Visual Studio SQL CE Database Editor or Powershell without even touch hMailServers COM Interface. 

*After hMailServer i noticed the following.
1) Installing on MySQL, the DB-User/Password can be setup with MySQL builtin Admin (mysql.exe)
2) Installing on MSSQL-Server, the DB-User/Password can be setup DB-Management Stdudio
3) Installing on Postgres, the DB-User/Password can be setup ip with PgAdmin3

If it comes to MS-SQL Compact 3.5 or 4.0 i cannot open 
C:\Program Files (x86)\hMailServer\Database\hMailServer.sdf with tools like CEQuery or SQLIteCE
Toolbox because it sasys the provided Password (setup by the Inno-Setup installer for a MSSQL CE
Installation is wrong.

However: i used DecryptBlowfish.vbs to get the correct password for hMailServer.sdf  but the script
returns a string by providing hMailServers password but if i use this encrypted string as Password in
an OLEDB String like this_: Data Source=C:\Program Files (x86)\hMailServer\Database\hMailServer.sdf;Password=RòYpç'  i get a .NET Format initialization Error.

Ok, make long story short - what is the Password for hMailServer.sdf ?
On which point is the password  for hMailServer.sdf is set durning Inno Setup Installation?
