### ISSUE TITLE
Certain domain requires slow communication to have emails delivered

### ISSUE THREAD

**Issue by oromand** [hmailserver/hmailserver#207]
When delivering email to certain domains (orange.fr/wanadoo.fr), this provider requests the sender server to speak sloooooowly (never heard of that before), as explained in this page: http://www.john-web.fr/640/developpement-web/plesk/wanadoo-et-orange-refusent-les-mails-trop-de-connexions.html

Is there any way to achieve this in hmail "natively" ?

Thanks for your answer

**Comment by oromand** [comment]
I bumped against this thread that is what I want to achieve; https://www.hmailserver.com/forum/viewtopic.php?t=21266

What would be the necessary changes to have maybe a route handling this ?

**Comment by TimurZanagar** [comment]
I'm interested, too.

**Comment by martinknafve** [comment]
This won't be implemented, due to lack of time on my part.
