### ISSUE TITLE
Unrecognised problem.

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#213]
V5.6.6-b2383

A problem occurred which I think is a bug.  I dont know the cause of the problem but I think it is one of those 'chance in a million' moments (my system has never had this before and after checking there is no reason why my system would have been the cause).  I only have the symptoms which will shows the error.  Hopefully it will help raise an investigation which highlights the cause.

Scenario:
The system is more or less idle - its overnight - everyone is in bed. The odd email comes in (these are collected by External Download). No antivirus is running.  At 5:18 a single email comes in and this is the resultant error:

> "APPLICATION"	3504	"2017-02-08 05:18:02.214"	"SMTPDeliverer - Message 341171: **Delivering message** from yourinvoice@rightfuelcard.net to sylvester@mydomain.net. File: D:\Datastore\hMailData\**{5BC45CEB-DAEF-4F9A-BE32-F87E25932E8D}.eml**"
> "ERROR"	3504	"2017-02-08 05:18:36.159"	"Severity: 2 (High), Code: HM5049, Source: File::Normal, Description: **Could not move** the file **D:\Datastore\hMailData\mydomain.net\sales\5B\{5BC45CEB-DAEF-4F9A-BE32-F87E25932E8D}.eml.tmp** to D:\Datastore\hMailData\mydomain.net\sales\5B\{5BC45CEB-DAEF-4F9A-BE32-F87E25932E8D}.eml. Tried 5 times without success., Error code: 5, Message: **Access is denied**"
> "APPLICATION"	3504	"2017-02-08 05:18:38.905"	"SMTPDeliverer - Message 341171: Message delivery thread completed."
> "ERROR"	2640	"2017-02-08 05:18:39.763"	"Severity: 3 (Medium), Code: HM5136, Source: TCPConnection::AsyncReadCompleted, Description: An error occured while parsing data. Data length: 186, Data: 12 UID FETCH 38444,38443 (UID FLAGS INTERNALDATE RFC822.SIZE BODY.PEEK[HEADER.FIELDS (date subject from content-type to cc reply-to message-id references in-reply-to X-K9mail-Identity)]). Remote IP: 94.15.195.214"
> "ERROR"	2640	"2017-02-08 05:18:40.434"	"Severity: 2 (High), Code: HM4208, Source: ExceptionHandler::Run, Description: An error occured while executing 'IOCPQueueWorkerTask', Error code: 5, Message: boost::filesystem::status: Access is denied: "D:\Datastore\hMailData\mydomain.net\sales\5B\{5BC45CEB-DAEF-4F9A-BE32-F87E25932E8D}.eml""
> "ERROR"	2640	"2017-02-08 05:18:48.093"	"Severity: 1 (Critical), Code: HM5519, Source: StackLogger::Log, Description: An error has been detected. A mini dump has been written to C:\Program Files (x86)\hMailServer\Logs\minidump_2017-02-08 051841_{24DBCD5C-2B67-4967-B44B-BD3321E5D858}.dmp"
> "ERROR"	4640	"2017-02-08 05:18:49.466"	"Severity: 3 (Medium), Code: HM5026, Source: PersistentMessage::_WriteDataToMessageFile, Description: Message retrieval failed because message file D:\Datastore\hMailData\mydomain.net\sales\5B\{5BC45CEB-DAEF-4F9A-BE32-F87E25932E8D}.eml did not exist."
> 

It left this file:

**D:\Datastore\hMailData\mydomain.net\sales\5B\{5BC45CEB-DAEF-4F9A-BE32-F87E25932E8D}.eml.tmp**

Note it is the .TMP file (which was denied access/locked according to the log..

This email was not imported due to
"ERROR"	3504	.....: **Could not move** the file **D:\Datastore\hMailData\mydomain.net\sales\5B\{5BC45CEB-DAEF-4F9A-BE32-F87E25932E8D}.eml.tmp** to D:\Datastore\hMailData\mydomain.net\sales\5B\{5BC45CEB-DAEF-4F9A-BE32-F87E25932E8D}.eml. Tried 5 times without success., Error code: 5, Message: Access is denied"

The remaining ERRORs relate to my mobile phone doing periodic checking whilst I sleep - and clearly it sees that the message appears in the list of new messages yet then fails to retrieve them due to it not actually existing.

All other emails before and after this event have come in without a problem.

This is the resultant dump:
[minidump_2017-02-08 051841_{24DBCD5C-2B67-4967-B44B-BD3321E5D858}.zip](https://github.com/hmailserver/hmailserver/files/760482/minidump_2017-02-08.051841_.24DBCD5C-2B67-4967-B44B-BD3321E5D858.zip)

Hopefully it uncovers a cause and maybe highlights an otherwise unknown oversight/bug that happens in a million-to-one chance (but happens all the same).

**Comment by RvdHout** [comment]
Looks like a permission issue, i assume you excluded D:\Datastore\hMailData from virusscanner?
*.tmp files should only exist in either the root of the defined /Data path or hmailserver defined /Temp path to my knowledge

**Comment by jimimaseye** [comment]
There is no realtime AV present.  The only virus scanning occurring is through ClamAV (upon receiving the email as per normal hmailserver operation).

Whether the .TMP file is correctly or incorrectly in the domain specific folder or not is not too important (although I suspect it is operating as it is coded to operate) - the main thing is this all happened under 'normal operation' of the server (ie, it does what it does as it has always done) and it has never happened in 6 years.  I have checked and ruled out any 3rd party software (there isnt anything other than spamassassin running anyway) and also disk errors (it was a temporary Access Denied rather than a read failure and the file is now available to delete proving the 'lock' denying the access has now been released.  This would not be the case if it was disk hardware error).

The email itself is a simple PLAIN TEXT body only with a single .PDF mime attachment of 60kb (its an incoming invoice). So nothing out of the ordinary.

**Comment by Dravion** [comment]
Looks like the incoming Email was successfully but temporary written to a *.eml.tmp file.
The next step would be a move file to it's final destination but at this moment hMailServer 
getting its Access Denied Error from Windows.

Possible causes:
1) File already exists and cannot be overwritten (try to delete it manually cound help)
2) hMailServer.exe Service User account has restricted permissions to write to DATA Folder
3) Hardware I/O Error (check for bad blocks)

**Comment by paulmann** [comment]
This 'Access Denied' error often stems from the Real-time Protection engine locking the message file while the External Scanner is also trying to access it.
A robust workaround is to use a wrapper script that copies the message to a dedicated %TEMP% buffer before scanning, keeping the production Data folder clean from locks. I've implemented this workflow in my PowerShell bridge project: [hMailServer-External-Antivirus](https://github.com/paulmann/hMailServer-External-Antivirus). It also includes a detailed guide on mandatory folder exclusions to prevent these conflicts.
