### ISSUE TITLE
recipients.originaladdress / catch-all problem. recipients.count always 1.

### ISSUE THREAD

**Issue by SorenRR** [hmailserver/hmailserver#214]
When multiple emails are sent to hMailServer within the same session and the recipients are translated eg. via Catch-All to the same target account, the original recipients are partly lost.

In the example below accounts exist for john.user and jane.user. john.doe and jane.doe do NOT exist thus they are referred to the catchall account.
`
"SMTPD"	2452	11644	"2017-02-11 23:43:50.164"	"209.85.223.171"	"SENT: 220 mx.acme.inc ESMTP"
"SMTPD"	1704	11644	"2017-02-11 23:43:50.305"	"209.85.223.171"	"RECEIVED: EHLO mail-io0-f171.google.com"
"SMTPD"	1704	11644	"2017-02-11 23:43:50.352"	"209.85.223.171"	"SENT: 250-mx.acme.inc[nl]250 SIZE"
"SMTPD"	1704	11644	"2017-02-11 23:43:50.492"	"209.85.223.171"	"RECEIVED: MAIL FROM:<*unknown*@gmail.com> SIZE=2236"
"SMTPD"	1704	11644	"2017-02-11 23:43:51.274"	"209.85.223.171"	"SENT: 250 OK"
"SMTPD"	1704	11644	"2017-02-11 23:43:51.430"	"209.85.223.171"	"RECEIVED: RCPT TO:<joe.user@acme.inc>"
"SMTPD"	1704	11644	"2017-02-11 23:43:51.445"	"209.85.223.171"	"SENT: 250 OK"
"SMTPD"	1704	11644	"2017-02-11 23:43:51.586"	"209.85.223.171"	"RECEIVED: RCPT TO:<jane.user@acme.inc>"
"SMTPD"	1704	11644	"2017-02-11 23:43:51.586"	"209.85.223.171"	"SENT: 250 OK"
"SMTPD"	1704	11644	"2017-02-11 23:43:51.742"	"209.85.223.171"	"RECEIVED: DATA"
"SMTPD"	1704	11644	"2017-02-11 23:43:51.758"	"209.85.223.171"	"SENT: 354 OK, send."
"SMTPD"	2224	11644	"2017-02-11 23:43:53.617"	"209.85.223.171"	"SENT: 250 Queued (1.844 seconds)"
"SMTPD"	1512	11644	"2017-02-11 23:43:53.774"	"209.85.223.171"	"RECEIVED: QUIT"
"SMTPD"	1512	11644	"2017-02-11 23:43:53.774"	"209.85.223.171"	"SENT: 221 goodbye"

2224		"2017-02-11 23:43:53.602"	"OnAcceptMessage(oClient, oMessage) oMessage.Recipients(ix).Address -> joe.user@acme.inc, jane.user@acme.inc"
2224		"2017-02-11 23:43:53.602"	"OnAcceptMessage(oClient, oMessage) oMessage.Recipients(ix).OriginalAddress -> joe.user@acme.inc, jane.user@acme.inc"

"SMTPD"	2452	11646	"2017-02-11 23:46:53.149"	"209.85.223.169"	"SENT: 220 mx.acme.inc ESMTP"
"SMTPD"	2452	11646	"2017-02-11 23:46:53.305"	"209.85.223.169"	"RECEIVED: EHLO mail-io0-f169.google.com"
"SMTPD"	2452	11646	"2017-02-11 23:46:53.336"	"209.85.223.169"	"SENT: 250-mx.acme.inc[nl]250 SIZE"
"SMTPD"	2452	11646	"2017-02-11 23:46:53.492"	"209.85.223.169"	"RECEIVED: MAIL FROM:<*unknown*@gmail.com> SIZE=2236"
"SMTPD"	2452	11646	"2017-02-11 23:46:53.836"	"209.85.223.169"	"SENT: 250 OK"
"SMTPD"	2452	11646	"2017-02-11 23:46:53.977"	"209.85.223.169"	"RECEIVED: RCPT TO:<john.doe@acme.inc>"
"SMTPD"	2452	11646	"2017-02-11 23:46:53.977"	"209.85.223.169"	"SENT: 250 OK"
"SMTPD"	2452	11646	"2017-02-11 23:46:54.133"	"209.85.223.169"	"RECEIVED: RCPT TO:<jane.doe@acme.inc>"
"SMTPD"	2452	11646	"2017-02-11 23:46:54.133"	"209.85.223.169"	"SENT: 250 OK"
"SMTPD"	2452	11646	"2017-02-11 23:46:54.289"	"209.85.223.169"	"RECEIVED: DATA"
"SMTPD"	2452	11646	"2017-02-11 23:46:54.289"	"209.85.223.169"	"SENT: 354 OK, send."
"SMTPD"	2224	11646	"2017-02-11 23:46:55.289"	"209.85.223.169"	"SENT: 250 Queued (0.984 seconds)"
"SMTPD"	1512	11646	"2017-02-11 23:46:55.445"	"209.85.223.169"	"RECEIVED: QUIT"
"SMTPD"	1512	11646	"2017-02-11 23:46:55.445"	"209.85.223.169"	"SENT: 221 goodbye"

2224		"2017-02-11 23:46:55.274"	"OnAcceptMessage(oClient, oMessage) oMessage.Recipients(ix).Address -> catchall@acme.inc"
2224		"2017-02-11 23:46:55.274"	"OnAcceptMessage(oClient, oMessage) oMessage.Recipients(ix).OriginalAddress -> john.doe@acme.inc"

'      Dim ix, strEnvelope1, strEnvelope2
'      For ix = 0 To oMessage.Recipients.Count-1
'         If (ix = 0) Then
'            strEnvelope1 = oMessage.Recipients(ix).Address
'            strEnvelope2 = oMessage.Recipients(ix).OriginalAddress
'         Else
'            strEnvelope1 = strEnvelope1 & ", " & oMessage.Recipients(ix).Address
'            strEnvelope2 = strEnvelope2 & ", " & oMessage.Recipients(ix).OriginalAddress
'         End If
'      Next
'      EventLog.Write("OnAcceptMessage(oClient, oMessage) oMessage.Recipients(ix).Address         -> " & strEnvelope1)
'      EventLog.Write("OnAcceptMessage(oClient, oMessage) oMessage.Recipients(ix).OriginalAddress -> " & strEnvelope2)
`

**Comment by martinknafve** [comment]
Looks to me like OrignialAddress would need to be a list of strings rather than a single string, right?

**Comment by SorenRR** [comment]
It could work... But it would require additional coding scriptwise and you would need to check Recipient.Address = Domain.Postmaster to determine if Recipient.OriginalAddress is a list that needs splitting.

Anyways, Since it's a specialist/automation feature, I'm happy with an option in the ini file to disable address consolidation.

If you can point me in the right direction I can do some testing myself - I have not been able to find the exact spot where duplicate recipients are filtered. I'm guessing it's somewhere in RecipientParser.cpp.

**Comment by SorenRR** [comment]
@martinknafve, in the light of the changes to core with respect to the "Return-"Reply" header to assist SpamAssassin and the "X-hMailServer-Envelope-From" header perhaps the best way to solve this subj. is to add "X-hMailServer-Envelope-To" as a comma separated string pre-translation by Alias, +addressing, distributionlists and Catch-all.
https://tools.ietf.org/html/rfc5321#section-3.7.1 suggests to add "Envelope" headers for gatewaying and we have on the forum had an issue recently involving a SMS gateway addressed by +addressing where SMS recipients potentially are lost.
https://www.hmailserver.com/forum/viewtopic.php?p=228548#p228548

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, and this is a very old issue (which does not seem to affect many people), I will close this issue without action. I realize that you may still want this fixed, but I don't want to give the false impression that this is something being worked on.
