### ISSUE TITLE
Bind to local IP address if you implement IPv6

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#215]
I think....

That if I enable IPv6 on the machine with hMailsevrer installed the I can't use the 'Bind to Local IP Address' feature. It generates errors.

**Comment by martinknafve** [comment]
I have been using IPv6 on my computers for years and haven't seen any issues with the bind to local IP address feature. I realize this is a really old issue, but if you're still seeing issues then please update this with the error message and I'll reopen it.
