### ISSUE TITLE
5.7 b2411 - External Download failure with CNAME/alias records

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#217]
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=30974

Summary:
Where External Download server stated is a CNAME record/alias then hmailserver fails to recurse and obtain the parent A record and fails with:
"The IP address for external account [name] could not be resolved. Aborting fetch."

Problem doesnt exist in production 5.6.6.

**Comment by martinknafve** [comment]
Fixed in 5.7, build 2482
