### ISSUE TITLE
Cannot copy email to public folder, function "MessageUtilities::CopyToIMAPFolder" only check user folder, not public

### ISSUE THREAD

**Issue by jamespira** [hmailserver/hmailserver#218]
Using API to move emails to public folder, and only getting error "Unable to copy message".

Reason was the function "MessageUtilities::CopyToIMAPFolder", before copying an email to destination, this function checks if the destination folder exists, however it only check folders under user account, it doesn't check public folders.
So this function think the destination folder doesn't exist thus giving the error.

Link to code:
https://github.com/hmailserver/hmailserver/blob/a7821cbafe927b8d8c7666fa856909ab2784b76d/hmailserver/source/Server/Common/Util/MessageUtilities.cpp

 // <-- indicates where the error is below

`
MessageUtilities::CopyToIMAPFolder(std::shared_ptr<Message> pMessage, int iDestinationFolderID)
   {
      // Check if the destination folder exists
      std::shared_ptr<IMAPFolders> pFolders = HM::IMAPFolderContainer::Instance()-**>GetFoldersForAccount(pMessage->GetAccountID());    // <-- only get account folders**
      std::shared_ptr<IMAPFolder> pFolder = pFolders->GetItemByDBIDRecursive(iDestinationFolderID);

      if (!pFolder)
         **return false;**  // <----This is what happens

      // Check which account this message belongs to.
      std::shared_ptr<const Account> pAccount = CacheContainer::Instance()->GetAccount(pMessage->GetAccountID());
      if (!pAccount)
         return false;

      std::shared_ptr<Message> pNewMessage = PersistentMessage::CopyToIMAPFolder(pAccount, pMessage, pFolder);
      if (!pNewMessage)
         return false;

      PersistentMessage::SaveObject(pNewMessage);

      pFolder->GetMessages()->Refresh(false);

      std::shared_ptr<ChangeNotification> pNotification = 
         std::shared_ptr<ChangeNotification>(new ChangeNotification(pNewMessage->GetAccountID(), pNewMessage->GetFolderID(), ChangeNotification::NotificationMessageAdded));

      Application::Instance()->GetNotificationServer()->SendNotification(pNotification);

      return true;
   }
`

**Comment by martinknafve** [comment]
This issue will be closed since there's currently no plans to fix it. hMailServer is no longer under active development so only critical bugs are fixed at this point.
