### ISSUE TITLE
5.7.B5414 update hm_messages set messageflags 

### ISSUE THREAD

**Issue by mns17** [hmailserver/hmailserver#221]
change from:
 String sql = "update hm_messages set messageflags = messageflags & ~ @FLAGS where messageaccountid = @ACCOUNTID and messagefolderid = @FOLDERID;
to:
 String sql = "update hm_messages set messageflags = messageflags & ~ @FLAGS where messageaccountid = @ACCOUNTID and messagefolderid = @FOLDERID and NOT messageflags = messageflags & ~ @FLAGS";

This patch will speed up the request

**Comment by martinknafve** [comment]
This may be a performance improvement for some database, but the syntax is not compatible with SQL Server Compact so can't include the change.
