### ISSUE TITLE
Starting with 1.1.0 there are no ms\do_*.bat files anymore.

### ISSUE THREAD

**Issue by Dravion** [hmailserver/hmailserver#223]
Hi,
The build instructions for OpenSSL higher then 1.1.0 has changed and needs to be updated.
There is no do.bat command anymore. After the perl configure its now just nmake

OpenSSL 1.1.x changed only the static LIB and DLL librarynames

Instead of: libeay32.lib ssleay32.lib (which is not avaiable anymore) its now necessary to link against
openssl.lib libssl.lib libcrypto.lib

The former DLL's libeay32.dll and ssleay32.dll are not longer avaiable also. 
Use the following new DLL's for shared deployment 
32-Bit libssl-1_1.dll AND libcrypto-1_1.dll 
64-Bit libssl-1_1-x64.dll AND libcrypto-1_1-x64.dll

**Comment by martinknafve** [comment]
hMailServer is supported with OpenSSL 1.0.2, not 1.1.0. 

From the instructions:

> Download OpenSSL 1.0.2* from http://www.openssl.org/source/ and put it into %hMailServerLibs%<OpenSSL-Version>. Replace 1.0.2* with the latest 1.0.2-version available
