### ISSUE TITLE
STARTTLS inbound failures forcing falback to unsecure connection with major mail providers

### ISSUE THREAD

**Issue by MidnightEngineers** [hmailserver/hmailserver#225]
In the hMail forum thread (STARTTLS Inbound mail syntax error) there is an error interaction in the initial STARTTLS command with some external systems. Can we resolve this by simply truncating vs comparing the SMTPConnection::ProtocolSTARTTLS_(const String &sRequest) function in SMTPConnection.cpp between lines 1783 and 1808, 
On line 1790 it is doing a boolean test to see if sRequest.GetLength() is greater than 8 (length of the word STARTTLS right) but I am not sure why this is needed?
If, as on line 226 we are using a trimmed variable with sFirstWord == _T("STARTTLS") why then not do the same here and discard any garbage trailing spaces?

**Comment by MidnightEngineers** [comment]
I think I have a code fix, but I'm having major problems with VSExpress 2017, could I get someone to compile this? Here's the replacement code for SMTPConnection.cpp starting at line 1784:
   void 
   SMTPConnection::ProtocolSTARTTLS_(const String &sRequest)
   {
      if (GetConnectionSecurity() == CSSTARTTLSOptional ||
          GetConnectionSecurity() == CSSTARTTLSRequired)
      {
         const String sStartTLSYN = "STARTTLS";
         bool hasParameters = sRequest.StartsWith(sStartTLSYN);

         if !(hasParameters)
         {
            SendErrorResponse_(501, "Syntax error");
            return;
         }

         EnqueueWrite_("220 Ready to start TLS");

         current_state_ = STARTTLS;

         EnqueueHandshake();
      }
      else
      {
         SendErrorResponse_(503, "Bad sequence of commands");
      }
   }

**Comment by martinknafve** [comment]
I'll have a look at it

**Comment by martinknafve** [comment]
I've uploaded a new temporary version here:
https://www.hmailserver.com/files/tmp/hMailServer-5.6.7-B2415.exe

Could you give it a try and see if it works for you? If it works, I'll put it up as beta.

The build below has gone through the same testing I normally do before I put up anything as beta, but would be good to have your confirmation that it solves the issue before I put it up.

**Comment by martinknafve** [comment]
Alright, the build is up as beta now.
