### ISSUE TITLE
Compaibility with Systems ?

### ISSUE THREAD

**Issue by blackcrack** [hmailserver/hmailserver#227]
Hi,

i was shortly on your Homepage,
would be nice if you are write the System compatibility by the download or something..
I was wrote in Reactosforum for make a advertising  for you are,
but it has not works on a XP compatible system like a Buddy wrote in the 
Reactos.org forum ... would be a nice addon for Reactos 
as an Mailserver by side of Http server .. pity it works not ..

best 
blacky

**Comment by martinknafve** [comment]
The system requirements are already listed in the documentation.
https://www.hmailserver.com/documentation/latest/?page=system_requirements

It's the first page under "Installation" in the documentation. I'm not sure what you mean by ReactOS. hMailServer works on XP (but of course you should not be using XP).

**Comment by blackcrack** [comment]
Hi Martin,
Microsoft Server 2003 (all editions)
Microsoft Windows XP Professional Service Pack 3

hmm.. i guess, Reactos it is at moment not on level sp3 
this is , like i guess, why it not works .. 
you can test it by self with Virtualbox : 
Headpage => Daily Builds => Download here !
http://reactos.org/getbuilds/
best regards
Blacky
