### ISSUE TITLE
XCLIENT support and features to limit its use

### ISSUE THREAD

**Issue by mologie** [hmailserver/hmailserver#228]
Hi,

I'd like to use this ticket for discussing the XCLIENT extension as per http://www.postfix.org/XCLIENT_README.html for hMailServer.

The XCLIENT command has various use cases: Testing, SMTP reverse proxies (nginx), web mail clients. In the latter two cases, XCLIENT allows hMailServer's auto-ban system to work on the IP provided through the command, instead of the real remote end's IP.

If there are no objections, I would implement and submit a pull request for the following in the next few months:

* [x] Parsing of the XCLIENT command
* [x] Using the command's data for overriding the client's hostname, IP, etc.
* [x] The option to specify whether an IP range may make use of the XCLIENT command
* [x] Integration of the above option into the .NET GUI
* [ ] Integration of the above option into the PHP GUI

Cheers,
Oliver

**Comment by mologie** [comment]
I've implemented most of the above in a branch:

https://github.com/mologie/hmailserver/tree/feature/smtp-xclient

(You don't want to merge that branch as-is, but rather cherry-pick from it, because it contains build system changes that I use on my mail server.)

![hmail-xclient](https://user-images.githubusercontent.com/597682/29244899-b9494966-7fc6-11e7-8347-d37c406e5563.png)

@martinknafve or another lead in this project: Could you please get in touch with me to discuss whether or not this could become a first-party feature as time permits? I'm available through this thread, or through the email address from my GitHub profile.

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, and this is a very old issue (which does not seem to affect many people), I will close this issue without action.
