### ISSUE TITLE
POP3D -ERR Invalid command in current state.

### ISSUE THREAD

**Issue by RvdHout** [hmailserver/hmailserver#230]
Using thunderbird to download messages through POP3 from hmailserver always returns -ERR Invalid command in current state if it received a AUTH command. Hmailserver continues POP deliveries without issues afterwards but i was wondering if it really is Invalid command?

"TCPIP"	1444	"2017-08-07 10:42:01.152"	"TCP - xxx.xxx.xxx.xxx connected to xxx.xxx.xxx.xxx:110."
"POP3D"	1444	267	"2017-08-07 10:42:01.339"	"xxx.xxx.xxx.xxx"	"SENT: +OK Welcome to mail.server.net"
**"POP3D"	3572	267	"2017-08-07 10:42:01.355"	"xxx.xxx.xxx.xxx"	"RECEIVED: AUTH "
"POP3D"	3572	267	"2017-08-07 10:42:01.355"	"xxx.xxx.xxx.xxx"	"SENT: -ERR Invalid command in current state."**
"POP3D"	7312	267	"2017-08-07 10:42:01.370"	"xxx.xxx.xxx.xxx"	"RECEIVED: USER info@domain.com"
"POP3D"	7312	267	"2017-08-07 10:42:01.370"	"xxx.xxx.xxx.xxx"	"SENT: +OK Send your password"
"POP3D"	3572	267	"2017-08-07 10:42:01.386"	"xxx.xxx.xxx.xxx"	"RECEIVED: PASS ***"
"POP3D"	3572	267	"2017-08-07 10:42:01.386"	"xxx.xxx.xxx.xxx"	"SENT: +OK Mailbox locked and ready"

**Comment by martinknafve** [comment]
hMailServer does not support the AUTH command which means it's invalid from hMailServers point of view (just like any other unsupported command would be). AUTH is an optional command, meaning that mail servers does not have to support it and mail clients can't assume that they do.
