### ISSUE TITLE
COM object, no way of finding out if an account exists

### ISSUE THREAD

**Issue by TeamKinetic** [hmailserver/hmailserver#235]
When using the COM object to add or update accounts you cannot find out if an account exists without tripping an exception.

Set obAccount = obDomain.Accounts.Add
obAccount.Address = vEmailAddress
obAccount.Password = vPassword
obAccount.Active = True

At this point if you try to save it will bomb out.

Set obAccount = obDomain.Accounts.ItemByAddress("emailAddress")

But you cannot perform any IsObject, IsNothing on the object above as it raises a subscript out of range error.

So there is no way to check an account exists without creating it, trapping the error and assuming it has errored because  the account already exist.

**Comment by RvdHout** [comment]
`Dim oApp, sAdminPassword : sAdminPassword = "VERY SECRET"

Set oApp = CreateObject("hMailServer.Application")
Call oApp.Authenticate ("Administrator", sAdminPassword)


Dim obDomain 
Set obDomain = oApp.Domains.ItemByName("%YOUR DOMAIN NAME%") 

If obDomain.Accounts.ItemByAddress("%EMAILADRESS%") Is Nothing Then
	Wscript.Echo("Not Exists")
Else
	Wscript.Echo("Exists")
end if`

**Comment by TeamKinetic** [comment]
ahh, I was trying to create it first and then checking the object status;

Set obAccount = obDomain.Accounts.ItemByAddress(emailAddress)
if obAccount Is Nothing <----gives you the subscript error.

Thanks

**Comment by TeamKinetic** [comment]
So it is a bug then as it shouldnt throw an exception if the account does not exist but provide a way of checking the account does or does not exist

**Comment by TeamKinetic** [comment]
So it is a bug then as it shouldnt throw an exception if the account does not exist but provide a way of checking the account does or does not exist

**Comment by RvdHout** [comment]
It is a bug....but you won't see that fixed anytime soon as development seems stalled...so till that time wrap On Error Resume Next around it like explained

**Comment by martinknafve** [comment]
I'm not really sure how this is a bug. It makes sense that you get an exception if the account already exists. And you're correct that there's no way to check if an account exists without having to handle an exception (unless you iterate through all the objects). But attempting to access the account and handle the exception should work fine? On Error Goto or try/catch depending on what language you're using...

**Comment by ericnewton76** [comment]
Exceptions shouldn't be used for logic conditions.  Exceptions should be reserved for exceptional situations... and checking if an account already exists is not an exceptional situation.  

The other problem with this logic is if the account doesnt exist but some other exception happens, like a transient connection failure, then the client code still tries to update a nonexistent account, causing another exception.  The client code fails and the user is left with nonsensical exceptions that most likely dont indicate the root failure of the problem.

Seems like the COM interface needs a simple (and I realize not so simple because of COM stupidities) addition to add an Account Exists method

**Comment by maxsnts** [comment]
Well, relying on Exception to check if a object exists its just bad practice.
An Exception is just that, and exception to the Rule, and error, something unexpected.
Checking the existence of a account should only trow an exception that the account existence could not be verified.

**Comment by martinknafve** [comment]
I'm closing this since there's an easy workaround to it so this has too low prio to be fixed anytime soon.
