### ISSUE TITLE
Docs and SpamAssassin

### ISSUE THREAD

**Issue by gregakaoz** [hmailserver/hmailserver#236]
FYI: Hmailserver documentation has been removed for some reason.

Also, I recently installed SpamAssassin and noticed that the process spamd.exe has to be running in order for SpamAssassin and hmailserver to establish a connection. I would like to add a feature to hmailserver that uses its primary SERVICE that calls spamd.exe as needed. 

Please consider the following:

Add a checkbox to the hmailserver GUI under Settings > Anti-spam [SpamAssassin] tab that reads:
[] Auto Launch.

If checked, the hmailserver SERVICE will see if the process handle to SpamAssassin exists (or check to see if spamAssassin is listening on the supplied port) and call CreateProcess if needed. If so, we can control the process and not give it a command line console to be shut down by another Admin.

If unchecked and save is triggered, the process should terminate if it was created under the hmailserver service.

**Comment by OutbackMatt** [comment]
hmmm
I use SpamAssassin on a separate machine.

Perhaps you could use the OnError trigger in Eventhandlers to parse the error, and if it is related to SpamAssassin not responding, then restart SpamAssassin.

I'd not be keen to see SpamAssassin 'checked' before use each time, this would add significant work to my server. Mind I'd also like for mail to be automatically delayed (greylisted) if SpamAssassin didn't respond, so that it can be checked by SpamAssassin next time - but that is a separate issue.

**Comment by OutbackMatt** [comment]
I'll also add that the documentation is alive and well (and always has been)
It can be found here >> https://www.hmailserver.com/documentation/latest/?page=overview

ALSO, every page on the admin GUI, where you press the help button, you will be directed to the correct documentation page for that Admin GUI page.

Finally, if you have an admin colleague that thinks it is OK to shutdown SpamAssassin via command line, you have bigger issues than getting more spam into your inboxes.

**Comment by gregakaoz** [comment]
* SpamAssassin uses sockets for IPC, not to establish a client/server paradigm. Also, Windows has its own routing table so you should use SpamAssassin as a LOCALHOST and put it back on your MTA server for efficiencies. 

* If a user launches (spamd.exe), the windows SHELL sends their SECURITY_ATTRIBUTES and in doing so SpamAssasign gets a handle to the User’s desktop handle (the console can then be closed by the user). If the SCM launches the process, the user will not see console window and will only be able to close the process via the task manager.  …not to mention that SCM will launch spamd wilthout a user logging on.

*When a server “listens” on a port, that port is blocked and WinSock will return an error code. It is a simple Boolean check to see if the action has failed. In your scenario using VBScirpt, the script interpreter does a just in time compilation and handles the instructions. Also, creating a process take a lot of processing power and that is why spamd remains open and uses IPC to communicate with hmailserver. 

* The documents where down for at least 2 weeks … please look at the original date of the post

* Finally: although I made no mention of using the command line to shut down SpamAssassin, just about all server packages use the command line to interact with the server’s service. For example IIS used the “iisreset /restart”. The reason I mentioned SpamAssassim should be closed is so the console goes back to the user’s desktop handle. And yes, my IT staff has the ability to shutdown server, process, etc.

**Comment by martinknafve** [comment]
From hMailServers point of view SpamAssassin is an external service same as for example SQL Server or SURBL servers. Having hMailServer auto-start various external services in case they are not running would be a weird design. hMailServer can continue to run even if SpamAssassin is down so there's no direct dependency.

You should set up SpamAssassin to run continuously and maybe add auto-restart of the SA windows service (or similar).
