### ISSUE TITLE
Copyright and legal questions

### ISSUE THREAD

**Issue by Dravion** [hmailserver/hmailserver#237]
Hi Martin,
As far as i see it, you are the Copyrightholder of the entire hMailServer project. 
Do you plan to handover all rights to something like GNU anytime soon?
Whats about the Copyright of thirdparty contributers, willing to help?

**Comment by martinknafve** [comment]
What would the benefits be with changing the copyright?

**Comment by Dravion** [comment]
I think its a commitment to the OpenSource Movement.

**Comment by martinknafve** [comment]
There's no plans to change the copyright of the project. I don't think handing it over to GNU or some other organization unless there's some commitment and wishes from those parties.
