### ISSUE TITLE
oMessage.Subject and oMessage.From return nothing on OnDeliveryFailed

### ISSUE THREAD

**Issue by jacko238** [hmailserver/hmailserver#239]
Hello
After inquiring on the forum ( https://www.hmailserver.com/forum/viewtopic.php?f=9&t=31981 ) , it seems
event OnDeliveryFailed(oMessage, sRecipient, sErrorMessage) doesn't return either oMessage.Subject nor oMessage.From though  oMessage.FromAddress works.
I use version 5.6.6-B2383
thank you.

**Comment by RvdHout** [comment]
I think this only the case when triggerred by a global rule, not? 
That makes me believe the original message that should populate the oMessage properties doesn't exist anymore, eg: already delete by the rule

With 'normal' bounces, eg: a receiving email address doesn't exist on recepient server, both oMessage.Subject and oMessage.From seem populated.

**Comment by RvdHout** [comment]
@martinknafve 
I'm a bit puzzled by this, sRecipientAddress is populated correctly and this value is also taken from pMessage, eg: https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/SMTP/SMTPDeliverer.cpp#L473-L481

This is strange as that would indicate pMessage is populated on L473 but no longer exist when FireOnDeliveryFailed is triggered on L481

**Comment by martinknafve** [comment]
The related PR has been merged.
