### ISSUE TITLE
Issue with LNK 2005

### ISSUE THREAD

**Issue by althafas** [hmailserver/hmailserver#241]
Hi , Im newbie to this project: i have done all the steps mentioned in the website. Still im facing issues like below: 

[hMailServer Errorlog.txt](https://github.com/hmailserver/hmailserver/files/1474592/hMailServer.Errorlog.txt)

Any help is always welcomed.

Regards
Althaf

**Comment by OutbackMatt** [comment]
This type of issue should be dealt with on the user forum  >> https://www.hmailserver.com/forum/

This is a configuration issue, not an issue with the program itself
