### ISSUE TITLE
Software version information

### ISSUE THREAD

**Issue by Engel1ST** [hmailserver/hmailserver#242]
Good evening,

First, thank you for this AWESOME mail server that I use since many years. I really like it and enjoy to use it daily.

I have developped one script to check which software version are installed on my server (PHP, Apache, MySQL, WinRAR, ClassicShell etc.) and  to compare them to whom that are online. My script parses all websites to detect the last build/version. If the build is different, I receive an alert by mail or SMS.

With hMailServer I have no idea how to do it. The file properties of hMailAdmin.exe give me a version 5.0.0. Those from hMailServer.exe give me 1.0.0.1. The 5.6.6 - Build 2383 version is currently installed on my system. Can you update these details in the Exe of hMailAdmin.exe or in a file that can be read ?
Thank you so much.

Alex.

**Comment by Engel1ST** [comment]
Good evening,

I did a temporary workaround like by using registry 👍 : 
` $version = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\hMailServer_is1' -Name DisplayName).DisplayName`

But if you can put the information elsewhere it will be perfect.

**Comment by OutbackMatt** [comment]
I use

./phpwebadmin/include_versioncheck.php

**Comment by martinknafve** [comment]
In 5.7, the hMailServer.exe file version will be set properly (for example to 5.7.0.2422)
