### ISSUE TITLE
Cannot receive or send emails to other email providers

### ISSUE THREAD

**Issue by kaustubh-Arnfeld** [hmailserver/hmailserver#244]
My port 25 is not block .

My DNS settings are correct and passes all the tests.

I even used Reg cure pro to fix the error 10053 .

But I am getting read operation failed ,0 bytes transferred ,end of the file,code 2

I am left clueless I am sending the screenshot (LOGS) for your kind consideration.

MY LOGS IMAGE URL: https://i.stack.imgur.com/SH2P6.png

**Comment by OutbackMatt** [comment]
I think you posted this on the user forum If not, please do so

This is a configuration issue, not an issue with the program itself
