### ISSUE TITLE
hMailserver does not deliver specific mail to recipients

### ISSUE THREAD

**Issue by CS-JS** [hmailserver/hmailserver#249]
Hi all,

we use hMailserver as  a POP2SMTP solution to fetch mails from an external POP-Server to a local Exchange Server (configured as in this tutorial - its written in german but maybe the screenshots are explaining the use-case: http://microlinc.homeip.net/index.php?lev1=22&lev2=1&id=215 ). hMailserver works fine in this scenario, fetches mails from the POP3 server and delivers them to the exchange server. 
But with some specific mails there seems to be a problem sending them to the exchange server. hMailer receives the mail from POP3, stores the mail locally and just does not send it to the Exchange server, the mail gets stuck in the users hMailserver account. Since the users are only accessing their Exchange Mailboxes, the user will never receive the mail. The mails that get stuck here have really few properties in common (some are addressed to the user directly, some are just BCC-style newsletters...), though they all seem to be related to spam of some kind. Since hMailserver is only used to "fetch-and-forward" mails, I never enabled AntiSpam or AV features on hMailserver itself, but rather have Exchange handle this.

Is there a way to trigger hMailserver to send those mails again, or to troubleshoot WHY these mails are being stored locally rather than forwarded to the Exchange server?

I have already enabled POP3 and SMTP logging in the hMailserver Settings. Since I became aware of the issue, I enabled Application and Debug logging also, but I will have to wait for the issue to happen again, to post these logs.

Here is the log of a mail that gets retrieved but not forwarded. Since hMailserver does not forward it, there are no SMTP-logs I can share:
```"POP3C" 2856    17368   "2018-02-21 08:23:02.102"       "X.X.X.X" "RECEIVED: +OK Hello there."
"POP3C" 2856    17368   "2018-02-21 08:23:02.102"       "X.X.X.X" "SENT: USER userA@POP3-Server.de"
"POP3C" 2836    17368   "2018-02-21 08:23:02.133"       "X.X.X.X" "RECEIVED: +OK Password required."
"POP3C" 2836    17368   "2018-02-21 08:23:02.133"       "X.X.X.X" "SENT: ***"
"POP3C" 2860    17368   "2018-02-21 08:23:02.149"       "X.X.X.X" "RECEIVED: +OK logged in."
"POP3C" 2860    17368   "2018-02-21 08:23:02.149"       "X.X.X.X" "SENT: UIDL"
"POP3C" 2828    17368   "2018-02-21 08:23:02.165"       "X.X.X.X" "RECEIVED: +OK[nl]1 UID12657-1122376224[nl]2 UID12658-1122376224[nl]3 UID12659-1122376224[nl]4 UID12660-1122376224[nl]5 UID12661-1122376224[nl]6 UID12662-1122376224[nl]7 UID12663-1122376224[nl]8 UID12664-1122376224[nl]9 UID12665-1122376224[nl]10 UID12666-1122376224[nl]11 UID12667-1122376224[nl]12 UID12668-1122376224[nl]13 UID12669-1122376224[nl]14 UID12670-1122376224[nl]15 UID12671-1122376224[nl]16 UID12672-1122376224[nl]17 UID12673-1122376224[nl]18 UID12674-1122376224[nl]19 UID12675-1122376224[nl]20 UID12676-1122376224[nl]21 UID12677-1122376224[nl]22 UID12678-1122376224[nl]23 UID12679-1122376224[nl]24 UID12680-1122376224[nl]25 UID12681-1122376224[nl]26 UID12682-1122376224[nl]27 UID12683-1122376224[nl]28 UID12684-1122376224[nl]29 UID12685-1122376224[nl]30 UID12686-1122376224[nl]31 UID12687-1122376224[nl]32 UID12688-1122376224[nl]33 UID12689-1122376224[nl]34 UID12690-1122376224[nl]35 UID12691-1122376224[nl]36 UID12692-1122376224[nl]37 UID12693-1122376224[nl]38 UID12694-1122376224[nl]39 UID12695-1122376224[nl]40 UID12696-1122376224[nl]41 UID12697-1122376224[nl]42 UID12698-1122376224[nl]43 UID12699-1122376224[nl]44 UID12700-1122376224[nl]45 UID12701-1122376224[nl]46 UID12702-1122376224[nl]47 UID12703-1122376224[nl]."
"POP3C" 2828    17368   "2018-02-21 08:23:02.165"       "X.X.X.X" "SENT: RETR 47"
"POP3C" 2828    17368   "2018-02-21 08:23:02.180"       "X.X.X.X" "RECEIVED: +OK 15490 octets follow."
"POP3C" 2620    17368   "2018-02-21 08:23:02.196"       "X.X.X.X" "SENT: QUIT"
"POP3C" 2860    17368   "2018-02-21 08:23:02.211"       "X.X.X.X" "RECEIVED: +OK Bye-bye."
```

**Comment by CS-JS** [comment]
Hi Martin, thanks for the reply!

I would expect the mails to be delivered to "userA@POP3-server.de" which is the account name and emailadress of the user in question.

That was my guess to, but I tested hMailServers behaviour and sent an email to the user from my office account, "to" my personal/private mail, "cc" to one of my coworkers, and "bcc" to our customer. All 3 recipients (including the exchange-server behind hMailserver-Pop2SMTP) received the mail, so I don't think this is a general problem in hMailServer, but rather must have something to do with these specific mails. Generally hMailServer delivers those mails to BCC Recipients fine.

Thanks for any hints!

**Comment by martinknafve** [comment]
To be able to troubleshoot the issue we would need to know what is the contents of the email on the POP3 server. It's not really possible to say why the email isn't delivered without that info. It may be related to the issue described here:

https://github.com/hmailserver/hmailserver/pull/428
