### ISSUE TITLE
Actionvalues not written to DB when creating a new rule 

### ISSUE THREAD

**Issue by AndisGrossteins** [hmailserver/hmailserver#257]
There seems to be a glitch when a new rule is saved first time. The `actionvalue` field in `hm_rule_actions` table stays empty even is the action value was provided in in the UI.
I'm able to reproduce this issue with hMailServer 5.6.7-B2425 in two environments:

1. Windows 10 x64 (Version 10.0.17134.48)
Database: MariaDB 10.2.11

2. Windows Server 2003 (Version 10.0.17134.48)
Database: MySQL 5.6.14

**Steps to reproduce:**

1. Add a global rule
1. Add rule criteria
1. Add action "Set header value" with any header and any string as value
1. Click OK in action windows (here the data should be saved) and OK in rule window
1. Go to test the new rule and it doesn't work
1. Check `hm_rule_actions` and see that the `actionvalue` is empty

As a side effect, the action is skipped if `actionvalue` is empty. That would defy any attempts to use this action to remove headers. Not a problem for me but might be useful to have an action that can unset/delete a header.

**Comment by AndisGrossteins** [comment]
Also reproducible in hMailServer 5.6.8-B2431.

**Comment by martinknafve** [comment]
This will be fixed in the next build.
