### ISSUE TITLE
OutOfMemoryHandler - hMailServer has run out of memory, clearing caches.

### ISSUE THREAD

**Issue by DeeJayPee** [hmailserver/hmailserver#258]
Hello,

I use hmailserver since like 10y+, and since few days, on one of the hms instance with a new domain and imapcopy all of the account, I've lot of strange errors.

Here are the last, but I've got many of them. 

> "ERROR" 5144    "2018-06-19 10:27:58.487"       "Severity: 2 (High), Code: HM4208, Source: File::ReadFile(), Description: An error occured when reading file., Message: bad allocation"
> "ERROR" 5144    "2018-06-19 10:27:58.863"       "Severity: 3 (Medium), Code: HM4227, Source: File::ReadFile, Description: An unknown error occurred while reading file from disk."
> "ERROR" 5144    "2018-06-19 10:27:59.284"       "Severity: 3 (Medium), Code: HM5042, Source: File::ReadTextFile, Description: An unknown error occurred while reading a text file from disk."
> "ERROR" 5144    "2018-06-19 10:27:59.456"       "Severity: 1 (Critical), Code: HM5062, Source: IMAPFetch::ReportCriticalError_, Description: ERROR HM10001 - IMAP FETCH: Error when loading MIME message. - \\\\192.168.4.131\MAILS\xxxx.yyy\zzzz\D2\\{D20FD1B3-8DA6-42BC-97AC-91F36FE3A56A}.eml"
> "ERROR" 5144    "2018-06-19 10:28:00.253"       "Severity: 3 (Medium), Code: HM5136, Source: TCPConnection::AsyncReadCompleted, Description: An error occured while parsing data. Data length: 94, Data: evxl UID FETCH 1:2,5:64,66:67,271:274,277:279 (UID FLAGS RFC822.SIZE BODY.PEEK[] INTERNALDATE). Remote IP: "
> "ERROR" 5144    "2018-06-19 10:28:01.050"       "Severity: 2 (High), Code: HM4208, Source: ExceptionHandler::Run, Description: An error occured while executing 'IOCPQueueWorkerTask', Message: bad allocation"
> ...
> "ERROR" 1140    "2018-06-19 10:27:49.331"       "Severity: 2 (High), Code: HM4208, Source: File::ReadFile(), Description: An error occured when reading file., Message: bad allocation"
> "ERROR" 1140    "2018-06-19 10:27:49.347"       "Severity: 3 (Medium), Code: HM4227, Source: File::ReadFile, Description: An unknown error occurred while reading file from disk."
> "ERROR" 1140    "2018-06-19 10:27:49.347"       "Severity: 3 (Medium), Code: HM5042, Source: File::ReadTextFile, Description: An unknown error occurred while reading a text file from disk."
> "ERROR" 1140    "2018-06-19 10:27:49.362"       "Severity: 1 (Critical), Code: HM5062, Source: IMAPFetch::ReportCriticalError_, Description: ERROR HM10001 - IMAP FETCH: Error when loading MIME message. - \\\\192.168.4.131\MAILS\xxxx.yyy\zzzz\D2\\{D20FD1B3-8DA6-42BC-97AC-91F36FE3A56A}.eml"
> "ERROR" 1140    "2018-06-19 10:27:49.378"       "Severity: 3 (Medium), Code: HM5136, Source: TCPConnection::AsyncReadCompleted, Description: An error occured while parsing data. Data length: 94, Data: 695b UID FETCH 1:2,5:64,66:67,271:274,277:279 (UID FLAGS RFC822.SIZE BODY.PEEK[] INTERNALDATE). Remote IP: "
> "ERROR" 1140    "2018-06-19 10:27:49.394"       "Severity: 2 (High), Code: HM4208, Source: ExceptionHandler::Run, Description: An error occured while executing 'IOCPQueueWorkerTask', Message: bad allocation"
> 

Allong with thoses errors, I've got a bunch of memory error : 
> "APPLICATION"   5068    "2018-06-19 10:37:01.862"       "OutOfMemoryHandler - hMailServer has run out of memory, clearing caches."
> "APPLICATION"   5068    "2018-06-19 10:37:01.878"       "OutOfMemoryHandler - hMailServer has run out of memory, clearing caches."
> "APPLICATION"   5068    "2018-06-19 10:37:01.894"       "OutOfMemoryHandler - hMailServer has run out of memory, clearing caches."
> "APPLICATION"   5068    "2018-06-19 10:37:01.987"       "OutOfMemoryHandler - hMailServer has run out of memory, clearing caches."
> "APPLICATION"   5068    "2018-06-19 10:37:02.003"       "OutOfMemoryHandler - hMailServer has run out of memory, clearing caches."

Eventually, the server crash (i've minidump) or message stay in the queue for a long time before being delivered. Every 

I know people use Outlook with IMAP.

Any idea on why ?

Thanks !

**Comment by martinknafve** [comment]
Yes, my recommendation to people having this issue will be to use 5.7. 5.7 has a completely rewritten model for handling memory to be more restrictive and not just "cache everything".

**Comment by mtraeumner** [comment]
Hi @martinknafve,
I've the same problem written here, but now in 2020 I didn't find any download link for version 5.7 or newer. The newest one at hmailserver(dot)com is 5.6.7. Isn't it available anymore?
Thanks in advance
Michael

**Comment by helptiger** [comment]
https://build.hmailserver.com/viewType.html?buildTypeId=HMailServer_BuildHMailServer57
Login as Guest

**Comment by mtraeumner** [comment]
Thank you very much

**Comment by mstenz** [comment]
I tried to install this latest version on my machine as well but get "This program does not support the version of Windows your computer is running". I am using Windows Server 2008 64Bit. Is this not supported anymore by 5.7.x?

**Comment by helptiger** [comment]
The latest build of 5.7 needs Server 2008R2 or newer.

btw Windows Server 2008 has already reached EOL. 
https://support.microsoft.com/en-us/help/4456235/end-of-support-for-windows-server-2008-and-windows-server-2008-r2

**Comment by Dravion** [comment]
You can reach out to my User build of hMailServer (64-Bit only, has a Installer).
https://github.com/Dravion/hmailserver/releases/download/2495/hMailServer-5.7.0-B2495-x64.exe

**Comment by helptiger** [comment]
> You can reach out to my User build of hMailServer (64-Bit only, has a Installer).
> https://github.com/Dravion/hmailserver/releases/download/2495/hMailServer-5.7.0-B2495-x64.exe
version will also not install, look
https://github.com/Dravion/hmailserver/commit/3a284278cf0664f5083c19516e1bb7916b1d3c34

**Comment by Dravion** [comment]
Ok, i released another build, which should work for you
https://github.com/Dravion/hmailserver/releases/tag/5.7.0-B2496

**Comment by mstenz** [comment]
@Dravion Thank you. I successfully installed that version. :)

**Comment by mstenz** [comment]
> btw Windows Server 2008 has already reached EOL.
> https://support.microsoft.com/en-us/help/4456235/end-of-support-for-windows-server-2008-and-windows-server-2008-r2

Yes, i know but was not able to replace it yet.

**Comment by zorgoban** [comment]
I had to update to 5.6.7 a few days ago because Admin had Problems with Windows Authentication during the connection to Sql Server on Windows Server 2019. Since then I also get those error messages. Never had this problem before. A 64 bit build would be very appreciated. But it's still funny that this problem arises now. Maybe some bug in the new version?

**Comment by mstenz** [comment]
> had Problems with Windows Authentication during the connection to Sql Server on Windows Server 2019.
Not sure if WIndows AUthentication is even used/supported? I have configured the user that hm is using to access the database. I think this issue is completely different to this one. Maybe opening a new issue or asking/checking in forum would be good.

**Comment by zorgoban** [comment]
Sorry, but this was not the main point of my message. More like a preamble. The out of memory error has nothing to do with Authentication. I know that.

**Comment by mpfrench** [comment]
I'm getting a lot of "out of memory" crashes on hMailServer-5.6.9-B2607.  This thread indicates that this problem was solved in version 5.7 but I cannot find it.  Can someone point me the right direction?

**Comment by SorenRR** [comment]
I'm assuming here...

https://d-fault.nl/files/hMailServer-Builds

**Comment by mpfrench** [comment]
Thank you Soren for the link.  The readme in B2643.17 does indeed claim to fix the out-of-memory crashes due to Apple mail clients.  However, I need someone to point me in the right direction using the SQL script to update the database to 5705.

These Apple-caused crashes are causing many many hMailserver crashes every day.

I installed hMailServer-5.7.0-B2643-x64 which brings the database to 5704, but I have not figured out how to use the script to update it to 5705.  Would someone point me in the correct direction?

**Comment by RvdHout** [comment]
What database type?
Did you try the included readme.txt?

mariadb/mysql
```
insert into hm_settings (settingname, settingstring, settinginteger) 
  select 'TlsOptions', '', 0 from dual
where not exists 
  (select settingname from hm_settings where settingname='TlsOptions');

update hm_dbversion set value = 5705;
```

For other database types you can get examples/instructions from here, but for 5.7 you only need the TlsOptions settings:
https://www.hmailserver.com/forum/viewtopic.php?p=253068#p253068

**Comment by pqvu78** [comment]
Could you please let me know if there is a newer 64-bit installer available for hMailServer?
