### ISSUE TITLE
nano server is doable?

### ISSUE THREAD

**Issue by imacks** [hmailserver/hmailserver#259]
Would it be possible to run hms on nano server? I believe all the requirements are there, and we could just strip out the gui parts to interface everything via powershell remoting.

**Comment by martinknafve** [comment]
This is not something which will be implemented in an official way. The user interface is a vital part of hMailServer. As you say, it may be possible to strip out the UI and get it up and running. There may be other roadblocks as well, such as the usage of DCOM which I don't know if Nano supports.
