### ISSUE TITLE
Libmysql.dll Innosetup Helperfunction for hMailServer

### ISSUE THREAD

**Issue by Dravion** [hmailserver/hmailserver#261]
On the Forum support section, some peoples seems to be having trouble to find and install the correct libmysql.dll file, so i checked if this step could be automated.

And thats the result so far (Screenshot)
https://www.hmailserver.com/forum/viewtopic.php?f=10&t=31562&p=202436&hilit=libmysql#p202436

1) It downloads the Oracle/MySQL Connector*.zip file to %appdata%\GUID\ non admin folder
2) It uses the internal Windows WinAPI builtin unzipper (COM Object) and unzip the downloaded archive
3) It locates the libmysql.dll inside the unzipped folder %appdata%\GUID\<unzipped>
4) It copys the libmysql.dll file to %program files (x86)%\hMailServer\bin\libmysql.dll position
5) It uses only Win32 and COM  (no .NET, no MFC, no Resourcefiles, just pure C/C++ code)
6) Solution/Project can be added and compiled without special settings/reconfiguration

How ever, i lost  patients and didnt work on it for a while but if you think its a good additional feature for the hMailServer Innotsetup Installer i will work on it again.

**Comment by martinknafve** [comment]
The reason libmysql.dll is not included is due to the fact that hMailServer was closed source some years ago. Since hMailServer is open source now, we could just bundle with the installer it instead so that you get the DLL installed by the installer.

The only downside I see is that it would slightly increase the size of the installation package (with about 600-1000kb depending on how good the InnoSetup compression is). Do you see any other issues?

So my suggestion is we close this item and just create a new issue to bundle it intead. Agree?

**Comment by Dravion** [comment]
Yeah, i agree.

**Comment by blackcrack** [comment]
would cool if it is WinServer2003 compatible => Reactos

**Comment by Dravion** [comment]
> would cool if it is WinServer2003 compatible => Reactos
> (in Rapps is VS2007 too :) )

Is ReactOS allready 64-Bit ready? 
We can target Windows XP SP3 32-Bit,  Windows XP SP2 64-Bit, Windows Server 2003 32-Bit and 
Windows Server 2003 64-Bit with our current Compiler Visual Studio 2013 C/C++ and even with
Visual Studio 2017 C/C++ XP-SP3 Targeting if it comes to the binary compatibility, but ReactOS and evem WINE doesnt support our DCOM OutOfProcess 32/64-Server and it seems the never will.
Thats the Problem why we cannot simply run hMailServer.exe on a WINE ready or ReactOS Operatingsystem right now. Right now i work on a rewrite to make hMailServer compile
on VS 2017 C/C++ (not a easy task).  If you interrested in our Roadmap and Developertalk, visit our Community Forum and get involved https://www.hmailserver.com/forum/viewforum.php?f=17

**Comment by Dravion** [comment]
Unfortently we have a shortage regarding exprts to, thats seens to be a common Problelm in OSS Projects. I like the hMailServer Community because they are verry tollerabt and since iam on the Forum, nobody was banned, exceptionally if someone is trying to sale Viagra Pills and crap like this.

Regarding Visual Studio 2017. Its true it doesnt run on ReactOS but on Win10 for example you can
do a compatible build doewn to XP SP3 (32-Bit) and SP XP2 (64-Bit). So, we can use it for now to target 
ReactOS as 32-Bit Platform as well (i need to to da a 32-Bit MSI Installer first). 

But the DCOM OutOfProcess Problem reamins. As far as i found out, the DCOM Support in ReatOS
(and even WINE) doesnt goes verry deep. It only supports so called InProc COM Servers, but our
hMailServer.exe implements a OutOfProcess COM-Server Object. hMailServer.exe will and can run
as Process on ReactOS and WINE but cannot it cant bind ports or its controllable from the AdminGUI
or PHPWebAdminInterface.  I think we need to port a stripped down hMailServer Deamon to
POSIX in general so it can be build with Make and GCC, so we have a foot in the Door to Linux and
ReactOS same time.

**Comment by blackcrack** [comment]
I think in the future everything will be merged and sooner or later everything will work, because it needs it and then it will be developed as well .. so it can work and should work .. but until then you just have to work on it .. me I'm curious how long it will take :) :+1: 
best regards
Blacky

**Comment by Dravion** [comment]
Hmm, its hard to point out. But hMailServers code itself isnt that big and besides COM Stuff in it, its pretty much portable. But the first Alpha will be demo that its possible (witout GUI) just make the hMailServer Deamon run and accepting connections.
