### ISSUE TITLE
Do not send security Headers in PHP

### ISSUE THREAD

**Issue by AyrA** [hmailserver/hmailserver#264]
You are currently sending these security headers in PHP:

- X-Content-Type-Options
- X-Frame-Options
- Content-Security-Policy
- X-XSS-Protection

Please do not do that. If you want to send these, do so via `.htaccess` or `web.config`.

The problem here is that HTTP headers "stack". My webserver globally sends these already which means the browser receives them twice.

Browsers concatenate headers with `,` which for example results in `X-XSS-Protection: 1; mode=block,1; mode=block`. This is an invalid value which browsers will ignore. This means that the fact that your script sends these headers in a preconfigured environment makes it unsafer than without.

I added a `web.config` file. Just put into the root of the web admin folder. Github doesn't supoorts the file extension so I added `.txt` which you have to remove again.

[web.config.txt](https://github.com/hmailserver/hmailserver/files/2274636/web.config.txt)

For `.htaccess` it is this:

	Header set X-Content-Type-Options "nosniff"
	Header set X-Frame-Options "DENY"
	Header set X-XSS-Protection "1; mode=block"
	Header set Content-Security-Policy "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline';"

**Comment by caugner** [comment]
@AyrA You seem to be using Apache HTTP Server.

Please try and use `Header setifempty` or `Header merge` instead of `Header set` (see [mod_headers docs](https://httpd.apache.org/docs/current/mod/mod_headers.html#header)).

**Comment by martinknafve** [comment]
I won't merge this. The scripts specifies what headers to use which is fine with me. If you're using some web server configuration which tweaks the headers and make them invalid, then you should fix that server config.
