### ISSUE TITLE
SMTP multiply max message size with 1024

### ISSUE THREAD

**Issue by Virinum** [hmailserver/hmailserver#267]
I've set the max message size to 102400 KB (100 MB). Via telnet I receive `250-SIZE 102400000`. But 102400000 Bytes are 97.65625 MB. So if I want exactly 100 MB, I've to set the value to 104857.6 (but points aren't allow).

E.g. Gmail returns `250-SIZE 157286400` (150 MB). It's not possible for me to set that value, too.

So here my suggestion: Multiply the max message value with 1024 (not 1000).

**Comment by RvdHout** [comment]
SMTPConection.cpp

**old**
`      // Append size keyword
      {
         String sSizeKeyword;
         int iMaxSize = smtpconf_->GetMaxMessageSize() * 1000;
         if (iMaxSize > 0)
            sSizeKeyword.Format(_T("\r\n250-SIZE %d"), iMaxSize);
         else
            sSizeKeyword.Format(_T("\r\n250-SIZE"));
         sData += sSizeKeyword;
      }`

**new**
`      // Append size keyword
      {
         String sSizeKeyword;
         int iMaxSize = smtpconf_->GetMaxMessageSize() * 1024;
         if (iMaxSize > 0)
            sSizeKeyword.Format(_T("\r\n250-SIZE %d"), iMaxSize);
         else
            sSizeKeyword.Format(_T("\r\n250-SIZE"));
         sData += sSizeKeyword;
      }`

**Comment by martinknafve** [comment]
Included in 5.7.
