### ISSUE TITLE
Successfull replacement of OpenSSL 1.0.2.x with LibreSSL 2.8.1

### ISSUE THREAD

**Issue by Dravion** [hmailserver/hmailserver#269]
Unfortently the new mainbranch of OpenSSL 1.1.x breaks internal API calls in many ways. Its not possible to simply port it to the new branch. 

BUT: I tested LibreSSL 2.8.1 x64 as replacement for my x64 Version of hMailServer and it works
like a charm. Build was successfully and i was able to create an new Innoinstaller which is slightly bigger
because i replaced OpenSSL's ssleay32.dll and libeay32.dll with libssl-1_1-x64.dll and libcrypto-1_1-x64.dll. Static link importlibs are now ssl.lib and crypto.lib

Download page https://github.com/Dravion/hmailserver/releases

Installer with LibreSSL is: hMailServer-5.6.8-B2431-LibreSSL-x64.exe 6.62 MB

**Comment by blackcrack** [comment]
very nice , this make's more save ! :)

**Comment by martinknafve** [comment]
For now hMailServer will continue to use OpenSSL. This doesn't mean I think Libre is a bad option (quite the opposite), but it's nothing which will be included in the nearest future, mainly due to time constraints. So I'm closing this for now.
