### ISSUE TITLE
StdString.h prevents compiling in VS2017

### ISSUE THREAD

**Issue by Dravion** [hmailserver/hmailserver#270]
I came across this file while iam trying to port the 2013 Codebase of hMailServer to VS2017.
This seems to be the only Showstopper so far. Do we need this anymore? There is no updated version
of it, but it seems to be referenced quite often.

**Comment by martinknafve** [comment]
StdString is used heavily in hMailServer. hMailServer can currently not be built using VS2017. I'll look into this issue when I upgrade support of dev environment.
