### ISSUE TITLE
How to set separate helo for each external ip/domain for outgoing mail.

### ISSUE THREAD

**Issue by BorizzK** [hmailserver/hmailserver#274]
Need separate helo for each external ip/domain for outgoing mail.

**Comment by Virinum** [comment]
It's currently not possible.
Please see https://www.hmailserver.com/forum/viewtopic.php?f=7&t=33334#p208334

**Comment by OutbackMatt** [comment]
why do you 'NEED' this??
Gmail doesn't, neither does Office365?

**Comment by martinknafve** [comment]
Closing, since this is more of a support question/feature request and it's not clear why it's needed in the first place.
