### ISSUE TITLE
mail header without any "received from"

### ISSUE THREAD

**Issue by andipfaff** [hmailserver/hmailserver#280]
I received several Emails without any "received from" header info. All the Emails have been sent to a secondary Email address (Alias) so I think that there's a bug related to these type of addresses.
[header1.txt](https://github.com/hmailserver/hmailserver/files/2923180/header1.txt)
[header2.txt](https://github.com/hmailserver/hmailserver/files/2923181/header2.txt)
[header3.txt](https://github.com/hmailserver/hmailserver/files/2923182/header3.txt)
[SMTP_log1.txt](https://github.com/hmailserver/hmailserver/files/2923183/SMTP_log1.txt)
[SMTP_log2.txt](https://github.com/hmailserver/hmailserver/files/2923184/SMTP_log2.txt)
[SMTP_log3.txt](https://github.com/hmailserver/hmailserver/files/2923185/SMTP_log3.txt)

**Comment by jimimaseye** [comment]
You should discuss this in the forum and let it be discussed and investigated by the other expert users first. You will  get a quicker conclusion.
