### ISSUE TITLE
HTTP Callbacks

### ISSUE THREAD

**Issue by cblaze22** [hmailserver/hmailserver#282]
One thing many of these email services have now is callback on certain status codes or ways to parse emails.  

One use case is users want to unsubscribe using STOP, it would be nice to use a regex when that email comes in on the body and call an endpoint to send that email and its details to so we can unsubscribe them.

Another use case is if the email fails because its invalid or doesnt exist.  There should be a way to send that email to a HTTP endpoint so we can correctly remove them from a list so we dont keep sending stuff to that email.

Also I know this is open source, but is there anyway to start paying you guys to add features. I think that would give some incentive to add some missing features.

**Comment by martinknafve** [comment]
Closing since this won't be implemented soon. I agree webhooks would be nice, but due to being low prio this won't be implemented anytime soon.
