### ISSUE TITLE
hmailserver.message not heeding AUTH

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#283]
I just did this in VBS on my server

```
dim hm
Set hm = CreateObject("hMailServer.Message")
hm.From = "President"
hm.FromAddress = "president@whitehouse.com"
hm.Body = "Test sending" & vbCrLf 
hm.subject = "Test Subject"
Call hm.AddRecipient ("MattG", "mygmailaddress@gmail.com")
hm.Save
```

And it sent.

There were no SMPTD lines in my logs, and I have external to external requiring AUTH
We think this is a significant vulnerability for those who run true IPv6 on their hMailserver (as opposed to tunnelled IPv6 via IPv4)

Thread here >>http://www.hmailserver.com/forum/viewtopic.php?f=10&t=33795&p=211093#p211093

**Comment by martinknafve** [comment]
"SMTPD" log entries are logged when an email is received over SMTP by hMailServer. (It's short for "SMTP Daemon". If you use the API to construct a message, then that message is added to the delivery queue directly. In other words, messages created using the API like this are not delivered to hMailServer using SMTP, they are added directly to the database.

So to take advantage of this, the attacker would need to have access to machine already, you would to have opened up for remote scripting and you would have disabled the firewall. Or am I missing something?

I agree that it should be logged, but I'm not sure it should require AUTH.

**Comment by OutbackMatt** [comment]
Read the thread linked please.
I don't believe that this is an issue, I was retelling another forum user's idea.

Because DCOM doesn't work over NAT I believe that this is not possible on IPv4 at all (as all internet connections using IPv4 use NAT in some form), but this MAY be an issue for IPv6 users.

Logging this is an important first step - that would allow us to monitor these messages sent via API

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, and this is a very old issue (which does not seem to affect many people), I will close this issue without action. I realize that you may still want this fixed, but I don't want to give the false impression that this is something being worked on.
