### ISSUE TITLE
Trigger an event on email sent

### ISSUE THREAD

**Issue by nareshkathi** [hmailserver/hmailserver#284]
I am not sure if its a correct forum or not to ask this question.

I am trying to trigger an event when an email is sent from an account. Not sure which method to use in EventHandlers.vb. Please let me know how to trigger/fire an event as soon as an email is sent from an account.

Thanks.

**Comment by martinknafve** [comment]
This question should be brought up in the hMailServer forum instead. The GitHub tracker is for bug reports.
