### ISSUE TITLE
Support for international email adresses (UTF-8)

### ISSUE THREAD

**Issue by minoser** [hmailserver/hmailserver#286]
I would like to have support for unicode characters in email addresses (account name/local part).
like this guy did: https://medium.com/@zackbloom/i-have-a-unicode-email-address-fbecd630ec12

The corresponding rfc:
https://tools.ietf.org/html/rfc6531

**Comment by martinknafve** [comment]
This won't be included any time soon due to lack of time. It looks like a nice to have, but the support for this seems to be quite low.
