### ISSUE TITLE
Ip Range Allow deliveries/Require SMTP authentication Bug

### ISSUE THREAD

**Issue by RvdHout** [hmailserver/hmailserver#287]
Have been fiddling around with the IP ranges, when I disallow Deliveries from External to External for a IP Range but do not uncheck External to External in Require SMTP authentication the error message displayed is:
"530 SMTP authentication is required."

Only if I also uncheck External to External in Require SMTP authentication the error message is correct. eg:
"550 Delivery is not allowed to this address."

This seems incorrect to me...Don't you think?
I think settings in Allow deliveries must always be the preferred and appointed criteria above settings in Require SMTP authentication, in Administrator GUI this looks to be the case as the Require SMTP authentication checkbox is greyed-out/readonly as soon you uncheck Allow deliveries, but in the code it seems to function visa versa

https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/SMTP/SMTPConnection.cpp#L681

**Comment by mstenz** [comment]
I have experienced same issue also after first configuration of the server, it was quite confusing.

**Comment by RvdHout** [comment]
I think simply flipping over the order of execution fixes this...weird i never noticed this before

**Comment by RvdHout** [comment]
https://www.hmailserver.com/forum/viewtopic.php?f=8&p=213151#p213151

**Comment by martinknafve** [comment]
@RvdHout I fixed this before I noticed your pull request. I'll compare our fixes and see if they are the same.

**Comment by martinknafve** [comment]
Merged
