### ISSUE TITLE
it seems this repo is dead, which fork to follow?

### ISSUE THREAD

**Issue by mstenz** [hmailserver/hmailserver#288]
Since some month now there is no real update, the forum is mostly dead as well and no fixes to issues provided anymore. 
For example my issue with draft messages not get saved is also not solved and a critical problem. 
Have someone successfully forked + continue the development on this peace of software seriously?
Please let me know the places i can get newer versions. 
Thank you.

**Comment by martinknafve** [comment]
This sounds like a discussion you should take in the forum and not submit as a bug. 

Dravion is working on a fork.  There may be others.

**Comment by mstenz** [comment]
Thx, unfortunately registration on forum and also reset password function does not work so I don't have a chance to use the forum. :(
I tried to contat Dravion but it was impossible because also his native emailaddress he use for github doesnt work anymore (at least 2 days ago). 
@Dravion: If you can contact me via email (mstenz-design@web.de) would be really great. thx

**Comment by martinknafve** [comment]
I just tried registering to the forum and it worked fine for me. Are you saying that the email message with activation link isn't sent to you? If so, please try to use the reset password feature and I'll check the logs to see why email delivery fail.

**Comment by mstenz** [comment]
just tried to reset the password right now

**Comment by martinknafve** [comment]
It was classified as spam by web.de. Can you try to use password reset again? I've tweaked some config on my end.

**Comment by mstenz** [comment]
i am in now. thx
