### ISSUE TITLE
Remove x86 support from 5.7

### ISSUE THREAD

**Issue by martinknafve** [hmailserver/hmailserver#290]
In 5.7, support for x86 will be removed. Only x64 will be supported.

**Comment by Dravion** [comment]
Hi,
That's good news. I think if hMailServer now has its own  x64 Releases there is no need to maintain LTS x64 anymore.

**Comment by martinknafve** [comment]
The support for x86 has been removed.

**Comment by blackcrack** [comment]
@martinknafve 

bad step, if i looking on Reactos .. :\

the _64 is only a extension, x86 runs on x86_64 too ...
if you remove the support for <x86 only make you really a bad step ..

best regards
Blacky

**Comment by martinknafve** [comment]
hMailServer runs on Windows. There's no support for running it on React OS.

ReactOS is a very impressive project, but they can't expect all software to remain in the Windows XP era just to be compatible with it.

**Comment by blackcrack** [comment]
it will be updated, up to 7 or further, but now it's the first target WinNT Server 2003 and there should be software where runs on it.. well, if you remove the support .. less pretty well software where supports Reactos .. it's pity .. youre software could be, if's support still WinNT2003Server, the next in Reactos/Virtualbox which tested out.. to be able to run.. or you.. if you want, could maybe a helping hand in reactos .. to have later a real open source WinNT for less out of the community without pay over 100 Dollar for a Licence and able to use .. and less spy and so on.. (so a real reaction against MS (politic) ) a Reactos out of the Internet Community .. did you see in the last times the Webpages.. and the more Modern Reactos pages ? and the Buildbot on the headpage => "Daily Builds"
https://reactos.org/getbuilds/ iso's in 7zip's , klick the right or left arrows to found a iso.7z for testing in a VM like VBox.. i bet you be surprised how well it today works ... in VBox ...
well, it's you're decision if you support also a bit Reactos or not.. many factorys working with WinXP already  in different mashins, if Reactos finish, can this mashins also work in the next century / 10 years further ..  but you must just hold on until then .. to be it usable on real hardware.. ind this is not really long, it works like a Chinese riceboard 2,4,8, and so on .. more better it runs more it convinces
the peoples .. and i tell you, reactos will come.. over short or long.. and therefore need we a mailserver for Winnt .. this be only the word, what i can give you in you're hands ..

best regards
Blacky
