### ISSUE TITLE
Remove support for XP, Vista and Server 2003

### ISSUE THREAD

**Issue by martinknafve** [hmailserver/hmailserver#291]
The support for these Windows-versions should be removed since Microsoft is no longer supporting them and hMailServer isn't being tested on them.

**Comment by blackcrack** [comment]
but reactos comes ... like i told on a other tread .. it's a bad step ..

**Comment by martinknafve** [comment]
@blackcrack, see reply here:
https://github.com/hmailserver/hmailserver/issues/290
