### ISSUE TITLE
Bundle libmysql.dll with installation to make installation smoother

### ISSUE THREAD

**Issue by martinknafve** [hmailserver/hmailserver#295]
With hMailServer 5.7, any user of MySQL will need to add place a new libmysql.dll in the bin folder, since hMailServer is now 64-bit. This will likely cause issues for a lot of users.

To remove this friction, the installer should just bundle the libmysql.dll-file. The reason it was removed years ago was because hMailServer was closed source and couldn't bundle it due to licensing, which is no longer an issue.

**Comment by martinknafve** [comment]
With hMailServer 5.7, any user of MySQL will need to add place a new libmysql.dll in the bin folder, since hMailServer is now 64-bit. This will likely cause issues for a lot of users.

To remove this friction, the installer should just bundle the libmysql.dll-file. The reason it was removed years ago was because hMailServer was closed source and couldn't bundle it due to licensing, which is no longer an issue.

**Comment by helptiger** [comment]
Nice, so hMailServer works with MariaDB out of the box!

**Comment by OutbackMatt** [comment]
I had to upgrade my MySQL to a newer version, and then manually track down the related version of the libmysql.dll, and then I had to run the DBUpdater.exe

hMailserver prompted me correctly through the process but including the dll is a great idea.

Is there only one version of the dll?
MySQL made it seem that there are many...


@helptiger
Is MariaDB 64 bit?

**Comment by Dravion** [comment]
> Nice, so hMailServer works with MariaDB out of the box!

AS long as you stay with MySQL Connector/C version 5.7.x series you can run hMailServer 5.x with MySQL. There is a MariaDB Install Guide in the hMailServer forum https://www.hmailserver.com/forum/viewtopic.php?f=21&t=32869

PS: MariaDB is not officially supported and tested, but it should work.

**Comment by jimimaseye** [comment]
@martinknafve Some concerns from dravion about what dll's work and what doesn't.  Do these concerns apply?: https://www.hmailserver.com/forum/viewtopic.php?t=33531

**Comment by Dravion** [comment]
Yeah, this can be a Problem.
While PostgreSQL made it very easy to compile hMailServer with latest PostgreSQL Support, simply by adding (for example: C:\Program Files\PostgreSQL\10\include\libpq-fe.h and its lib
C:\Program Files\PostgreSQL\10\lib\libpq.lib) from retail PostgreSQL, it's on the other hand not that easy to update to latest MySQL 8+ Include Headers and binary libs. I believe it has something todo,
that Martin made a custom modification to older MySQL Headers and added it to hMailServer, which unfortunately is not upstream compatible with MySQL 8.x I think its necessary to redo Martins modifications to MySQL 8.x all over again to make it work natively with MySQL 8,x.

**Comment by Dravion** [comment]
They are try to hide the required libmysql.dll version more and more.
This ZIP-Archive contains the correct libmysql.dll x64 version (5.7.29).
https://downloads.mysql.com/archives/get/p/23/file/mysql-5.7.29-winx64.zip

**Comment by RvdHout** [comment]
libmysql.dll x64 version (5.7.30) https://dev.mysql.com/downloads/file/?id=494047

**Comment by Dravion** [comment]
As far as i understand it, it is compatible to older versions but it can only connect to MySQL 8.x
if it's configured in Legacy Mode so it can accept libmysql.dll Connection from the  5.7.x line.
MySQL 8.x libmysql.dll on the other hand can connect to lower MySQL 5.x versions but this would
require to update hMailServers MySQL C/C++ Headers to match version 8.0 Headers for libmysql.dll.

**Comment by RvdHout** [comment]
```
Starting task...
Please wait while creating database...
Error:
The MySQL client (libmysql.dll, x64) could not be loaded.
hMailServer needs this file to be able to connect to MySQL.
The MySQL client needs to be manually copied to the hMailServer Bin directory. The file is not included in the hMailServer installation.
It can be obtained from https://dev.mysql.com/downloads/connector/c/.
Path: C:\Program Files\hMailServer\Bin\libmysql.dll
```

This is MySQL 5.6.48 64-bit with libmysql.dll x64 version (5.7.30).... doesn't look backwards compatible

**Comment by Dravion** [comment]
On my end libmysql.dll v5.7.30 x64 version works on this MySQL 5.6.48 x64 version
![libmysql dll-v5 7 30_on_mysql- 5 6 48-x64-on-Win10-x64](https://user-images.githubusercontent.com/15117429/80611242-a89fc280-8a3a-11ea-8931-e897255cb14e.png)

I use this DLL-Version in my custom build and it works on the DBSetup.exe step at the Install Wizzard or later if someone wants to change the DB.

[libmysql-v5.7.30-x64.zip](https://github.com/hmailserver/hmailserver/files/4552457/libmysql-v5.7.30-x64.zip)

**Comment by RvdHout** [comment]
My used libmysql.dll  is exactly the same as yours (verified hashes)

![mysql_5 6 48](https://user-images.githubusercontent.com/13403301/80614152-66788000-8a3e-11ea-9e39-dbbfed02500f.png)

![mysql_5 6 48(2)](https://user-images.githubusercontent.com/13403301/80614385-b0616600-8a3e-11ea-97c7-592592ea5989.png)

**Comment by Dravion** [comment]
I think i found the Problem.
The libmysql,dll version 5.7.30 is linked against an earlier version of Visual C/C++ Redist DLL's (Visual Studio 2013) but in this Installer, only Visual C/C++ 2019 Redist DLL's are integrated.

1) You can let stay the hMailserver Setup DB-Wizzard stay open
2) Download this https://www.microsoft.com/en-us/download/details.aspx?id=40784 (x64)
3) After download run vcredist_x64.exe and click the Next button in hMailServer Setup,

**Comment by RvdHout** [comment]
Pfff, that  installer is going to be a hell to manage, Might not be the best move to include libmysql.dll in the installer with all those different requirements, looks like we have to include all Visual C/C++ Redistributable Packages from 2010 to 2019 :)

**Comment by Dravion** [comment]
libmysql.dll (5.7.30) should work fine with MySQL 5,48 if  libmysql.dll was  compiled with Visual C/C++2019. 

However: This means someone has to compile MySQL-Server 5.7.30 with Visual Studio 2019 
and extract libmysql.dll from it ;d

**Comment by Dravion** [comment]
Ok, i did. 
I compiled MySQL-Server 5.7.30 and get a fresh libmysql.dll v5.7.30 out of it
Test with Martins hMailServer-5.7.0-B2518.exe Setup works, so Visual Studio 2013 Redist
DLL's doesn't need to be included in the installer, using this libmysql.dll version
Download:
https://github.com/Dravion/mysql-server/releases/tag/libmysql.dll-custom

![msvc_142_libmysql dll_custom_build](https://user-images.githubusercontent.com/15117429/80724080-b66c4b00-8b01-11ea-8027-87f1e6db5db0.png)

**Comment by RvdHout** [comment]
Will check it out 👍

**Comment by TBAIKamine** [comment]
this is super frusturating
i want to be able to view the database using phpmyadmin.
so i have wamp installed with mysql 5.7.28
i installed every damn VC from 2010 through 2019
i tried all the libmysql.dll from my wamp install folder and the ones offered here in github
 this is #?@*$...___________

**Comment by RvdHout** [comment]
> this is super frusturating
> i want to be able to view the database using phpmyadmin.
> so i have wamp installed with mysql 5.7.28
> i installed every damn VC from 2010 through 2019
> i tried all the libmysql.dll from my wamp install folder and the ones offered here in github
> this is #?@*$...___________

Take some xanax

**Comment by Dravion** [comment]
Try this one
https://github.com/Dravion/mysql-server/releases/download/libmysql.dll-custom/libmysql.dll

**Comment by TBAIKamine** [comment]
@Dravion thank you so much, i check your post in the hmailserver forum
i went to mysql website and selected the right version
i also noticed the 32bits was requested so it worked. no xanax needed this time (@RvdHout )

now i run into another problem : Database version could not be detected.
i will check the git issues in this repo
if not found will create one
cheers all

**Comment by martinknafve** [comment]
Since this is an enhancement (rather than a bug) and it turned out to be more complicated than expected, I will close this. If someone wants to create a PR for it then we can of course integrate it, but I won't have time to resolve this.
