### ISSUE TITLE
AUTH PLAIN not working with libcurl

### ISSUE THREAD

**Issue by tomy2105** [hmailserver/hmailserver#299]
I'm using 3rd party program which uses libcurl to send mail to hMailserver using AUTH PLAIN (which is in new libcurl preferred over AUTH LOGIN) and it does not work.

Looking at the relevent RFC (https://tools.ietf.org/html/rfc4616) it seems that libcurl is correctly forming base64 encoded usernameNULusernameNULpassword sequence.

However looking at https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/SMTP/SMTPConnection.cpp method AuthenticateUsingPLAIN_(const String &sLine) I see code is looking for tab delimiter and not nul.

Moreover, only looking briefly at the code, not sure if code handles double username correctly either.

Could someone confirm if I'm correct to say hMailserver AUTH PLAIN has problems?

Thanks in advance.

**Comment by martinknafve** [comment]
This was fixed as part of this:
https://github.com/hmailserver/hmailserver/pull/385

**Comment by RvdHout** [comment]
@martinknafve
In my opinion and to my knowledge hmailservers accepts both /0 and /t as delimiters when using AUTH PLAIN

```
\0: \0username@domain.com\0P@ssword
\0: AHVzZXJuYW1lQGRvbWFpbi5jb20AUEBzc3dvcmQ=


220 Welcome to mail.domain.nl
EHLO mailserver.com
250-mail.domain.nl
250-SIZE 52428800
250-STARTTLS
250-AUTH LOGIN PLAIN
250 HELP
AUTH PLAIN AHVzZXJuYW1lQGRvbWFpbi5jb20AUEBzc3dvcmQ=
235 authenticated.
QUIT
221 goodbye
```

```
\t: \tusername@domain.com\tP@ssword
\t: CXVzZXJuYW1lQGRvbWFpbi5jb20JUEBzc3dvcmQ=


220 Welcome to mail.domain.nl
EHLO mailserver.com
250-mail.domain.nl
250-SIZE 52428800
250-STARTTLS
250-AUTH LOGIN PLAIN
250 HELP
AUTH PLAIN CXVzZXJuYW1lQGRvbWFpbi5jb20JUEBzc3dvcmQ=
235 authenticated.
QUIT
221 goodbye
```

in code we split them using /t, see:
https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/SMTP/SMTPConnection.cpp#L257
https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/SMTP/SMTPConnection.cpp#L279


Not even sure why you say it fixes, as the issue in this post is about SMTP and the other one about SASL....and makes you wonder if SASL AUTH PLAIN also accepts /t/and /0

https://github.com/large/hmailserver/blob/5d5351492b24a5a4f4da836e20d85b8484d0f623/hmailserver/source/Server/IMAP/IMAPCommandAuthenticate.cpp#L66
