### ISSUE TITLE
COM API unread messages

### ISSUE THREAD

**Issue by heyifei** [hmailserver/hmailserver#300]
Hi,guys!

I'm trying to get unread messages of an account by COM API.

hMailServer.Application hMailApp = new hMailServer.Application();
                hMailApp.Authenticate("admin", "xxxxxx");
                hMailServer.Domain myDomain = hMailApp.Domains.ItemByName["domain"];
                hMailServer.Messages msg = new hMailServer.Messages();
                hMailServer.Account account = myDomain.Accounts.ItemByAddress["xyz@domain.com"];
                msg = account.Messages;
                int newMsgCnt = 0;
                int msgCNT = account.Messages.Count;
                for (int i = 0; i < msgCNT; i++)
                {
                    //see table [hm_messages] field [messageflags] unread message is 96
                    //eMessageFlag.eMFVirusScan+eMessageFlag.eMFRecent = 96
                    bool flag = msg.get_ItemByDBID(msg[i].ID).Flag[eMessageFlag.eMFVirusScan]&& msg.get_ItemByDBID(msg[i].ID).Flag[eMessageFlag.eMFRecent]; //**always true**
                    if (flag)
                    {
                        newMsgCnt++;
                    }
                }
but flag always TRUE.
Can anyone help?
Thanks !

**Comment by heyifei** [comment]
more info  hmailServer 5.6.5-B2367

**Comment by RvdHout** [comment]
For scripting and general support questions you better should try the [https://www.hmailserver.com/forum](url)

**Comment by heyifei** [comment]
> For scripting and general support questions you better should try the [https://www.hmailserver.com/forum](url)

Thanks for your information.
