### ISSUE TITLE
HMaiAdmin on sever core 2016/2019  - Improved support needed

### ISSUE THREAD

**Issue by PrismaComputer** [hmailserver/hmailserver#303]
Some parts of HMailAdmin are not working when running on server core installations:

File and directory pickers are not available, so it should be possible to always type in paths. Pressing a file picker button should also not lead to error messages or freezes.

The spam assassin test also freezes. I suspect the shown test result window to not working under sever core.

**Comment by RvdHout** [comment]
Simply install the hmailadmin on a supported OS? Why did you pick Server Core in the first place? Don't come complaining some Gui parts don't function, that is the whole point of using Server core, isn't it?

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by PrismaComputer** [comment]
Why are you spamming me again with nonsense?
First of all, Martin told me that he is willing to support core installations. Second, older core installations are better supported. When I remember correctly there where some changes made expecially for that purpose..

And last but not least, I never said I want GUI elements back in sever core. I just expect hMailAdmin NOT TO FREEZE and to be able to TYPE all paths BY HAND.

**Comment by RvdHout** [comment]
You expect to much...good luck!🤣

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by martinknafve** [comment]
I won't add support for non-GUI versions of Windows server, due to lack of time.
