### ISSUE TITLE
PlusAddressing with no char selected causes "550 Unknown User"

### ISSUE THREAD

**Issue by palinkas-jo-reggelt** [hmailserver/hmailserver#308]
Version: 5.7.0-B2497 (x64)

I stumbled onto this by accident. 

Enable plus addressing for a domain, but DO NOT select a character. This causes SMTP to reject incoming messages with error 550 Unknown User for all accounts on that domain. Those same accounts can log in via IMAP without issue.

**Comment by martinknafve** [comment]
I have added validation so that you can't enable plus addressing without also selecting a plus addressing character.
