### ISSUE TITLE
Release 5.6.8

### ISSUE THREAD

**Issue by stephanruhland** [hmailserver/hmailserver#309]
Hi,
the latest stable release is now more than 2 years old.
Is there a plan to move beta version 5.6.8 to a stable release?
![image](https://user-images.githubusercontent.com/1325150/71004777-b2a3d300-20e2-11ea-8bc7-639a23074a19.png)

Kind regards
Stephan

**Comment by OutbackMatt** [comment]
That Beta is stable if you wish to use it

there is plans for a 5.7.0 version, currently in ALPHA

**Comment by caugner** [comment]
@OutbackMatt If that beta is stable, why isn't it published as a stable 5.6.8 release?

**Comment by RvdHout** [comment]
Because it is 5.7! :)

**Comment by OutbackMatt** [comment]
Martin would need to clarify the why

From the archives page you can see how many times it has been downloaded
https://www.hmailserver.com/download_archive

From the main project page here (on Github) Martin has stated that at least 500 downloads need to occur before considering removing Beta tag

Many tens of thousands of downloads later....

**Comment by caugner** [comment]
@martinknafve Would you be able to publish the current beta as a stable release? Or if not, could you clarify what is blocking this step?

**Comment by RvdHout** [comment]
5.6.7 is SSLv3 and TLS 1.0 to 1.2 (OpenSSL 1.0.x)
5.6.8 is TLS 1.0 to 1.3 (OpenSSL 1.1.x)
