### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by FabulousGee** [hmailserver/hmailserver#313]
Hey guys,

first of all let me say that I am so glad that Martin returned - hope you keep up the good work!!

An issue I am facing quite for a long time now is the missing  LDAP authentication. I know that there is a way to use Active Directory linking but this will only work if the hmailserver is running on the same machine as the AD (or if the server has been added to the AD).
In our case (and I think in many other cases, too) this is not a good solution. We have a local AD/LDAP for our internal stuff and in addition to that we have a second server on the internet which is running all web and mailing stuff. We do not want to have it in the AD (since we would have to do this via VPN which isn't really recommended) and on the other hand do not want to host the mailserver in our local network for obvious reasons.

So it would be really nice to have the option to auth against a LDAP service - I am not really into hmailserver's structure but it shouldn't be a very hard task since the basic functionality with Active Directory has already been done. IMHO it's just necessary to add a switch "AD" or "LDAP" and then switch configuration type in the code.

An example for LDAP auth in C++ can be found on stackoverflow:
https://stackoverflow.com/questions/31704482/authentication-against-active-directory-with-c-on-linux

I would do it myself and send a  pull request but I am really not into hmailserver's code (and my C++ is a mess ^^ ) and I have no time to fiddle it out currently... So I hope anyone else is facing the same issue and might be motivated to integrate this.

Anyway, hmailserver is a great software and I am really looking forward to 5.7 when it's ready!

**Comment by martinknafve** [comment]
I'm sorry but implementing LDAP is a fairly big task, and I won't have time to work on this. So while I agree that it would make sense, I'm closing this one for now not to give you false hopes. :)
