### ISSUE TITLE
More details and statistics

### ISSUE THREAD

**Issue by mstenz** [hmailserver/hmailserver#325]
Hi, 
hmailserver can potentically run a lot of harddisk actions (for example when copy one imap folders contents to another. this will lead in a batch where all these files of emails (let it be thousands) recreated and the database entry also recreated/updated. If you have a very busy server with a lots of file actions this could be a potential issue. 
Right now you cannot see what is happening under the hood (for example how many file operations or batch jobs are running, how many threads are used and so on. 
It would be realy cool if the administrator allows to show the amount of threads are currently used or if something is in the queue (like the delivery queue). 
Also i prefer to have a button to stop external communication but still allow to finish all internal running jobs/tasks/queues/threads before completely shutdown the server. 
Michael

**Comment by mstenz** [comment]
The reasion i am opening this issue is that i was forced to do some folder migration between different accounts on the same server. and it took ~2 or 3 hours for hmailserver to finish the whole disk/db operations but i was only able to see this by watching the process explorer. Still i was not aware really whats going on and if some type of utilization is of normal operation or for this special actions.

**Comment by OutbackMatt** [comment]
>  Also i prefer to have a button to stop external communication but still allow to finish all internal running jobs/tasks/queues/threads before completely shutdown the server.

On the status>> Server  page of the admin GUI, there is a 'pause' button - does exactly this

> Right now you cannot see what is happening under the hood (for example how many file operations or batch jobs are running, how many threads are used and so on.

I use process explorer, and the right click on the hMailserver.exe and get properties

This sort of query should really be dealt with on the user forum please
https://www.hmailserver.com/forum/index.php

**Comment by mstenz** [comment]
> On the status>> Server page of the admin GUI, there is a 'pause' button - does exactly this

Thx, i was not sure on this. 

> I use process explorer, and the right click on the hMailserver.exe and get properties

This is not exactly what i need. What the request is, having this on the hmailserver Administrator for example in the status tab or similar. Process explorer can only view the operation systems task threads. but internall in hmailserver there exist other threads/tasks and so on that the operating system it not able to see in this exact way. 

> This sort of query should really be dealt with on the user forum please
https://www.hmailserver.com/forum/index.php

This is nothing for the forum, because it is a feature request. There is no help from normal users expected as it requires a developer to do it.

**Comment by OutbackMatt** [comment]
There is a feature request section in the user forum
https://www.hmailserver.com/forum/viewforum.php?f=2

**Comment by mstenz** [comment]
May be, but I have posted it here.

**Comment by martinknafve** [comment]
This won't be implemented (due to lack of time on my part).
