### ISSUE TITLE
Usage of deprecated PHP version

### ISSUE THREAD

**Issue by Jerlag01** [hmailserver/hmailserver#328]
Due to the documentation we are forced to use deprecated versions of PHP for the phpwebadmin. 

Is there any chance this gets updated to a newer version of PHP?

**Comment by OutbackMatt** [comment]
There is a workaround posted here >> https://www.hmailserver.com/forum/viewtopic.php?f=7&t=34837

**Comment by martinknafve** [comment]
Next build will no longer depend on deprecated PHP features. I've also updated the documentation with some missing information.
