### ISSUE TITLE
Move builds from TeamCity to GitHub Actions

### ISSUE THREAD

**Issue by martinknafve** [hmailserver/hmailserver#331]
Experimental version here (which needs some cleanup):
https://github.com/martinknafve/hmailserver-1/actions

**Comment by martinknafve** [comment]
Any opinion on this @RvdHout? As I see it, the main benefits would be:

* One less server to maintain and keep updated (in the long term, I'll keep it around for 5.6)
* Everyone with source code access has easy access to download build as well without needing separate account
* Anyone (and not just me) can tweak the builds.

Main drawbacks I think are:

* A bit less control. Right now GitHub Actions does not yet have latest boost version (I'm guessing they will be a bit behind)

**Comment by RvdHout** [comment]
Mmm, i have totally have no experience with GitHub Actions, but if i understand it right it the Github variant of Teamcity? 

Don't exactly know what you mean with points 2 and 3...

**Comment by martinknafve** [comment]
Both TeamCity and GitHub Actions are 'continuous integration' systems which compiles the code automatically whenever it's pushed to git (and potentially run unit tests etc as well). So they are very similar. 

With GitHub actions, you define a workflow in yaml which specifies what should be done on commit, and then GitHub will take care of running that. I've created an experimental version here for hMailServer:
https://github.com/martinknafve/hmailserver-1/blob/master/.github/workflows/main.yml

Whenever code is pushed to git, GitHub will start a VM/container with Windows Server 2019, Visual Studio 2019, InnoSetup etc already installed and execute the build.

This makes the entire build process a bit more transparent, since the build is defined in a file in the git repo and everyone has access to it, instead of being defined by me on a server which only I have access to (build.hmailserver.com).

So if someone wonders whether the ConfigureInstallation-tool is built automatically then they can find that answer in the yaml-file. This also means that if someone goes ahead and forks hMailServer, then they'll be able to use the same build pipeline and have continuous integration for their fork automatically.

**Comment by martinknafve** [comment]
Reverted these changes and moved back to TeamCity, mainly due to the lack of Boost in the GitHub Actions environment.
