### ISSUE TITLE
hMailServer-5.7.0-B2530-x64 - VCRedist 2013/2019 dependency mismatch with  libmysql.dll v5.7.x (x64)

### ISSUE THREAD

**Issue by Dravion** [hmailserver/hmailserver#339]
*Description:
If a User is installing a x64 version of hMailServer 5.7, which was build with Visual Studio 2019
and wants to use a MySQL DB-Server. the User cannot complete the Installation because it fails
at the DB-Creation Wizard step invoked by the Innosetup Installer.

Error message: 
The MySQL client (libmysql.dll, x64 could not be loaded)
It can be obtained from https://dev.mysql.com/downloads/connector/c/

But the download link is no longer valid, the right one is:
https://dev.mysql.com/downloads/mysql/5.7.html

**PROBLEM:** 
Even if the User would download the correct ZIP-File (for example:
https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.30-winx64.zip)
unzip and copy the required file from 

* \mysql-5.7.30-winx64\lib\libmysql.dll
TO:
*\hMailServer\Bin\libmysql.dll

Its not possible to complete the DBSetup step, because the libmysql.dll was compiled
with Visual Studio 2013, which has the wrong dependency as you can see:

C:\Temp\libmysql_dll_5.7.30>dumpbin /DEPENDENTS oracle\libmysql.dll
Microsoft (R) COFF/PE Dumper Version 14.26.28805.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file oracle\libmysql.dll

File Type: DLL

  Image has the following dependencies:

    MSVCR120.dll
    KERNEL32.dll
    CRYPT32.dll
    Secur32.dll
    MSVCP120.dll
    bcrypt.dll
    USER32.dll
    ADVAPI32.dll
    WS2_32.dll

*SOLUTION 1:
The User needs to have VC 2013 Redist DLL-Installed to make libmysql.dll v5.7.30 (x64)
run again

*SOLUTION 2:
Build MySQL-Server 5.7 from Source with Visual Studio 2019 to get the correct
libmysql.dll version
*Repository
https://github.com/mysql/mysql-server/tree/5.7

In this case, the libmysql.dll DLL-Dependencies is looking like this:

C:\Temp\libmysql_dll_5.7.30>dumpbin /DEPENDENTS custom\libmysql.dll
Microsoft (R) COFF/PE Dumper Version 14.26.28805.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file custom\libmysql.dll

File Type: DLL

  Image has the following dependencies:

    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    KERNEL32.dll
    libssl-1_1-x64.dll
    libcrypto-1_1-x64.dll
    Secur32.dll
    ADVAPI32.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-conio-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    MSVCP140.dll
    WS2_32.dll

**Comment by martinknafve** [comment]
Will be handled as part of https://github.com/hmailserver/hmailserver/issues/295.
