### ISSUE TITLE
Forced TLS for incoming/outgoing email to specific domain?

### ISSUE THREAD

**Issue by caugner** [hmailserver/hmailserver#340]
A new customer requires us to set up "Forced TLS", i.e. hMailServer should only accept email from/send email to another mail server if the connection is encrypted, and trigger a Non-Delivery Report otherwise:

> Encrypting mail transmission via Forced TLS (Transport Layer Security) Transport Layer Security encrypts the transmission of e-mail over the internet. The encryption takes place between the Internet access points of the two communicating companies and is automatically carried out without any actions by the communicating communication partners (users). Forced TLS connection emails will encrypted mails in all cases between transmission of communication partners. If a connection fails due to an error situation, the mail transport is rejected and the sender of the e-mail receives a Non Delivery Report (NDR). Basically, all mails of all communication partners are encrypted via a Forced TLS connection.

Does hMailServer support this? And if not, how much would it cost to sponsor this feature?

**Comment by OutbackMatt** [comment]
In the Ports section of the GUI, just set all standards ports to 'require TLS'
(25, 143, 110, 587)

You will need a suitable certificate installed.
Be warned that you will miss much mail by doing this, especially when you also turn off SSLv3.0, and TLSv1.0 and TLSv1.1

Use a newer (beta) version of hMailserver to include support for TLSv1.3

**Comment by caugner** [comment]
To avoid missing mail by other customers, we would prefer to "require TLS" on the mailbox level. Like this we could create a dedicated "TLS only" email address.

**Comment by mstenz** [comment]
> prefer to "require TLS" on the mailbox level.

I do not understand this requirement really. Mailboxes communicate internally within the server, so there is no SMTP connection and the clients can use IMAPS. Or I don#t get the point of your request?

**Comment by RvdHout** [comment]
I could see one would like to have clients use SSL/TLS, but the communication between server (which should first try STARTTLS by default if configured correctly) is beyond me...

You can force TLS/SSL for clients using IP Ranges, Require SSL/TLS for authentication

**Comment by caugner** [comment]
Thank you for your suggestions.

To clarify: I'm talking about enforcing encryption for non-authenticated transmissions (SMTP) between our hMailServer instance and a specific customer's (= domain's) external mail server.

An IP range with "Require SSL/TLS for authentication" would not cover our case, because connections between mail servers (i.e. "External to local e-mail-addresses") cannot require authentication, since external mail servers don't have credentials.

If there was an IP range option "Require SSL/TLS for all connections", this would be a viable solution (even though it doesn't adapt to changes of the external mail server's IP address or other mail server's sending mail on behalf of that mail server, cf. SPF).

**Comment by RvdHout** [comment]
Just thinking out loud....can't u use a Route for that specific customer? I believe you can set SSL/TLS in routes...

**Comment by caugner** [comment]
> Just thinking out loud....can't u use a Route for that specific customer? I believe you can set SSL/TLS in routes... (will be using SSL/TLS only for outgoing mails though)

Good idea, indeed the Routes feature seems to lead in the right direction.

However, it looks like it
1. covers outgoing mails only (as you mention),
2. requires "Target SMTP host" and "TCP/IP port" to be set (which means I would have to update these manually if the customer domain's MX entry change).

**Comment by OutbackMatt** [comment]
> To avoid missing mail by other customers, we would prefer to "require TLS" on the mailbox level. Like this we could create a dedicated "TLS only" email address.

If you don't have a dedicated hmailserver** for this customer, how will you know which connections to encrypt and which ones to allow unencrypted


> An IP range with "Require SSL/TLS for authentication" would not cover our case, because connections between mail servers (i.e. "External to local e-mail-addresses") cannot require authentication, since external mail servers don't have credentials.
You do understand that encryption is NOT the same as AUTHentication...
Many messages are sent to my server via an encrypted connection from people / servers that I don't know (including much SPAM). They don't AUTHenticate, but they do encrypt the connection


> If there was an IP range option "Require SSL/TLS for all connections", this would be a viable solution 

There is
Set a port to 'require StartTLS' or to 'SSL', and ONLY encrypted incoming connections matching that encryption level will be used

For outgoing setting a route to the appropriate encryption level will work
This customer will need a dedicated hMailserver**

**Comment by caugner** [comment]
> If you don't have a dedicated hmailserver** for this customer, how will you know which connections to encrypt and which ones to allow unencrypted

Let's assume I could define a rule that emails between `*@customer.example` and `*@local-hmailserver.example` must only be transmitted over encrypted connections.

For incoming emails: After the external mail server has sent `MAIL FROM` and `RCPT TO` (i.e. before the email content is transmitted), hMailServer knows whether that rule applies. Therefore hMailServer could reject the email (causing an NDR) if the current connection is not encrypted.

For outgoing emails: Since hMailServer has the full email, it knows whether the rule applies. If the external mail server does not support transport encryption, hMailServer could simply close the connection and generate an NDR.

> This customer will need a dedicated hMailserver**

That's not an option for us (too expensive).

**Comment by OutbackMatt** [comment]
So you ONLY want to encrypt traffic between your server and this customer's server?

Create a custom port, eg port 54325 that requires Encryption, and get the customer server to send to you ONLY on that port. You could EASILY reject mail from other ports using that domain name as sender domain with a script

Similarly in reverse, when you create a route, set a custom port and IP address. This will bypass the use of standard DNS mx records. You could create a global rule with 'use route' as an action

As an added bonus when you set a route, AND you have the 'verify remote server SSL/TLS certificates' selected in SSL/TLS settings, hmailserver will compare the name on the certificate to the name presented by the server to ensure that they match, before making the connection.

**Comment by caugner** [comment]
> So you ONLY want to encrypt traffic between your server and this customer's server?

Ideally, yes.

> Create a custom port, eg port 54325 that requires Encryption, and get the customer server to send to you ONLY on that port.

Thanks, that's a creative workaround. Unfrotunately that won't happen, partly because it doesn't fulfill our customer's requirements:

>> Forced TLS connection emails will encrypted mails **in all cases** between transmission of communication partners.

In other words: Both parties have to enforce independently that the other party cannot send/receive emails via unencrypted transmissions.

**Comment by OutbackMatt** [comment]
> In other words: Both parties have to enforce independently that the other party cannot send/receive emails via unencrypted transmissions.

OR, you would need to implement a solution JUST for this customer (and perhaps others who require ONLY encrypted connections)

Again, you cannot determine who a message is from AND THEN encrypt the connection.

The Encryption needs to happen first, either from the sender by design, or forced for ALL senders by the recipient server.

**Comment by caugner** [comment]
> Again, you cannot determine who a message is from AND THEN encrypt the connection.

Sure, but it can determine who the message is from and then refuse the message if the connection is not encrypted. That's the requirement. This would effectively prevent unencrypted transmission of emails between the parties.

(The idea is that one party could have a temporary problem with or misconfiguration of their mail server, but as long as both parties enforce these requirements, unencrypted transmission of emails is still prevented.)

**Comment by caugner** [comment]
By the way, Postfix [allows to specify TLS policies per recipient domain](http://www.postfix.org/TLS_README.html#client_tls_policy), at least for outgoing mail.

**Comment by caugner** [comment]
Which just made me think that @OutbackMatt's solution does **not** enforce encryption for outgoing mail, only for incoming mail:

> In the Ports section of the GUI, just set all standards ports to 'require TLS'
(25, 143, 110, 587)

**Comment by RvdHout** [comment]
> By the way, Postfix [allows to specify TLS policies per recipient domain](http://www.postfix.org/TLS_README.html#client_tls_policy), at least for outgoing mail.

Whats your point? Maybe you should simply use Postfix then....

**Comment by caugner** [comment]
> Whats your point?

I was pointing out how another mail server conceptually supports this feature. There is no need to reinvent the wheel, if other mail servers have solved this before.

**Comment by RvdHout** [comment]
Therefor i said use that mailserver if you need that feature as this has nothing to do with reinventing the wheel....i suppose you choose hmailserver as it much easier to administrate compared to postfix, both have their pros and cons.

I really doubt @martinknafve would incorporate such feature, as basically what you ask is very uncommon scenario, simply let mailservers decide how they send out mail, you know that if StartTLS is supported on both servers this is the default connection security used, right? If that fails or is unavailable it is tried without a secure connection, as 99% of all mailserver would do it

**Comment by caugner** [comment]
@RvdHout STARTTLS is susceptible to Man-in-the-Middle attacks, as the exchange about the availability of encryption is not encrypted.

**Comment by caugner** [comment]
See also [Posteo's TLS-sending guarantee](https://posteo.de/en/help/activating-tls-sending-guarantee), which enforces TLS for outgoing email.

PS: It seems that Postfix can be forced to require TLS for sending and receiving emails by setting `smtp_tls_security_level=encrypt` (for sending) and `smtpd_tls_security_level=encrypt` (for receiving).

**Comment by OutbackMatt** [comment]
> 
> 
> Which just made me think that @OutbackMatt's solution does **not** enforce encryption for outgoing mail, only for incoming mail:
> 
> > In the Ports section of the GUI, just set all standards ports to 'require TLS'
> > (25, 143, 110, 587)
Yes that is INCOMING only solution

This is for outgoing connections
> 
> For outgoing setting a route to the appropriate encryption level will work

Which looks to me like the postfix documentation you linked to

> 
> @RvdHout STARTTLS is susceptible to Man-in-the-Middle attacks, as the exchange about the availability of encryption is not encrypted.

Man in the middle can happen because the certificates aren't validated
Most client level antivirus that inspect SSL mail do exactly a man-in-the-middle attack. They put their own certificate in the middle to decrypt, then re-encrypt mail connections.


I'm really struggling to see the use case.
**Spam comes via encrypted connections very often (ever get spam from a gmail or outlook.com account - that will have arrived via an encrypted connection)
**Unless you and your client are actually testing for a specific certificate, man-in-the-middle can still happen


If this is ONLY for communication between you and the client, then a custom config at both ends will work, as would a VPN

If this is for all new mail to a particular fussy domain owner (irrespective of where the mail is from), then a stand alone instance of hMailserver will achieve what you need

And then you could always use postfix if that does what you want...

**Comment by RvdHout** [comment]
Or...

Wait and hope @martinknafve could use a bonus and could use some funding for this project.... and incorporates this feature
But that said, martin isn't that active (here) anymore, so maybe you should better contact martin directly using the contact form on the website

**Comment by caugner** [comment]
> This is for outgoing connections
>> For outgoing setting a route to the appropriate encryption level will work
> Which looks to me like the postfix documentation you linked to

You're right, except that hMailServer
1. does not support setting this globally,
2. [requires (for a domain) to specify "Target SMTP host" and "TCP/IP port"](https://github.com/hmailserver/hmailserver/issues/340#issuecomment-657458491)

> Man in the middle can happen because the certificates aren't validated

The man-in-the-middle can simply strip the STARTTLS advertising and you wouldn't even have an encrypted connection for which a certificate can be validated.

This is a security issue, not necessarily a spam issue.

Unfortunately we're going in circles.

Long story, short: Like I [mentioned already initially](https://github.com/hmailserver/hmailserver/issues/340#issue-651357976), we are willing to sponsor this security feature.

/cc @martinknafve

**Comment by RvdHout** [comment]
1. You said this is a single clients demand, so why would it need to be globally?
2. Simply use MX with lowest priority... this is not likely to change, port you have to figure out anyway... some do not allow SSL/TLS on port 25, and 465 needs to be used (or 587)

**Comment by caugner** [comment]
> You said this is a single clients demand, so why would it need to be globally?

If I could (alternatively) set this globally, managing a secondary "TLS-only" hMailServer instance would suddently make sense and be feasible.

**Comment by RvdHout** [comment]
That makes no sense, and likely is going to give issues for 99% of the usercase's.....are you personally going to answer all forums topics that can't send and receive mail after toggling that option?

**Comment by caugner** [comment]
> That makes no sense
> are you personally going to answer all forums topics

Please *seriously* consider what impression you make with statements like these.

Our opinions may differ, but that shouldn't prevent us from collaborating in a civilized manner and finding good solutions for problems. After all, you seem to have the best intentions to finding solutions for this issue.

**Comment by martinknafve** [comment]
This won't be implemented due to lack of time on my part.
