### ISSUE TITLE
[BUG] Can't sign in using Aurora Webmail lite PHP v8 (8.4.0-build-a3)

### ISSUE THREAD

**Issue by zFerry98** [hmailserver/hmailserver#341]
I have not solved but as usual I have to do it for my cocks.

**Comment by OutbackMatt** [comment]
This sort of query is better handled on the user forum
I doubt this is a bug

On what OS are you running  Afterlogic?
Has that OS been patched to include support for TLSv1.1 or TLSv1.2
(It doesn't happen automatically on Windows servers)

**Comment by zFerry98** [comment]
> This sort of query is better handled on the user forum
> https://www.hmailserver.com/forum/
> I doubt this is a bug
> 
> On what OS are you running Afterlogic?
> Has that OS been patched to include support for TLSv1.1 or TLSv1.2
> (It doesn't happen automatically on Windows servers)

>### Config:
hMailServer: 5.6.8 B2501, Windows Server 2019,
PHP 7310 for IIS,
IIS 10.
DB: MySQL 8

As I wrote above:
OS: Windows Server 2019 datacenter GUI (latest stable),
If you mean on which Webserver, IIS, Internet Information Service, version 10 with PHP for windows version 7310.

I don't know what you mean by TLS patch on windows. But I can confirm that 1.1, 1.2 and 1.3 certainly go.
1.1 from Email for android (old phones) both remotely and internally.
1.2 from Outlook for android.
1.3 from mozzilla thunderbird both remotely and internally.

At this point, I tell you the same thing that I also said on the AfterLogic forum. I try to put WebMail 8.2.19 back and see if it works with the latest HMS 5.6.8 B2501. If it goes, then it's either their change or not updated something that has been updated here instead.
If it doesn't work (which was the case with the Old HMS) then it is a problem of HMS with the last Beta. For this I wrote both here and on the forum. Now I do these tests and update the comment 👍

**Comment by OutbackMatt** [comment]
> > On what OS are you running Afterlogic?
> > Has that OS been patched to include support for TLSv1.1 or TLSv1.2
> > (It doesn't happen automatically on Windows servers)
> 

> If you mean on which Webserver, IIS, Internet Information Service, version 10 with PHP for windows version 7310.
> 
> I don't know what you mean by TLS patch on windows. But I can confirm that 1.1, 1.2 and 1.3 certainly go.
> 1.1 from Email for android (old phones) both remotely and internally.
> 1.2 from Outlook for android.
> 1.3 from mozzilla thunderbird both remotely and internally.


hmailserver accepting TLSv1.3 is different from your windows server trying to use it for outgoing connections

use this tool on teh machine where Afterlogic is installed >> https://www.nartac.com/Products/IISCrypto

You may have SMD enabled on your server, which is SSLv3.0
Some software uses the server security mechanisms to create connections rather than third party tools
I'm guessing that Afterlogic use the Windows defaults

If I recall correctly Afterlogic uses ASP rather than PHP. ASP uses the underlying Windows security mechanisms

**Comment by zFerry98** [comment]
> > > On what OS are you running Afterlogic?
> > > Has that OS been patched to include support for TLSv1.1 or TLSv1.2
> > > (It doesn't happen automatically on Windows servers)
> 
> > If you mean on which Webserver, IIS, Internet Information Service, version 10 with PHP for windows version 7310.
> > I don't know what you mean by TLS patch on windows. But I can confirm that 1.1, 1.2 and 1.3 certainly go.
> > 1.1 from Email for android (old phones) both remotely and internally.
> > 1.2 from Outlook for android.
> > 1.3 from mozzilla thunderbird both remotely and internally.
> 
> hmailserver accepting TLSv1.3 is different from your windows server trying to use it for outgoing connections
> 
> use this tool on teh machine where Afterlogic is installed >> https://www.nartac.com/Products/IISCrypto
> 
> You may have SMD enabled on your server, which is SSLv3.0
> Some software uses the server security mechanisms to create connections rather than third party tools
> I'm guessing that Afterlogic use the Windows defaults
> 
> If I recall correctly Afterlogic uses ASP rather than PHP. ASP uses the underlying Windows security mechanisms

![image](https://user-images.githubusercontent.com/17975351/87932694-37493c00-ca8c-11ea-9dea-9adda8a60cfa.png)
Afterlogic webmail lite is written in PHP, in fact I use IIS 10 with PHP 7.
The problem now is that the webmail forums are no longer responding.

But what does IIS use v1.3 have to do with webmail and HMS? There is "1.3" is not forced, there are always 1.1 1.2 active and working. From IIS also in the config I did not put SSL for the site certificates. From IIS you can tell if: Force SSL, Ignore SSL or Accept SSL. I, for SSL I tried to put now both ignore and then after accept, nothing has changed, always wrong. The problem is that it is no longer an SSL TLS issue etc. Because "Afterlogic webmail lite php 8.2.19" together with HMS 5.6.8 B2451 (just the version that removed SSLv3 and put TLSv1.3) worked without problems. Unfortunately I cannot verify if 8.4.0 works with HMS B2451. Again, HMS already with the patch that removes SSLv3 and adds TLSv1.3 worked with WebMail lite php 8.2.19. On the changelog of the afterlogic forum it says nothing about changes in ssl / tls preferences for the latest version.

I want to clarify again, Webmail Lite PHP 8.2.19 (the one that worked together with HMS B2451) DOES NOT WORK with HMS 2501. And the B2451 is the version where SSLv3 has been removed and TLSv1.3 added.

Maybe I'm not understanding but I think it's a problem of HMS more than of WebMail lite php. If it were WebMail lite PHP, then already with the B2451 it no longer had to work.

I apologize if he seemed aggressive ... But on a site they say it's his fault, on the other side they say it's the fault of the other and then you don't understand anything anymore.

At this point I'm going to look for a way to force PHP and IIS to use TLS but in my opinion it's not IIS and PHP fault.

**Comment by OutbackMatt** [comment]
> I want to clarify again, Webmail Lite PHP 8.2.19 (the one that worked together with HMS B2451) DOES NOT WORK with HMS 2501. And the B2451 is the version where SSLv3 has been removed and TLSv1.3 added.
> 
> Maybe I'm not understanding but I think it's a problem of HMS more than of WebMail lite php. If it were WebMail lite PHP, then already with the B2451 it no longer had to work.
> 
> I apologize if he seemed aggressive ... But on a site they say it's his fault, on the other side they say it's the fault of the other and then you don't understand anything anymore.
> 
> At this point I'm going to look for a way to force PHP and IIS to use TLS but in my opinion it's not IIS and PHP fault.

If it was hMailserver, don't you think that many of us would have seen these issues with our own webmail.

I don't use Afterlogic
I do use Roundcube and other PHP based web mail products.
I have PHP7.3 running on Ubuntu in my network, with Roundcube connecting to my hMailserver on a Windows machine. PHP uses a third party SSL library - in most cases OpenSSL

Perhaps this is about your self signed certificate..?

**Comment by zFerry98** [comment]
Nothing to do, I updated the HMS certificate with the latest version of OpenSSL1.1.1g and that of the website mail on IIS both from IIS Certificates and using Let's Enc.
It continues to give exactly the same problem.

**Comment by zFerry98** [comment]
### Roundcubemail 1.4.7:

### 993 587 ssl:// tls:// localhost myexternalIP (tested with firewall off)

`
[23-Jul-2020 02:55:15 +0300]: <7ga2e0ou> PHP Error: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
 (POST /cubemail/?_task=mail&_unlock=loading1595458532490&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:55:15 +0300]: <7ga2e0ou> PHP Error: Failed to connect socket: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
 (POST /cubemail/?_task=mail&_unlock=loading1595458532490&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:55:15 +0300]: <7ga2e0ou> SMTP Error: Connection failed: Failed to connect socket: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
 in B:\SERVER\IIS8\www3\cubemail\program\lib\Roundcube\rcube.php on line 1702 (POST /cubemail/?_task=mail&_unlock=loading1595458532490&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:55:53 +0300]: <7ga2e0ou> PHP Error: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
 (POST /cubemail/?_task=mail&_unlock=loading1595458570017&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:55:53 +0300]: <7ga2e0ou> PHP Error: Failed to connect socket: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
 (POST /cubemail/?_task=mail&_unlock=loading1595458570017&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:55:53 +0300]: <7ga2e0ou> SMTP Error: Connection failed: Failed to connect socket: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
 in B:\SERVER\IIS8\www3\cubemail\program\lib\Roundcube\rcube.php on line 1702 (POST /cubemail/?_task=mail&_unlock=loading1595458570017&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:56:58 +0300]: <7ga2e0ou> PHP Error: Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato.
 (POST /cubemail/?_task=mail&_unlock=loading1595458616797&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:56:58 +0300]: <7ga2e0ou> PHP Error: Failed to connect socket: Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato.
 (POST /cubemail/?_task=mail&_unlock=loading1595458616797&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:56:58 +0300]: <7ga2e0ou> SMTP Error: Connection failed: Failed to connect socket: Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato.
 in B:\SERVER\IIS8\www3\cubemail\program\lib\Roundcube\rcube.php on line 1702 (POST /cubemail/?_task=mail&_unlock=loading1595458616797&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:57:55 +0300]: <7ga2e0ou> PHP Error: Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato.
 (POST /cubemail/?_task=mail&_unlock=loading1595458673583&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:57:55 +0300]: <7ga2e0ou> PHP Error: Failed to connect socket: Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato.
 (POST /cubemail/?_task=mail&_unlock=loading1595458673583&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:57:55 +0300]: <7ga2e0ou> SMTP Error: Connection failed: Failed to connect socket: Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato.
 in B:\SERVER\IIS8\www3\cubemail\program\lib\Roundcube\rcube.php on line 1702 (POST /cubemail/?_task=mail&_unlock=loading1595458673583&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:58:58 +0300]: <7ga2e0ou> PHP Error: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
 (POST /cubemail/?_task=mail&_unlock=loading1595458755882&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:58:58 +0300]: <7ga2e0ou> PHP Error: Failed to connect socket: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
 (POST /cubemail/?_task=mail&_unlock=loading1595458755882&_framed=1&_lang=it&_action=send)
[23-Jul-2020 02:58:58 +0300]: <7ga2e0ou> SMTP Error: Connection failed: Failed to connect socket: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
 in B:\SERVER\IIS8\www3\cubemail\program\lib\Roundcube\rcube.php on line 1702 (POST /cubemail/?_task=mail&_unlock=loading1595458755882&_framed=1&_lang=it&_action=send)`
