### ISSUE TITLE
how to change the default smtp port 25 to 465？

### ISSUE THREAD

**Issue by w8589167** [hmailserver/hmailserver#343]
my isp locked my 25 port ，i can't sent mail  to other email account。i won't to use smtp realy
how i can change the default send port to 465？

**Comment by mstenz** [comment]
Hi, this is more a Forum related question, than a bug or similar. 
You can reach the Forum here: https://www.hmailserver.com/forum/viewforum.php?f=7&sid=acd24f5989b3323d6b7178cffb9b939a

**Comment by Stoyan-Bukovich** [comment]
Hi, you should not change the SMTP port 25 as this port is required for mail server to mail server communication by RFC. This port is not for normal client to server communication. By RFC you have 465 and 578 submission ports. If you want to have more non standard SMTP ports, you can have as many as you want. To do that go to settings > TCP/IP ports than select Add new...
Afterwards for Protocol select SMTP for TCP/IP port type the port number you want (example 9025) and for security connection NONE or whatever your security might be, SSL certificate in case of NONE must be empty, and hit SAVE button. 

This will give you an extra SMTP non-standard, non-RFC compliant port. Oh, and don't forget to open firewall exception in your Windows machine and NAT forwarding in your router etc.

Cheers
