### ISSUE TITLE
Unable to receive emails from web form using hmailserver

### ISSUE THREAD

**Issue by Redflyerone-1** [hmailserver/hmailserver#346]
When we send emails from our website email form, the emails go to the hmailserver pickup folder but don't get delivered. This may be a smtp configuration in the IIS. However, we can send / receive emails using our pc outlook.
We need to verify the spf setup. We get tons of spam. How can this be fixed ?
We are looking for an expert to review our configuration of the hmailserver, IIS, DNS, spam filter...
You contact me at ech@frenchcinema.com
Thank you.

**Comment by mstenz** [comment]
Hi, this is not really a type of issue for github, more for forum. But if you want to have personal support, please send me an email
info@cowmedia.de

**Comment by Redflyerone-1** [comment]
I am new at github. Just joined today. Thank you for your reply.
