### ISSUE TITLE
IP Ranges – sorting by date (expires) not correct

### ISSUE THREAD

**Issue by helptiger** [hmailserver/hmailserver#347]
If the list of ip ranges is sorted by date (expires), it is sorted by text and not by date.

![Screenshot-12-46-2020_09 46 36](https://user-images.githubusercontent.com/10258902/90061136-fee0fa80-dce5-11ea-8762-3dba1b116586.png)  ![Screenshot-12-54-2020_09 54 51](https://user-images.githubusercontent.com/10258902/90061524-875f9b00-dce6-11ea-9d84-ae3c7b7403eb.png)

In my opinion, the sorting should really be done by date.
Tested on latest 5.7 with MariaDB 10.5.4.

**Comment by OutbackMatt** [comment]
You can click on the 'expires' at the top to re-sort them by date

**Comment by helptiger** [comment]
> You can click on the 'expires' at the top to re-sort them by date

I did that of course, result see pictures: no correct sorting by date.

**Comment by RvdHout** [comment]
It does here

**Comment by OutbackMatt** [comment]
Works for me, too
Also with MySQL, hmailsevrer 5.7.0-B2536-x64

Before
![image](https://user-images.githubusercontent.com/7231493/90100815-c93d1f80-dd80-11ea-9846-ba5e4b75ad59.png)


After sort by 'Expires'
![image](https://user-images.githubusercontent.com/7231493/90100882-f12c8300-dd80-11ea-925b-73629ddb39f4.png)

**Comment by helptiger** [comment]
so, for testing please add some 2021 dates

**Comment by RvdHout** [comment]
OK, that seems to be a bit off like you said.... 

On a side-note, a big (auto)ban list can really slow down hmailserver operation....i therefor don't ban anything longer then 24h so not really a issue for me

**Comment by RvdHout** [comment]
https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Tools/Administrator/Utilities/ListViewColumnSorter.cs
https://docs.microsoft.com/nl-nl/troubleshoot/dotnet/csharp/sort-listview-by-column

**Comment by RvdHout** [comment]
@martinknafve 

[This solution ](https://stackoverflow.com/a/15558965) doesn't seem to difficult to fix this datetime sorting issue

**Comment by RvdHout** [comment]
@helptiger 

Can you try this build of hmailadmin.exe? (Includes above mentioned fix)
https://d-fault.nl/files/ filename: hMailAdmin_sortbydate_fix.zip

**Comment by helptiger** [comment]
> @helptiger
> 
> Can you try this build of hmailadmin.exe? (Includes above mentioned fix)
> https://d-fault.nl/files/ filename: hMailAdmin_sortbydate_fix.zip

Thanks for your support. Your version works, the sorting is as it should be.

**Comment by helptiger** [comment]
Is it complicated to program that also the IP addresses are sorted ascending and descending?

**Comment by RvdHout** [comment]
> Is it complicated to program that also the IP addresses are sorted ascending and descending?

Probably not that complicated, if you follow the same procedure i did with DateTime column in the updated commit for this pull request.

You know it open source right? I would say give a go....
https://stackoverflow.com/questions/6248039/how-to-sort-list-of-ip-addresses-using-c-sharp

**Comment by helptiger** [comment]
The issue was fixed and the code has been released.

**Comment by visualperception** [comment]
What I did as I like to sort by date all over the place is to change my windows date format to display date as yyyy-mm-dd
Go to windows Settings/time and language/region/change data formats
In there you can change the way dates are displayed. To me it makes much more sense to display dates as yyyy-mm-dd and that way throughout windows you can sort on date and have the lists display in date order.
