### ISSUE TITLE
Can you set a limit for the number of mails sent per day to avoid spam?

### ISSUE THREAD

**Issue by khh88** [hmailserver/hmailserver#349]
Can you set a limit for the number of mails sent per day to avoid spam?
Ipswitch Mailserver has HAMR which helped a lot
Hacked Account Mail Regulator (HAMR) limits can be configured and customized at multiple levels: System wide, Domain wide or even individually by user.
Thanks KH

**Comment by LeeThompson** [comment]
This would be a worthwhile feature I think.   Default behavior should be "unlimited", but should be a setting for both domain and users levels.

**Comment by OutbackMatt** [comment]
Many of us achieve this with custom scripts

In a default hMailserver installation, users can AUTH with one account and send FROM another user
This alone makes limiting sending fairly hard on it's own. When we script we also need to ensure that the sender is the same as the AUTH credentials

**Comment by khh88** [comment]
Yes, the SMTP limit has helped me many times when customers' websites were hacked.
Instead of 10,000 spam emails, only 200 could be sent a day and I received a warning email so that we could protect ourselves well and did not end up on any blacklist.
The Auth account is sufficient, the number of emails sent on the current day.
Can something like this be implemented via a script? I have to get used to it first,
Is there the number of sent mails in the DB tables?

**Comment by OutbackMatt** [comment]
Head to the user forum
A number of methods, including detailed scripts and help available there

https://www.hmailserver.com/forum/
