### ISSUE TITLE
Logging issues and feature request

### ISSUE THREAD

**Issue by globules-io** [hmailserver/hmailserver#355]
Issue : If I start the logging then select another element of the tree (on the left), then back to logging, log is gone.
Feature request : be able to right click on the IP on the logging interface and add to blocked IPs/ranges.

**Comment by zechnkaas** [comment]
As a workaround you can open the console 2 times

**Comment by OutbackMatt** [comment]
Log is written to file if enabled
Many of us find BareTail useful for watching live logs

**Comment by martinknafve** [comment]
This one won't be implemented, due to lack of time on my part and a workarounds exists (view the log on disk instead of UI, or start 2 copies of the UI).
