### ISSUE TITLE
APOP POP3 command support

### ISSUE THREAD

**Issue by kay27** [hmailserver/hmailserver#356]
Hi,

What do you think about adding APOP support? ([RFC 1939 page 14](https://www.ietf.org/rfc/rfc1939.txt))

**Comment by OutbackMatt** [comment]
Doing the smallest amount of research possible, it would seem that APOP has it's limitations, including only using MD5.

General Consensus is to use StartTLS (Required) on your default POP3 connections (port 110), or use SSL connections on port 995.

**Comment by martinknafve** [comment]
This won't be implemented. Use TLS instead.
