### ISSUE TITLE
Installation problems with postgresql

### ISSUE THREAD

**Issue by lublak** [hmailserver/hmailserver#361]
At my work we use a postgresql 13 database.
I have a predefined database with the name: "db-internal-fm" with a schema hmail.
I also have an user "hmail" that have access only to this schema.
First of all: I can't set the installation schema. I hope it can install it without setting the schema and it is used by default.
Also i get an error:

```
Starting task...
Please wait while updating database settings...
authentication method 10 not supported
```

**Comment by SorenRR** [comment]
Have you tried asking here: https://www.hmailserver.com/forum/

**Comment by lublak** [comment]
@SorenRR no, but I think the "authentication method 10 not supported" comes from the postgres client (library) being too old.
I look into the repo and found out that https://github.com/hmailserver/hmailserver/tree/5.6.8/libraries/pgsql8.2.4 is very old.
The "master" has not yet been published but has the newer libraries https://github.com/hmailserver/hmailserver/tree/master/libraries.
I think this issue can be closed. But thank you for your answer.
