### ISSUE TITLE
INI settings initialization

### ISSUE THREAD

**Issue by RvdHout** [hmailserver/hmailserver#364]
@martinknafve 

Quick question, in IniFileSettings.cpp you initialize various settings, example:
https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/Common/Application/IniFileSettings.cpp#L41-L52

Why are those highlighted initialized as boolean (false) and not using the proper variable types, in this case integers?

**Comment by martinknafve** [comment]
This appears to be a copy/paste mistake which should be fixed.

**Comment by RvdHout** [comment]
Not sure if you are aware, 5.7.x branch is not building any artifacts since you moved back to teamcity.
