### ISSUE TITLE
my server sends the emails to spam or span in gmail and outlook

### ISSUE THREAD

**Issue by ortiga88** [hmailserver/hmailserver#365]
my configuration is for 587 and startls my domain is "mercamira.es" can someone help me ??

<img width="340" alt="image" src="https://user-images.githubusercontent.com/26000087/112840475-ab1df880-909f-11eb-98dc-404f23b517c2.png">

**Comment by martinknafve** [comment]
Please see this:
https://www.hmailserver.com/documentation/latest/?page=ts_send_messages_to_specific_server

If it's not sufficient then please ask in the forum instead.
