### ISSUE TITLE
Error sending emails to an external server hmailserver?

### ISSUE THREAD

**Issue by StasToken** [hmailserver/hmailserver#367]
I encountered a strange oddity, when I try to send messages to an external mail server, I receive this email

```
    Your message did not reach some or all of the intended recipients.

    Sent: Sun, 4 Apr 2021 16:04:00 +0300 Subject: ping

    The following recipient(s) could not be reached:

    xxxxxx@yandex.ru Error Type: SMTP Connection to recipients server failed. Error: Could not connect to xxx.xxx.xxx.xxx on port 25 since this would mean connecting to myself.

    Tried 5 time(s)

    hMailServer

```

I run the diagnostic says that everything is OK, except that the folder for the backup is not specified. I checked the host file - there is nothing suspicious there, I do not ask you to give a 100% answer, hint where to look next? I don't even understand how to diagnose this problem, and I can't really find anything in google
_Version 5.6.7-B2425_

**Comment by OutbackMatt** [comment]
Please ask these type of questions on the user forum
https://www.hmailserver.com/forum/index.php

**Comment by StasToken** [comment]
Sorry - I didn't know there was a forum.

**Comment by StasToken** [comment]
Problem solved! https://hmailserver.com/forum/viewtopic.php?f=7&t=36387&p=228266#p228266
