### ISSUE TITLE
"Mailbox remove" doesnt remove the folderstructure on disk

### ISSUE THREAD

**Issue by mstenz** [hmailserver/hmailserver#370]
I have deleted a mailbox and the mail files itself get removed, but the whole folder structure including 256 hex subfolders was not deleted. 
There are no errors in the logfiles.

**Comment by mstenz** [comment]
P.S.: The same happens when you completely delete a domain. The folders stay on the filesystem.

**Comment by RvdHout** [comment]
Your issue report is kinda poor, could you at least mention what hms version you are running?

Are you sure? I just checked on a server i adminitrate where i recently deleted a domain, eg: client moved away
I'm positive that folder is no longer exists in my /Data directory (and i didn't delete it manually)

Did you screw arround with permission?

**Comment by mstenz** [comment]
the version i am using is 5.7.0-B2495 (x64). 
There is no specific change on permissions, hmailserver anyhow runs with "Local System" user, so should have enough rights. As the files where deleted i also do not expect any permission issue.

**Comment by mstenz** [comment]
I have now recreated the domain + mailbox and deleted it again. there were no mails in as it was for sure empty. still alle the folders exist as they were before.

**Comment by SorenRR** [comment]
5.7.0-B2495 is over 1 year old. If this is Dravions fork you need to go here: https://github.com/Dravion/hmailserver

**Comment by mstenz** [comment]
there does not exist any newer hmailserver production version than that iam using. i am using a compiled version that allows installation on Windows Server 2018, but it is running on Server 2016 now already. because there is no other change I think the issue must be here as well.

**Comment by RvdHout** [comment]
There is **no** production for 5.7!!!
I just tested this on my own private server that is running the latest 5.7 **ALPHA** release...

Created domain, created account, send a test mail -> Folder(s) got created
Next, Delete domain -> Everything was deleted

**Comment by mstenz** [comment]
I would install the latest version from build if that would help: 
https://build.hmailserver.com/viewLog.html?buildId=1230&buildTypeId=HMailServer_BuildHMailServer57&tab=buildChangesDiv
is that a good version to use?

**Comment by RvdHout** [comment]
Yup, 5.7.0-B2556 is what i am running
But it's unlikely that would solve you issue as nothing 'big' is changed since 5.7.0-B2495 as far as i know.... 

I would investigate permissions, AV blocking deletion and not sure if it is even possible but maybe connected client(s) blocking deletion?

**Comment by mstenz** [comment]
I have installed this version and with this it is working.

**Comment by RvdHout** [comment]
Lucky you 👍
