### ISSUE TITLE
MX resolve CName only

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#371]
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=36270

NSLookup on same machine works, but hMailserver 5.7 b2556 won't deliver to domains with only CNAME

Some examples in thread include 'bohemia-znak.cz'

**Comment by RvdHout** [comment]
Addendum

**Symptom:**  hMailServer 5.7.x doesn't resolve MX records that contain a CNAME record

https://www.rfc-editor.org/rfc/rfc2181.txt
```
10.3. MX and NS records

The domain name used as the value of a NS resource record, or part of
the value of a **MX resource record must not be an alias.** Not only is
the specification clear on this point, but using an alias in either
of these positions neither works as well as might be hoped, nor well
fulfills the ambition that may have led to this approach. This
domain name must have as its value one or more address records.
Currently those will be A records, however in the future other record
types giving addressing information may be acceptable. It can also
have other RRs, **but never a CNAME RR**.
```

According the RFC this behavior is absolutely fine, but the practical side learns us that quite a few sysadmins don't follow this RFC and do use CNAME records as MX records.
hMailServer 5.6.x resolves MX records that contain CNAME records without issues

@martinknafve 
If you agree to ignore the RFC like the 5.6.x branch does, it think 2 places need attention

DNSResolver::GetEmailServers() should call: 
GetIpAddresses(sDomainName, a_records, true) apposed to GetIpAddresses(sDomainName, a_records, false) it currently does 2x, [L188](https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/Common/TCPIP/DNSResolver.cpp#L188) and [L224](https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/Common/TCPIP/DNSResolver.cpp#L224)

DNSResolver::GetMXRecords() need a bit more work, eg: similar to DNSResolver::GetTXTRecords() and DNSResolver::GetTXTRecordsRecursive_()

**Comment by martinknafve** [comment]
Fixed
