### ISSUE TITLE
DKIM Signing Not Performed On Messages > 10 MB

### ISSUE THREAD

**Issue by bobdig** [hmailserver/hmailserver#387]
There is a File Size limit of 10MB for DKIM signing according to this [forum thread](https://www.hmailserver.com/forum/viewtopic.php?f=7&t=37151).

**Comment by martinknafve** [comment]
The limit exists to prevent out-of-memory issues. The implementation is not so efficient. I've increased the limit from 10 to 50MB. hMailServer 5.7 is 64 bit so it should not be an issue there.
