### ISSUE TITLE
Cant install without internet

### ISSUE THREAD

**Issue by Dariusz1989** [hmailserver/hmailserver#388]
Hey

Im setting it up on my local network to help with diagnostic services(freenas/etc) But I cant install it on vm that has no internet access.

Would it be possible to get the intaller tweaked to allow us to skip the net framework 2.0 requirement/etc?

TIA

**Comment by RvdHout** [comment]
Install .Net 3.5 first on the VM trough the Windows control panel, Turn Windows features on or off

**Comment by Dariusz1989** [comment]
@RvdHout mmm I tried enabling it, but windows want to connect to the internet to download missing stuff. I also tried manually installing 3.5/ 4.x etc but they said a never version is installed and I cant do it.

**Comment by RvdHout** [comment]
Fix internet :) 
You gonna need internet anyway....what use will a mailserver have without internet?

**Comment by Dariusz1989** [comment]
@RvdHout well no, its for local network & services. Like truenas that is on offline network... Entire network is fully offline. 
I take I'm the only one in the world that needs this "ignore" checkbox then ^^

**Comment by RvdHout** [comment]
Or install latest 5.7 artifact from https://build.hmailserver.com/login.html (login as guest)
Note: this is 64-bit

**Comment by Dariusz1989** [comment]
@RvdHout worked like charm! Thank you lots!!!
