### ISSUE TITLE
Vulnerable if the sender mail address is longer than 255 characters?

### ISSUE THREAD

**Issue by helptiger** [hmailserver/hmailserver#393]
Spammers have a hard time if the sender mail address is longer than 255 characters. hMailserver then throws the following error message, for example:

"ERROR"	3180	"2021-08-31 17:49:09.878"	"Severity: 2 (High), Code: HM5032, Source: DALConnection::Execute, Description: MySQL: Data too long for column 'messagefrom' at row 1 (Additional info: INSERT INTO hm_messages (messageaccountid, messagefilename, messagetype, messagefrom, messagesize, messageflags, messagefolderid, messageuid, messagelocked, messagecreatetime, messagecurnooftries, messagenexttrytime) VALUES (0, '{B2A22FAB-A1AF-4CC8-ADA6-676CDCAE616D}.eml', 1, 'prvs=08774653b8=reply+6UE4F6x6Z499Q5p5SmRUsQrm66pbe1vSm6jP35xfemSO564ZK9361v89r722RuX300X3bcu62k8XGOwvk3WGxZ75Zslr63sAV6QOfB6skk4a78Xrznr9ihS489ucJ3895l5jyrv3223p4700ZNpXC6prROJ6UiKVj46r1kvE5Qw23cH9gQ4x4H5MawHlFCYow6N92880wIBiMNL5m771Mr9HzlI6g1PD32SjV22vYcvg19jN2210tB1Ju3e4SAW83LkEhKd150HTf2Z21boy020weffY8u63AqVvRYTK12pM@slim.lirelivre.info', 521552, 96, 0, 0, 1, '2021-08-31 17:49:09', 0, '1901-01-01'))"

Does this make hmailserver vulnerable?

**Comment by RvdHout** [comment]
vulnerable to what exactly?

**Comment by helptiger** [comment]
Is it perhaps conceivable that mails sent with such a long address cause the hard disk to overflow and crash the server? Mails do not appear because they are not recorded in the database, but are stored on the hard disk? Do they end up as data corpses?

**Comment by helptiger** [comment]
I have searched the hard disk and found no mail file that led to the error message. I assume that a mail with a correspondingly long sender is not processed at all. Is that correct?

**Comment by martinknafve** [comment]
I have added validation so that emails are rejected if the recipient address is more than 254 characters.
