### ISSUE TITLE
Support für mordern authentication

### ISSUE THREAD

**Issue by alie2n** [hmailserver/hmailserver#394]
Hi,
according to [this article](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-september-2021-update/ba-p/2772210) delivering mails to Exchange online will not be possible within the next year.
If using a tenant with mandatory mfa using smtp basic auth is already not possible anymore.
It would be great if hmailserver would implement the so called modern authentication.

**Comment by mstenz** [comment]
This is only for user-based communication. server/SMTP-based communication is still unchanged. I don't think there is any change required in hmailserver because it is not an email client.

**Comment by martinknafve** [comment]
Yes. Exchange Online wouldn't know if/how users have authenticated when the message was delivered to hMailServer using SMTP. So there's no way they could block email based on that.

**Comment by alie2n** [comment]
I think you misunderstood the main reason for this issue.
When trying to use Exchange Online as relay for hmailserver you need to authenticate to relay mails. After enabling multi factor authentication (which already is the default for new tenants and cannot not be turned of) I found no way to authenticate.

The only way would be support modern authentication.
