### ISSUE TITLE
Diagnostics Issue

### ISSUE THREAD

**Issue by RvdHout** [hmailserver/hmailserver#397]
@martinknafve 

Found a quirk in diagnostics

```
Test: Server details
hMailServer version: 5.7.0-B2576
Version architecture: x64
Processor architecture: x86
Logical processors: 4
System memory: 16229 MB
Database type: MySQL
```

Processor architecture x86 is wrong, it might be using a x86 instruction set, but in this instance (Intel Celeron J3455 of my NUC system @home) it is a fact it is a x64 processor, running Windows server 2019 (64-bit)

This check seems to be the culprit 
https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/Common/Diagnostics/TestInformationGatherer.cpp#L45-L56

**Comment by RvdHout** [comment]
Is this a easy as to swap the values around or is there more to it

```
      switch (system_info.wProcessorArchitecture)
      {
      case PROCESSOR_ARCHITECTURE_INTEL:
         processor_architecture = "x86";
         break;
      case PROCESSOR_ARCHITECTURE_AMD64:
      case PROCESSOR_ARCHITECTURE_IA64:
         processor_architecture = "x64";
         break;
      default:
         processor_architecture = "Unknown";
      }
```

**Comment by RvdHout** [comment]
> Is this a easy as to swap the values around or is there more to it?
✔️

**Comment by martinknafve** [comment]
I'm wondering if it wouldn't make more sense to just remove this diagnostics output? hMailServer 5.7 is always x64 and won't run on 32-bit processors. So logging that it is x64 bit build on x64 bit processor seems a bit redundant with the version number, do you agree?

**Comment by RvdHout** [comment]
Agreed

**Comment by martinknafve** [comment]
I removed the meaningless information.
