### ISSUE TITLE
Installer does no longer work

### ISSUE THREAD

**Issue by AyrA** [hmailserver/hmailserver#400]
When it tries to download .NET 2.0 it gives this error which can't be skipped:

    Error sending request.
    A redirect request will change a non-secure to a secure connection

The URL of where the framework is downloaded might has expired and returns 404.

URL found here: https://github.com/hmailserver/hmailserver/blob/master/hmailserver/installation/hMailServerInnoExtension.iss#L64

**Comment by martinknafve** [comment]
You can install .NET Framework manually before running the installer. The upcoming version 5.7 is using a newer version of .NET Framework.
