### ISSUE TITLE
SessionID in client properties

### ISSUE THREAD

**Issue by RvdHout** [hmailserver/hmailserver#401]
@martinknafve 

I utilize some custom logging for various events, sometimes i have a hard time matching those log entries in my custom logs with the one in the main hmailserver log. Would it be somehow possible to have the TCPConnection's SessionId added to the oClient properties? Every TCPConnection gets a unique SessionID, right? 

This way the SessionID property can be used to match the main hmailserver log to lookup/find corresponding log entries 

eg: something like this: 
oClient.IPAddress
oClient.Port
oClient.HELO
oClient.Username
**oClient.SessionID**

I noticed oClient.IPAddress & oClient.Port are set inside TCPServer.cpp and SessionID is created in TCPConnection.cpp but I have a hard time figuring out how I could use that SessionID as client property in TCPServer.cpp in OnClientConnect

**Comment by SorenRR** [comment]
@RvdHout 

Have a look at this ... https://www.hmailserver.com/forum/viewtopic.php?f=10&t=33787&hilit=threadid

**Comment by RvdHout** [comment]
But that ThreadId isn't the same as the TCPConnection SessionID, is it? And ThreadId  is not necessarily unique 

`
"SMTPD"	2572	491	"2019-04-10 03:06:04.117"	"204.232.178.184"	"SENT: 220 mx.acme.inc ESMTP"
"SMTPD"	2572	491	"2019-04-10 03:06:04.445"	"204.232.178.184"	"RECEIVED: EHLO web1.valentus.com"
"SMTPD"	2572	491	"2019-04-10 03:06:24.100"	"204.232.178.184"	"SENT: 250-mx.acme.inc[nl]250 SIZE"
"SMTPD"	2572	491	"2019-04-10 03:06:24.225"	"204.232.178.184"	"RECEIVED: MAIL FROM:<support@valentus.com>"
"SMTPD"	2572	491	"2019-04-10 03:06:24.225"	"204.232.178.184"	"SENT: 250 OK"
"SMTPD"	2572	491	"2019-04-10 03:06:24.335"	"204.232.178.184"	"RECEIVED: RCPT TO:<road.runner@acme.inc>"
"SMTPD"	2572	0	"2019-04-10 03:06:24.397"	"TCP"	"DNS lookup: 184.178.232.204.zen.spamhaus.org, 0 addresses found: (none), Match: False"
"SMTPD"	2572	0	"2019-04-10 03:06:24.757"	"TCP"	"DNS lookup: 184.178.232.204.b.barracudacentral.org, 0 addresses found: (none), Match: False"
"SMTPD"	2572	0	"2019-04-10 03:06:24.913"	"TCP"	"DNS lookup: 184.178.232.204.bl.spamcop.net, 0 addresses found: (none), Match: False"
"SMTPD"	2572	491	"2019-04-10 03:06:24.913"	"204.232.178.184"	"SENT: 250 OK"
"SMTPD"	2572	491	"2019-04-10 03:06:25.022"	"204.232.178.184"	"RECEIVED: DATA"
"SMTPD"	2572	491	"2019-04-10 03:06:45.162"	"204.232.178.184"	"SENT: 354 OK, send."
200		"2019-04-10 03:06:49.693"	"IDS Delete     	204.232.178.184"
"SMTPD"	200	491	"2019-04-10 03:06:49.756"	"204.232.178.184"	"SENT: 250 Queued (4.515 seconds)"
"SMTPD"	1176	491	"2019-04-10 03:06:49.881"	"204.232.178.184"	"RECEIVED: QUIT"
"SMTPD"	1176	491	"2019-04-10 03:06:49.881"	"204.232.178.184"	"SENT: 221 goodbye"
`

If i get it right, ThreadId  = 200 in above example?
But i would like SessionId = 491 (eg: the SessionID of the whole TCPConnection

**Comment by SorenRR** [comment]
I did play around with SessionID a couple of years back, can't remember why I abandoned it but it was also oApp.Status.<thingy> ... Using oApp.Status.<thingy> enables you use it even if no oClient is available in the script.

**Comment by RvdHout** [comment]
Doubt oApp.Status can do anything useful with SessionID (Other then displaying total sessions), as that session is (pre-)created per TCP connection

**Comment by RvdHout** [comment]
TCPServer.h

```
      bool FireOnAcceptEvent(std::shared_ptr<TCPConnection> connection, const IPAddress& remoteAddress, int port);
      //bool FireOnAcceptEvent(const IPAddress &remoteAddress, int port);
```

TCPServer.cpp
```
   bool
   //TCPServer::FireOnAcceptEvent(const IPAddress &remoteAddress, int port)
   TCPServer::FireOnAcceptEvent(std::shared_ptr<TCPConnection> connection, const IPAddress& remoteAddress, int port)
   {
      // Fire an event...
      if (!Configuration::Instance()->GetUseScriptServer())
         return true;

      std::shared_ptr<ClientInfo> pCliInfo = std::shared_ptr<ClientInfo>(new ClientInfo);
      pCliInfo->SetIPAddress(remoteAddress.ToString());
      pCliInfo->SetPort(port);
      pCliInfo->SetSessionId(connection->GetSessionID());

      std::shared_ptr<ScriptObjectContainer> pContainer = std::shared_ptr<ScriptObjectContainer>(new ScriptObjectContainer);
      std::shared_ptr<Result> pResult = std::shared_ptr<Result>(new Result);

      pContainer->AddObject("Result", pResult, ScriptObject::OTResult);
      pContainer->AddObject("HMAILSERVER_CLIENT", pCliInfo, ScriptObject::OTClient);

      String sEventCaller;

      String sScriptLanguage = Configuration::Instance()->GetScriptLanguage();

      if (sScriptLanguage == _T("VBScript"))
         sEventCaller.Format(_T("OnClientConnect(HMAILSERVER_CLIENT)"));
      else if (sScriptLanguage == _T("JScript"))
         sEventCaller.Format(_T("OnClientConnect(HMAILSERVER_CLIENT);"));

      ScriptServer::Instance()->FireEvent(ScriptServer::EventOnClientConnect, sEventCaller, pContainer);

      switch (pResult->GetValue())
      {
      case 1:
         {
            // Disconnect the socket immediately.
            return false;
         }
      }

      return true;
   }
```

TCPConnection.h
```
   public:
      ...

      int GetSessionID();

   protected:

      ConnectionState GetConnectionState() { return connection_state_;  }
      //int GetSessionID();
```

**Comment by RvdHout** [comment]
@martinknafve, anything wrong with toggling public/private definition for int GetSessionID();?
Or did I approach this all wrong?

**Comment by martinknafve** [comment]
I skimmed the changes and it looks OK to me. There's nothing wrong with changing it from protected to public. Only reason it was protected was because there previously was no need to call it from outside.

You can create a pull request for your commit and I could merge it to master, if you want to.

**Comment by RvdHout** [comment]
I could do that i think...one question though

Can you successfully merge, when for example a pull request interferes with a previous pull request (you wan't me to use master branch to create pull, right?)

In this example for instance the changes in hMailServer.idl propget numbering uses:

`[propget, id(10), helpstring("The assigned SessionID for the TCP/IP connection.")] HRESULT SessionID([out, retval] LONG* pVal);`

This is the result of this being added after previous pull request for https://github.com/hmailserver/hmailserver/pull/391
eg: https://github.com/hmailserver/hmailserver/pull/391/commits/bc4c0ebafde4264883153c982720c7fac0c7d1db#diff-75d87c61c535a79588c449b7b5737250faab52947bb22c21b9d17ee6a16897a6R1596-R1599

**Comment by gotspatel** [comment]
If possible, can you please give an example usage of "oClient.SessionID"

and Thank you very much for oApp.Status.ThreadID

**Comment by RvdHout** [comment]
@gotspatel 

I use it with some custom logging (LogWriter vbscript class by @SorenRR) 

```
'******************************************************************************************************************************
'********** Classes                                                                                                  **********
'******************************************************************************************************************************

Class LogWriter
   Private m_oApp, m_LogID, m_LogFile, m_LogType, m_LogDir, m_LogSessionID
   Private i, t, temp, strDay, strMonth, strTime, strLogFile, strLogDate

   Private Sub Class_Initialize()
      Set m_oApp = CreateObject("hMailServer.Application")
      Call m_oApp.Authenticate(HMUSER, HMPASSWORD)
      m_LogFile = "LogWriter"
      m_LogType = "M"
      m_LogDir = m_oApp.Settings.Directories.LogDirectory
      REM m_LogID = Cstr(m_oApp.Status.ProcessedMessages)
	  m_LogID = Cstr(m_oApp.Status.ThreadID)
	  m_LogSessionID = Empty
   End Sub

   Private Sub Class_Terminate()
      '
      '   Termination code goes here.
      '
   End Sub

   Public Property Let LogFile(strFile)
      m_LogFile = Trim(strFile)
   End Property

   Public Property Let LogDir(strDir)
      If (Right(strDir, 1) = "\") Then
         m_LogDir = Trim(Left(strDir, Len(strDir) - 1))
      Else
         m_LogDir = Trim(strDir)
      End If
   End Property

   Public Property Let LogType(strType)
      m_LogType = Trim(strType)
   End Property
   
   Public Property Let LogSessionId(iSessionId)
      m_LogSessionID = Cstr(iSessionId)
   End Property

   Public Function Wait(sec)
      With CreateObject("WScript.Shell")
         .Run "timeout /T " & Int(sec), 0, True       ' Windows 7/2003/2008 or later
'        .Run "sleep -m " & Int(sec * 1000), 0, True  ' Windows 2003 Resource Kit
'        .Run "powershell Start-Sleep -Milliseconds " & Int(sec * 1000), 0, True
      End With
   End Function

   Public Function OpenFile(strPath)
      Const Append = 8
      Const Unicode = -1
      With CreateObject("Scripting.FileSystemObject")
         Dim oFile
         For i = 0 To 30
            On Error Resume Next
            Set oFile = .OpenTextFile(strPath, Append, True, Unicode)
            If Not (Err.Number = 70) Then
               Set OpenFile = oFile
               On Error Goto 0
               Exit For
            End If
            On Error Goto 0
            Wait(1)
         Next
      End With
      If (Err.Number = 70) Then
         ' EventLog.Write( "ERROR: VBScript Class LogWriter" )
         ' EventLog.Write( "File " & strPath & " is locked and timeout was exceeded." )
         Err.Clear
      ElseIf (Err.Number <> 0) Then
         ' EventLog.Write( "ERROR: VBScript Class LogWriter : Function OpenFile" )
         ' EventLog.Write( "Error       : " & Err.Number )
         ' EventLog.Write( "Error (hex) : 0x" & Hex(Err.Number) )
         ' EventLog.Write( "Source      : " & Err.Source )
         ' EventLog.Write( "Description : " & Err.Description )
         Err.Clear
      End If
   End Function

   Public Function Write(strText)
      t = Timer
      temp = Int(t)
      strMonth = DatePart("yyyy",Date) & "-" & Right("0" & DatePart("m",Date), 2)
      strDay = strMonth & "-" & Right("0" & DatePart("d",Date), 2)
      strTime = Right("0"  & Hour(Now),   2) & ":" &_
                Right("0"  & Minute(Now), 2) & ":" &_
                Right("0"  & Second(Now), 2) & "." &_
                Right("00" & (Int((t-temp) * 1000)), 3)
      strLogDate = strDay & " " & strTime
      If (m_LogType = "M") Then
         strLogFile = m_LogDir & "\" & m_LogFile & "_" & strMonth & ".log"
      Else
         strLogFile = m_LogDir & "\" & m_LogFile & "_" & strDay & ".log"
      End If
      With OpenFile(strLogFile)
		If (IsEmpty(m_LogSessionID)) Then
			.WriteLine(m_LogID & vbTab & Chr(34) & strLogDate & Chr(34) & vbTab & Chr(34) & strText & Chr(34))
		Else
			.WriteLine(m_LogID & vbTab & m_LogSessionID & vbTab & Chr(34) & strLogDate & Chr(34) & vbTab & Chr(34) & strText & Chr(34))
		End If
         .Close
      End With
      Write = Err.Number
   End Function

End Class
```

Example

```
Dim EventLogX : Set EventLogX = New LogWriter
EventLogX.LogFile = "OnHELO"
EventLogX.LogSessionId = oClient.SessionID
EventLogX.Write(RPad("OnHELO" & Chr(34), 8, " ") & vbTab & Chr(34) & "IPAddress = " & oClient.IPAddress )
EventLogX.Write(RPad("OnHELO" & Chr(34), 8, " ") & vbTab & Chr(34) & "HELO = " & oClient.HELO )
Set EventLogX = Nothing

Function LPad(StringToPad, Length, CharacterToPad)
  Dim x : x = 0
  If Length > Len(StringToPad) Then x = Length - len(StringToPad)
  LPad = String(x, CharacterToPad) & StringToPad
End Function

Function RPad(StringToPad, Length, CharacterToPad)
  Dim x : x = 0
  If Length > Len(StringToPad) Then x = Length - len(StringToPad)
  RPad = StringToPad & String(x, CharacterToPad)
End Function

```
