### ISSUE TITLE
hMailServer 5.7 Crash

### ISSUE THREAD

**Issue by chmichael** [hmailserver/hmailserver#404]
Hello,
  Attached the logs & minidump

btw, the Service will crash and doesn't restart. Please consider a watchdog for such cases.

**Comment by martinknafve** [comment]
What build are you on?

I removed your logs, since you probably don't want to disclose the email addresses here. 

You can configure the Windows service to automatically restart on errors. Not sure why an additional watchdog is needed?

**Comment by chmichael** [comment]
Was the latest 5.7 build. Now i reverted back to 5.6 due the this crash.

Can you add the settings to restart the service by default on the install script ?

Thank you

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, this won't be addressed. If you come up with a reproducible scenario for 5.7 then please add that and we can re-open the issue. We won't change the service installation behavior.
