### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [hmailserver/hmailserver#405]
It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by martinknafve** [comment]
This is done.

**Comment by Neustradamus** [comment]
@martinknafve: Excellent, a good change!

Now you can change your visibility to public:
- https://github.com/orgs/hmailserver/people

**Comment by Neustradamus** [comment]
In the organization, you can add the logo, a description, the website...

You can pin this repository.

In all repositories, at right, you can click on the gear and add description, topics, enable or disable options...

You can add a repository hmailserver.github.io for the website and it will be hmailserver.com.

Note: The forum needs to be forum.hmailserver.com and not hosted on GitHub.

You can:
- Send an email to request new developers
- Create a ticket to request new developers and pin this ticket
- Create a post to request new developers on the forum

The future starts today.
