### ISSUE TITLE
dds error in 5.7

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#408]
I don't use DDS very often, it's probably been a couple of years

Went to use it today, and after it looks like it is completed it gave this error
<img width="314" alt="image" src="https://user-images.githubusercontent.com/7231493/149248479-0324591e-e919-45d8-a4b4-4d98b28388d5.png">

Interestingly, and repeatable on all use, it also crashed my hMailadmin.exe and restarted the message counters (made the hmailserver.exe restart)

I've been getting hMailserver.exe restarts randomly every couple of days for ages, and each time the hMailAdmin crashes.

**Comment by martinknafve** [comment]
Are there any errors logs generated in the `C:\Program Files (x86)\hMailServer\Logs` folder?

**Comment by OutbackMatt** [comment]
No logs, no mini-dumps created

Playing a bit more with this, I may have it backwards
The DDS has worked a couple of times (single domains) this morning and failed a couple of times (all domains)
Last week it failed on both, although the 'all domains' failures today were both on the exact same folder.

Perhaps the error in DDS is due to the the hmailserver.exe (service) failing, and not causing the service to fail

(The service fails every day or so normally for me - still trying to work out why)

**Comment by OutbackMatt** [comment]
And today (Sunday morning - should be quiet time) every time I use DDS it crashes hMailserver without error logs being created, without minidump.

When I thought that the DDS worker the other day, what I meant was it didn't crash, and it didn't error, but it also didn't bring up any visual acuity to say  'completed'  - and certainly messages that I was expecting to be imported were not...

**Comment by OutbackMatt** [comment]
Found that I had done this >> https://www.hmailserver.com/forum/viewtopic.php?f=21&t=29828
Many years ago

Removing that index from the database and it seems to work fine, in that it runs though and shows completed at the end

I'm still checking to see if the massages get added as expect

**Comment by RvdHout** [comment]
@OutbackMatt 

As it seem you had a double index on the same table property this is considered solved, not?
Please close...
