### ISSUE TITLE
Improvements of organization and repositories

### ISSUE THREAD

**Issue by Neustradamus** [hmailserver/hmailserver#409]
Dear @martinknafve,

To do improvements:

In the organization, you can add the logo, a description, the website...

You can pin this repository.

In all repositories, at right, you can click on the gear and add description, topics, enable or disable options...

You can add a repository hmailserver.github.io for the website and it will be hmailserver.com.

Note: The forum needs to be forum.hmailserver.com and not hosted on GitHub.

You can:
- Send an email to request new developers
- Create a ticket to request new developers and pin this ticket
- Create a post to request new developers on the forum

The future starts today.

**Comment by martinknafve** [comment]
This will not be implemented. I have no plans on migrating the website over to github. Thanks.

**Comment by Neustradamus** [comment]
@martinknafve: You have not read the ticket.

I will create a new ticket.

**Comment by Neustradamus** [comment]
@martinknafve: Done: https://github.com/hmailserver/hmailserver/issues/410.

Please read here and the new ticket, please read thanks.

Note: To win time, in the new ticket, I have remove (the less important part):
```
You can add a repository hmailserver.github.io for the website and it will be hmailserver.com.
Note: The forum needs to be forum.hmailserver.com and not hosted on GitHub.
```
