### ISSUE TITLE
Improvements of organization and repositories

### ISSUE THREAD

**Issue by Neustradamus** [hmailserver/hmailserver#410]
Dear @martinknafve,

To do improvements:

In the organization, you can add the logo, a description, the website...

You can pin this repository.

In all repositories, at right, you can click on the gear and add description, topics, enable or disable options...

You can:
- Send an email to request new developers
- Create a ticket to request new developers and pin this ticket
- Create a post to request new developers on the forum

The future starts today.

**Comment by martinknafve** [comment]
We have discussed this already. Please stop the spam.
