### ISSUE TITLE
hMailserver with Postgres DB

### ISSUE THREAD

**Issue by waltergrimmvie** [hmailserver/hmailserver#414]
I am trying to install hMailserver with Postgres.

I have checked and looked at multiple google links.

I just cannot connect to Postgres during hMailserver setup, it always requires authentication, which I am being told is supported.

Starting task...
Please wait while creating database...
authentication method 10 not supported

Does anyone please have an procedure to connect hMailserver to Postgres please

**Comment by RvdHout** [comment]
Maybe this can help you?
https://www.hmailserver.com/forum/viewtopic.php?f=21&t=31638&p=198543&hilit=Postgres#p198543

**Comment by waltergrimmvie** [comment]
thank you very much, yes tried this 5 times++ in now in the last few month, still getting the error abone 

The article is from 2017, I assume there are soem changes, most noteably the pg_hba.conf setting, scram-sha-256 instead of md5 as in the article

![image](https://user-images.githubusercontent.com/42313805/150685721-9761cb3e-b5a4-42dd-8cab-ce5e973739c1.png)

**Comment by RvdHout** [comment]
Not using Postgres myself, but if i read that topic right you **do not change it to md5** but into **password**

But if that is still possible nowadays?

**Comment by waltergrimmvie** [comment]
thanx for your help, 

this is the text from the article: (From md5 to password)

FROM:
host     all             all             127.0.0.1/32            md5
TO:
host     all             all             127.0.0.1/32            password

furthermore it says 
"# "local" is for Unix domain socket connections only"

I am using the Windows Postgres

BUT: I replaced "scram-sha-256" to  password for all rows in pg_hba.conf, and it worked now

**Comment by RvdHout** [comment]
Good the hear, enjoy!

**Comment by aligunesv** [comment]
Hello,
The link below is very helpful:
[https://www.hmailserver.com/forum/viewtopic.php?f=21&t=31638&p=198543&hilit=Postgres#p198543](https://www.hmailserver.com/forum/viewtopic.php?f=21&t=31638&p=198543&hilit=Postgres#p198543)

However, if you encounter an error like this:
_"connect to PostgreSQL server: FATAL: no pg_hba.conf entry for host"_

You can fix it by changing the following line in your **pg_hba.conf** file:

From this:

`host    all         all         all             md5`

To this:

```
host    all         all         127.0.0.1/32    password
host    all         all         all             password
```

I’m sharing this in case someone else faces the same issue I did. Hopefully, this will help others to solve it more easily.
