### ISSUE TITLE
hMailServer future

### ISSUE THREAD

**Issue by Neustradamus** [hmailserver/hmailserver#417]
Dear @martinknafve,

I think it is needed to pin this issue :)

To link to the forum posts:
- https://www.hmailserver.com/forum/viewtopic.php?f=10&t=38161
- https://www.hmailserver.com/forum/viewtopic.php?f=8&t=38160

I am happy to have awakened the dormant project and allowed a revival.

Information to all, I am not a bot.

**Comment by martinknafve** [comment]
Pinned an issue with this info.
