### ISSUE TITLE
Upgrade to #2586 DB Version 5702 failed on MariaDB (MySql)

### ISSUE THREAD

**Issue by helptiger** [hmailserver/hmailserver#418]
The upgrade to the newer version did not run without errors. The SQL changes were not entered in the MariaDB database. After 2 attempts I started the SQL script manually and then it worked.
So it has to be checked if this is generally the case with MySql. Previous version was #2585.

`"ERROR"	4300	"2022-01-31 10:58:28.231"	"Severity: 1 (Critical), Code: HM5011, Source: Application::OnDatabaseConnected, Description: The database is too old for this version of hMailServer. Please run hMailServer Database updater (DBUpdater.exe) to upgrade it. Database version: 5700, Required database version: 5702"
"ERROR"	4620	"2022-01-31 11:01:44.491"	"Severity: 1 (Critical), Code: HM5011, Source: Application::OnDatabaseConnected, Description: The database is too old for this version of hMailServer. Please run hMailServer Database updater (DBUpdater.exe) to upgrade it. Database version: 5700, Required database version: 5702"
"ERROR"	1344	"2022-01-31 11:07:41.432"	"Severity: 3 (Medium), Code: HM5015, Source: PropertySet::GetProperty_(), Description: The property ascheckptr could not be found."
"ERROR"	1344	"2022-01-31 11:07:41.438"	"Severity: 3 (Medium), Code: HM5015, Source: PropertySet::GetProperty_(), Description: The property ascheckptrscore could not be found."
`

**Comment by OutbackMatt** [comment]
Same issue on MySQL

**Comment by helptiger** [comment]
> 
Please try the script without the spaces.

![Bildschirmfoto 2022-01-31 um 12 01](https://user-images.githubusercontent.com/10258902/151782740-e54959b0-b9ad-4efb-a018-13a33b58b376.jpg)

**Comment by OutbackMatt** [comment]
OK did that, ran the DBUpdater, and then restarted the hMailserver  Windows service, and it all looks good

**Comment by helptiger** [comment]
> OK did that, ran the DBUpdater, and then restarted the hMailserver Windows service, and it all looks good

To be sure, you can still check if the two new entries are present in the hm_settings table. Otherwise changes to the new entries will not be saved. I also had it, that the version was changed to 5702, but the entries were not there. Therefore I came to the solution with the spaces.

**Comment by OutbackMatt** [comment]
Yes, both new settings are in the database

The GUI included the new setting, and I've enabled it, and it is being logged under 'debug'

**Comment by RvdHout** [comment]
Strange, the initial database creation script and all other update script include those spaces

**Comment by helptiger** [comment]
@RvdHout 
I also find it a bit confusing and inconsistent. Normally I always use a space after the comma.
In this case it only works without a space, why remains to be clarified.

btw -> Thanks for the new features!

**Comment by helptiger** [comment]
For testing, I have once again reset the DB to version 5700. After requesting the hmailserver password, a window appears with the message "Upgrade path not found. Please contact support".An upgrade via dbupdater is not possible at the moment with MariaDB and probably MySql.

![Bildschirmfoto 2022-01-31 um 16 56](https://user-images.githubusercontent.com/10258902/151829406-b4c336cc-1062-418d-9457-cf293c4f879f.jpg)

**Comment by RvdHout** [comment]
@helptiger 

I found some missing instructions needed for the dbupdater to work correctly, should be fixed in next build

**Comment by martinknafve** [comment]
This fix is now included in the latest 5.7.0 build.
