### ISSUE TITLE
ClamAV via TCP is not working after Update to 0.104

### ISSUE THREAD

**Issue by LordDragonus** [hmailserver/hmailserver#420]
If using ClamAV via TCP with version 0.104 or higher, hMailServer shows Message Box with „UNKNOWN COMMAND“.

This is because hMailServer is using the command "STREAM" as shown here https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/Common/AntiVirus/ClamAVVirusScanner.cpp#L64
It was deprecated and has been deleted now. The right command should be "INSTREAM" now, as shown in the manpage: https://manpages.debian.org/testing/clamav-daemon/clamd.8.en.html

Forum thread: https://www.hmailserver.com/forum/viewtopic.php?f=7&t=37507

**Comment by RvdHout** [comment]
Hello @LordDragonus 

When was this deprecated? With version 0.103.x? 
The change should be fairly easy, but what to do with backward compatibility? Not everyone is (able to) use/using the latest version of ClamAV, many of us are still on 0.103.x or even older versions

**Comment by RvdHout** [comment]
I did some test, i can send the data to clamav using a single socket connection and inquiry the INSTREAM command but have trouble receiving data back using SynchronousConnection::ReadUntil(const AnsiString &delimiter, AnsiString &readData)

Not sure what i am missing here...

**Comment by SorenRR** [comment]
@RvdH you wrote earlier that you could send size and data but not receive reply... Well, I have trouble converting to 4 byte big endian (probably b.c. I haven't "broken the code yet") BUT... In 5.6.8 I made these changes and I DO read the reply from ClamAV...  Join forces?

https://github.com/SorenRR/hmailserver/commit/4deff1500c3f1f10273b570185e06c172bb97e24

**Comment by RvdHout** [comment]
@SorenRR 

I think you/we are completely on the wrong track, build a example project using the C# code posted at the forums and see the obvious difference with what we are doing

```
00000000  6E 49 4E 53 54 52 45 41  4D 0A 00 00 00 44 58 35   nINSTREA M....DX5 
00000010  4F 21 50 25 40 41 50 5B  34 5C 50 5A 58 35 34 28   O!P%@AP[ 4\PZX54( 
00000020  50 5E 29 37 43 43 29 37  7D 24 45 49 43 41 52 2D   P^)7CC)7 }$EICAR- 
00000030  53 54 41 4E 44 41 52 44  2D 41 4E 54 49 56 49 52   STANDARD -ANTIVIR 
00000040  55 53 2D 54 45 53 54 2D  46 49 4C 45 21 24 48 2B   US-TEST- FILE!$H+ 
00000050  48 2A 00 00 00 00                                  H*....
```

**Comment by RvdHout** [comment]
Thats explains the method, don't forget we are writing char arrays and not bytes, so eventually a complete rewrite is needed

**Comment by RvdHout** [comment]
chunksize = 22

```
00000000  6E 49 4E 53 54 52 45 41  4D 0A 00 00 00 16 58 35   nINSTREA M.....X5 
00000010  4F 21 50 25 40 41 50 5B  34 5C 50 5A 58 35 34 28   O!P%@AP[ 4\PZX54( 
00000020  50 5E 29 37 00 00 00 16  43 43 29 37 7D 24 45 49   P^)7.... CC)7}$EI 
00000030  43 41 52 2D 53 54 41 4E  44 41 52 44 2D 41 00 00   CAR-STAN DARD-A.. 
00000040  00 16 4E 54 49 56 49 52  55 53 2D 54 45 53 54 2D   ..NTIVIR US-TEST- 
00000050  46 49 4C 45 21 24 48 2B  00 00 00 02 48 2A 00 00   FILE!$H+ ....H*.. 
00000060  00 00  
```

**Comment by SorenRR** [comment]
(https://github.com/SorenRR/hmailserver/commit/4a25bbbf29f2da0ed002f9de66888c72d8f5420e)

I still have a problem getting the right size of the chunk...

`"DEBUG"	2956	"2022-02-11 21:25:11.415"	"Connecting to ClamAV virus scanner..."
"DEBUG"	2956	"2022-02-11 21:25:11.415"	"Send the INSTREAM command."
"DEBUG"	2956	"2022-02-11 21:25:11.415"	"p #1) Send <length>(big endian, 4 bytes )"
"DEBUG"	2956	"2022-02-11 21:25:11.415"	"(loop #1) Send the chunk of data corresponding to the above length"
"DEBUG"	2956	"2022-02-11 21:25:11.415"	"Send a 0 - length block to mark end of stream"
"DEBUG"	2956	"2022-02-11 21:25:11.415"	"Get response"
"DEBUG"	2956	"2022-02-11 21:25:11.446"	"Got response: stream: OK"
"DEBUG"	2956	"2022-02-11 21:25:11.446"	"No virus detected: stream: OK"
"DEBUG"	2956	"2022-02-11 21:25:11.446"	"Connecting to ClamAV virus scanner..."
"DEBUG"	2956	"2022-02-11 21:25:11.446"	"Send the INSTREAM command."
"DEBUG"	2956	"2022-02-11 21:25:11.446"	"the chunk of data corresponding to the above length"
"DEBUG"	2956	"2022-02-11 21:25:11.446"	"(loop #1) Send the chunk of data corresponding to the above length"
"DEBUG"	2956	"2022-02-11 21:25:11.446"	"Send a 0 - length block to mark end of stream"
"DEBUG"	2956	"2022-02-11 21:25:11.446"	"Get response"
"DEBUG"	2956	"2022-02-11 21:25:11.462"	"Got response: stream: Eicar-Signature FOUND"
"DEBUG"	2956	"2022-02-11 21:25:11.462"	"Virus detected: Eicar-Signature"


Fri Feb 11 21:18:16 2022 -> SelfCheck: Database status OK.
Fri Feb 11 21:25:11 2022 -> instream(192.168.0.61@57146): OK
Fri Feb 11 21:25:11 2022 -> instream(192.168.0.61@57147): Eicar-Signature(62b97e1a78f740a95997f4b24f59ffd3:69) FOUND
`

**Comment by SorenRR** [comment]
Bloody hell... It works ;-)

Seems the size issue is only with the test function ?!?

`"DEBUG"	3844	"2022-02-11 23:42:27.432"	"Connecting to ClamAV virus scanner..."
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"Send the INSTREAM command."
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #1) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #1) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #2) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #2) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #3) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #3) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #4) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #4) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #5) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #5) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #6) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #6) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #7) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #7) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #8) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #8) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #9) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #9) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #10) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #10) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #11) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #11) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #12) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #12) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #13) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #13) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #14) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.432"	"(loop #14) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #15) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #15) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #16) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #16) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #17) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #17) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #18) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #18) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #19) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #19) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #20) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #20) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #21) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #21) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #22) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #22) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #23) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #23) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #24) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #24) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #25) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #25) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #26) Send <length>(big endian, 4 bytes) 4096"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #26) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #27) Send <length>(big endian, 4 bytes) 1827"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"(loop #27) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"Send a 0 - length block to mark end of stream"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"Get response"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"Got response: stream: OK"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"No virus detected: stream: OK"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"Applying rules"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"Performing local delivery"
"DEBUG"	3844	"2022-02-11 23:42:27.447"	"Applying rules"
"DEBUG"	3844	"2022-02-11 23:42:27.463"	"Saving message: {3423CB9C-8FD7-46A7-85B0-0B6326ED2AA3}.eml"
"DEBUG"	3844	"2022-02-11 23:42:27.463"	"Local delivery completed"`

**Comment by SorenRR** [comment]
Ok, I'm done spamming this issue... ;-)

`"DEBUG"	3844	"2022-02-12 00:07:07.080"	"Connecting to ClamAV virus scanner..."
"DEBUG"	3844	"2022-02-12 00:07:07.082"	"Send the INSTREAM command."
"DEBUG"	3844	"2022-02-12 00:07:07.083"	"(loop #1) Send <length>(big endian, 4 bytes) 1834"
"DEBUG"	3844	"2022-02-12 00:07:07.083"	"(loop #1) Send the chunk of data corresponding to the above length"
"DEBUG"	3844	"2022-02-12 00:07:07.083"	"Send a 0 - length block to mark end of stream"
"DEBUG"	3844	"2022-02-12 00:07:07.083"	"Get response"
"DEBUG"	3844	"2022-02-12 00:07:07.138"	"Got response: stream: Sanesecurity.Junk.55796.UNOFFICIAL FOUND"
"DEBUG"	3844	"2022-02-12 00:07:07.138"	"Virus detected: Sanesecurity.Junk.55796.UNOFFICIAL"
"DEBUG"	3844	"2022-02-12 00:07:07.139"	"Deleting message"
"DEBUG"	3844	"2022-02-12 00:07:07.146"	"Deleting message file."`

**Comment by RvdHout** [comment]
Got it working? Bit hard to read to log entries above... looks promising 👍

**Comment by RvdHout** [comment]
@SorenRR 
Got a issue with pBuf->GetSize() not being a int on 64-bit but size_t, so i cast it
`unsigned int sizeValue = htonl(static_cast<unsigned int>(pBuf->GetSize()));`

Got it working as well, slightly different approach though, still using htonl

```
   VirusScanningResult
   ClamAVVirusScanner::Scan(const String &hostName, int primaryPort, const String &sFilename)
   {
      TimeoutCalculator calculator;

      LOG_DEBUG("Connecting to ClamAV virus scanner...");
      SynchronousConnection socketConnection(calculator.Calculate(IniFileSettings::Instance()->GetClamMinTimeout(), IniFileSettings::Instance()->GetClamMaxTimeout()));
      if (!socketConnection.Connect(hostName, primaryPort))
         return VirusScanningResult("ClamAVVirusScanner::Scan", Formatter::Format("Unable to connect to ClamAV stream port at {0}:{1}.", hostName, primaryPort));

      if (!socketConnection.Write("nINSTREAM\n"))
         return VirusScanningResult("ClamAVVirusScanner::Scan", "Unable to write INSTREAM command.");

      // Send the file on the stream socket.
      File oFile;
      if (!oFile.Open(sFilename, File::OTReadOnly))
      {
         String sErrorMsg = Formatter::Format("Could not send file {0} via socket since it does not exist.", sFilename);
         return VirusScanningResult("ClamAVVirusScanner::Scan", sErrorMsg);
      }

      const int STREAM_BLOCK_SIZE = 4096;
      const int maxIterations = 100000;
      for (int i = 0; i < maxIterations; i++)
      {
         std::shared_ptr<ByteBuffer> pBuf = oFile.ReadChunk(STREAM_BLOCK_SIZE);

         if (pBuf->GetSize() == 0)
            break;

         unsigned int sizeValue = htonl(static_cast<unsigned int>(pBuf->GetSize()));
         char sizeStr[4];
         memcpy(sizeStr, &sizeValue, 4);

         // Send the request.
         if (!socketConnection.Write(to_string(sizeStr[0]) + to_string(sizeStr[1]) + to_string(sizeStr[2]) + to_string(sizeStr[3])))
            return VirusScanningResult("ClamAVVirusScanner::Scan", "Unable to write packet size to stream port.");

         if (!socketConnection.Write(*pBuf))
            return VirusScanningResult("ClamAVVirusScanner::Scan", "Unable to write packet data to stream port.");
      }

      unsigned int nullValue = 0;
      char nullStr[4];
      memcpy(nullStr, &nullValue, 4);
      
      if (!socketConnection.Write(to_string(nullStr[0]) + to_string(nullStr[1]) + to_string(nullStr[2]) + to_string(nullStr[3])))
         return VirusScanningResult("ClamAVVirusScanner::Scan", "Unable to write end of stream.");

      AnsiString readData;

      if (!socketConnection.ReadUntil("\n", readData))
         return VirusScanningResult("ClamAVVirusScanner::Scan", "Unable to read response (after streaming).");

      socketConnection.Close();

      readData.TrimRight("\n");

      // Parse the response and see if a virus was reported.
      try
      {
         const regex expression("^stream.*: (.*) FOUND$"); 
         cmatch what; 
         if(regex_match(readData.c_str(), what, expression)) 
         {
            LOG_DEBUG("Virus detected: " + what[1]);
            return VirusScanningResult(VirusScanningResult::VirusFound, String(what[1]));
         }
         else
         {
            LOG_DEBUG("No virus detected: " + readData);
            return VirusScanningResult(VirusScanningResult::NoVirusFound, Formatter::Format("Result: {0}", readData));
         }
      }
      catch (std::runtime_error &) // regex_match will throw runtime_error if regexp is too complex.
      {
         return VirusScanningResult("ClamAVVirusScanner::Scan", "Unable to parse regular expression.");
      }

      
   }
```

**Comment by RvdHout** [comment]
How would you overflow a fixed chunk size with a maximum length of 4096? 

You believe in the union myth? Read the comments under this post
https://stackoverflow.com/a/14873864

Don't get me wrong i really don't know what is best approach

**Comment by SorenRR** [comment]
Dunno... If I read stuff correctly this memcpy and union stuff is about reading the same bit of memory with different glasses (so to speak) so if I do this

`      union
      {
         std::uint32_t integer;
         unsigned char byte[4];
      } foo;`

should it not allocate 4 bytes either way?

**Comment by martinknafve** [comment]
The PR to fix this issue has been merged. Closing.
