### ISSUE TITLE
Unable to send email after Windows Server 2016 update KB5010359

### ISSUE THREAD

**Issue by caugner** [hmailserver/hmailserver#421]
We installed the monthly Windows updates (KB5010359) on our Windows Server 2016 running hMailServer, and afterwards our web application was no longer able to send emails through hMailServer. Reverting that Windows updates resolved the issue.

The German info page for that update mentions a known problem with regard to apps using the Microsoft .NET Framework: https://support.microsoft.com/de-de/topic/8-februar-2022-kb5010359-betriebssystem-build-14393-4946-e47d743b-9026-4390-bca6-5ad4ddb40ca8

As a workaround, they suggest upgrading .NET Framework manually (to 4.6.2 or later), and we seem to currently have 4.6.01586 installed.

However, we were wondering whether hMailServer does already use these newer versions of .NET, since the code still metnions .NET 2.0:

https://github.com/hmailserver/hmailserver/blob/74833dc91d83caf44071c68b89236e74dc1b747c/hmailserver/installation/Shared.iss#L28

**Comment by SorenRR** [comment]
DOTNET 2.0 is a minimum requirement due to support for Windows 2000.
I have successfully used hMailServer on my development station (Win10) and my test/backup server (Win2019) with only DOTNET 4.x installed.
