### ISSUE TITLE
REQ: SEARCH HEADER Message-Id database support

### ISSUE THREAD

**Issue by chmichael** [hmailserver/hmailserver#422]
Hello,
  emClient is using SEARCH HEADER Message-Id when you move the messages from folder to folder.
  Due the fact the everytime hMailServer is loading the eml to get the "Message-Id" this process is slow!
  Return from a database indexed field would be instant!
  
Forum:
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=38426

Thank you

**Comment by martinknafve** [comment]
Sorry, no such features will be added to hMailServer, due to lack of time.

(If someone wants to implement it they are free to do so and submit a pull request - if that arrives I'll consider reopening this)
