### ISSUE TITLE
Feature request: IMAP move extension

### ISSUE THREAD

**Issue by Seni1ix** [hmailserver/hmailserver#424]
Would if be possible to enhance the IMAP Protocol With the Move extension:

https://www.ietf.org/archive/id/draft-krecicki-imap-move-00.html

I have to move a large amount of mails around.
and se that there is a IMAP Move extension that would have greatly speed up and improved efficiency.

can this be implemented? 
ref: https://www.hmailserver.com/forum/viewtopic.php?f=2&t=38413

**Comment by martinknafve** [comment]
Sorry, no such features will be added to hMailServer, due to lack of time.

(If someone wants to implement it they are free to do so and submit a pull request - if that arrives I'll consider reopening this)
