### ISSUE TITLE
x64 build

### ISSUE THREAD

**Issue by chmichael** [hmailserver/hmailserver#426]
Hello,
  I've been using the x64 build of Dravion without any problems. (https://github.com/Dravion/hmailserver)
  So i don't see any reason not to create an official one for x64 5.6 build and not to wait when 5.7 will be ready!

Also the Dravion x64 is faster!

Thank you

**Comment by RvdHout** [comment]
Simply stick with Dravion's build then?
Doubt it is faster, as you can see in the release notes **absolutely nothing** is changed but yet you where stupid enough to install it

**Comment by chmichael** [comment]
> Simply stick with Dravion's 5.6.x x64 build then? 

Dravion release is just the official release with a couple libraries updated and compiled 64 bit.

I wonder what's your issue doing the same build on the official release or you think changing compiler to compile for 64-bit will break things ? (which it will not) Is it so hard to spend 5 seconds to change the compiler settings ? 

> Doubt it is faster, 

The cpu usage is lower compared to the office x86 so it's faster. 

> as you can see in the release notes **absolutely nothing** is changed but yet you where stupid enough to install it

I guess you didn't bother to check either his github or the hmailserver forum!
https://www.hmailserver.com/forum/viewtopic.php?f=10&t=38421

New build of hMailServer-5.6.8-B2574 code base (64-Bit)
Updates:
OpenSSL 1.1.1n
Boost 1.72.0
Innosetup 6.0
Required .NET vers min. 4.5 

> Not to mention Dravion never posted sources, he literally made a closed source project of a open source project...go figure!?

The sources are his the above github link!

Thank you

**Comment by RvdHout** [comment]
`*The Code for LTS build are taken from official hMailServer Github Repo, not Dravion/hmailserver repo!`
Maybe learn to read... fact is his code is not available, so there is no change this is merged easily into 5.6.x

So he updated some libraries, kudos to him....he proved he can repack a installer!!!
FYI it is actually OpenSSL 1.1.1m, OpenSSL 1.1.1n is only available for 1 day
Does updating innosetup change something?
Is using Boost 1.72.0 better then using Boost 1.70.0?
Older systems, running 5.6.x mostly have .NET 2.0/3.5 installed by default and .NET 4.5 has to be installed separately

**Comment by chmichael** [comment]
First of all you're agressive and i don't know why!

>Maybe learn to read... fact is his code is not available, so there is no chance this is merged easily into 5.6.x

Did you compile his code or you put this statement out of your head ? (i can be agreesive and impolite too)
Anybody can do what Dravion did and more if you have the time! It's open source!

> Does updating innosetup change something, does it improve hmailserver internal working in any way? 

Newer versions of libraries and software support newer operating systems, fix bugs, improve perfomance and add new things that you might want to use them or not. I always use the latest installer version in my own software regardless if i use any new feature of it.

You can keep the old doesn't really matter it's up to the developer!

> So he updated some libraries, kudos to him....he proved he can repack a installer!!! 
> Is using Boost 1.72.0 better then using Boost 1.70.0? 

Seems to me alot of fixes and new stuff (It's 1.78 now)
https://www.boost.org/users/history/ 

> Older systems, running 5.6.x mostly have .NET 2.0/3.5 installed by default and .NET 4.5 has to be installed separately (5.7 uses .NET 4.5 by default)

We're in 2022 and not in 2006! Net 4.5 is faster more optimized and supported on newer OS than net 2.5. .Net core is even better!
Windows 10 and Windows Server 2016 are the current least supported systen that any person or company should run and they both have 4.5 available as optional.

Conclusion ... 

If you don't care improve this very nice peace of software fine... 
If you don't believe that i'm using Dravion x64 build and it's using less CPU fine also.
I think now i understand why Dravion to fork it and he's trying to improve it!
We're in a 64-bit world now and not in 32-bit and you're so negative about improvents!

ps:
My point was a build with .NET 4.5 and x64 is better! It's not You vs Darvion!
I don't compare developers i just point that someone did it.

Every developer that want to contribute to any project should be welcome!

Thank you

**Comment by RvdHout** [comment]
If x64 support is the main issue for you, just use 5.7.x.... many of us do that (either as test but also some in production)
Boost 1.78.00 may contain fixes and improvements, but why break something that simply works and has none known vulnerabilities?

Fact is we have no idea what he put in the source code, his github repository does not contain a branch that represents the changes he claims he committed, take my word for it

And then you have this:
https://www.hmailserver.com/forum/viewtopic.php?f=8&t=38160

Also relevant, i think...

**Comment by chmichael** [comment]
> If x64 support and .NET 4.5 is the main issue for you, just use 5.7.x.... 

I did but the i had to revert back to 5.6.x due this issue: https://github.com/hmailserver/hmailserver/issues/404 

> many of us do that (either as test but also some in production) Boost 1.78.00 may contain fixes and improvements, but why 
> break something that simply works and has none known vulnerabilities? 
> Chances are it will most likely break compatibility sooner than it does fix compatibility.

I don't know if it will break something that why you have test builds to give a try!
Usually when the libraries contain breaking changes they write it on their release notes.

> Fact is we have no idea what he put in the source code, his [github repository](https://github.com/Dravion/hmailserver) 
> does not contain a branch that represents the changes he claims he committed in his so called LTS release 
> (either 5.6.8 x86 or x64), take my word for it. So if his intentions are to contribute to this project, why does he 
> keep his code private? Just think of it, OK?

Ok! i'll find some time to compile his source code in order to verify it ok ?

> And then you have this: https://www.hmailserver.com/forum/viewtopic.php?f=8&t=38160
> Also relevant, i think...

Thanks! I'll take a look!

Thank you

**Comment by RvdHout** [comment]
Do whatever you want, building your own or use a trustworthy source (5.7.x) with a decent userbase is always better then just download and install a version that claims to be working.

It is very easy to verify compare/branches against the original repository, hence therefor my claim there is no source available for the Dravion build 5.6.8 x86 or x64 holding the changes as advertised in the changelog for those so called LTS releases

**Comment by chmichael** [comment]
Hello,
1) Download Dravion 5.6.8 source.zip from github
2) Download Boost 1.72
3) Download OpenSSL 1.1.1n
4) Applied changes to Boost 1.72 in otder to work with VS 2022 - https://github.com/boostorg/build/issues/735
5) Builded Boost
6) Builded OpenSSL
7) Compiled 64 bit target

HmailServer 64-bit with Boost 1.72 compiled with VS 2022 Done!

ps:
the only error i got was the below which i commented: (i'm not a C++ expert)

Charaset.cpp
      //setNeedsEncoding.push_back("åäö");
      //setNeedsEncoding.push_back("ÅÄÖ");
      //setDoesNotNeedEncoding.push_back("Re: =?ISO-8859-1?Q?Reuni=E3o?= =?ISO-8859-1?Q?Reuni=E3o?=ÖABCD =?ISO-8859-1?Q?Reuni=E3o?= ABCD");

Conclusion ... 
1) The Dravion source.zip it's compiling so it's legit!
**2) hMailServer can be compile for 64-bit targets using the latest VS 2022 and with newer libraries/.NET framework!**

Tried to compiled with Boost 1.78 but it would require changes! (probably they changed some APIs)
Attached screenshot with proof!

Thank you

![hmailserver-darvion-x64](https://user-images.githubusercontent.com/13120950/158832800-b1f727d0-66b8-4d2a-b33a-ea9b9edbc930.jpg)

**Comment by RvdHout** [comment]
Feel free to keep replying, but i'm done with this BS

**Comment by chmichael** [comment]
> Why would you prefer a official 5.6.8 x64 build?

@martinknafve seems ot be active again!
 
> Or simply use the official 5.7.0 x64 build

As i noted in my earlier post it has a major bug that prevent me for using it -> https://github.com/hmailserver/hmailserver/issues/404

Thank you

**Comment by RvdHout** [comment]
He is not active again, what gave you that idea? 
you clearly did not read his forum announcement if you think a OpenSSL security fix is him being active again

#404 doesn't give much details, and only you seem to have that issue.... i know many that run 5.7 (either in production or alongside 5.6 as test) including myself without having crashes on 5.7, could it be your config?

**Comment by chmichael** [comment]
> He is not active again, what gave you that idea? you clearly did not read his forum announcement if you think a OpenSSL security fix is him being active again

I just saw his recent commits i'll check the forum! Thanks!

> #404 doesn't give much details, and only you seem to have that issue.... i know many that run 5.7 (either in production or alongside 5.6 as test) including myself without having crashes on 5.7, could it be your config?

The same config reverted back to 5.6.8 32-bit works without the service crash!
If you wish to provide you more details the issue is open! 

> I would not keep my hopes up for a 5.6.x x64 build....just saying!

Ok! Thank you for taking time to reply! :)

**Comment by RvdHout** [comment]
Did you try the latest [5.7 build](https://build.hmailserver.com/repository/download/HMailServer_BuildHMailServer57/1314:id/hMailServer-5.7.0-B2590-x64.exe)? 
**Note:** You have to use x64 build for libmysql.dll for this, and any other 32-bit component you might be using within your scripts (if any) Once again, no one else is having problems with 5.7 so it must be something on your end!

But finally the truth comes out, so you noticed the recent commits and you realized you are on back-foot now by using the Dravion release, eg: 5.6.8. vs 5.6.9....bad luck, you might have more success asking Dravion to update to 5.6.9

**Comment by chmichael** [comment]
> Did you try the latest [5.7 build]

Nope, the last 5.7 i used and had crashing was 2582. I only see Anti-spam fixes up to 2590 build!

> You have to use x64 build for libmysql.dll for this, and any other 32-bit component you might be using within your scripts (if > any) Once again, no one else is having problems with 5.7 so it must be something on your end!

How can it be at my end ? I've used it (5.7.2582 - connected to MySQL DB) on a production Windows 2016 Server essentials and it was the only thing crashing! Reverting back to latest stable 32-bit bit the no more crashes! How do you explain that because i really trying to understand the cause of the crash! If you have any tips please tell me!

Also hMailServer will not run with a 32bit libmysql.dll library so i'm using the 64-bit 6.1.11 of libmysql.dll.

I've installed the latest 5.7 build now on my PC ... let's see how it goes!

Thank you

**Comment by RvdHout** [comment]
> How can it be at my end ? 

Uh, let me think....maybe because you are the only one having issues with it?

**Comment by chmichael** [comment]
> Uh, let me think....maybe because you are the only one having issues with it?

You're not helping!
 
> > 64-bit 6.1.11
> 
> Where did you get that? Why not use libmysql.dll from MySQL 5.7.x as libmysql.dll MySQL 8.x is not supported (yet)

https://downloads.mysql.com/archives/c-c/
(Latest 5.7.x compatible library they made before going to v8)

**Comment by RvdHout** [comment]
> You're not helping!

Just saying it crashes without more info doesn't give me much to go by



I just tried 6.1.11 and it works as well, but usually i use libmysql.dll taken from MySql Community Server 5.7.36 zip package

**Comment by chmichael** [comment]
> Just saying it crashes without more info doesn't give me much to go by, you are not doing yourself any favours

What info you need ? It's running and suddenly stops creating a minidump!

**Comment by RvdHout** [comment]
@chmichael 

I would give 5.7 another shot, because after examining the Dravion sources i can only conclude his so called 5.6.8 (x64) release is nothing more then a build made from the 5.7.x source and being labeled as 5.6.x

**Comment by RvdHout** [comment]
> > Just saying it crashes without more info doesn't give me much to go by, you are not doing yourself any favours
> 
> What info you need ? It's running and suddenly stops creating a minidump!

You could start with some logs (with complete logging turned on within HMS), and ERROR_hmailserver_*.log if any
You probably had these posted before martin cleaned up the #404 issue report.

Maybe better to use the forum if you still encounter a issue with 5.7.x, more people to assist there

**Comment by chmichael** [comment]
I posted in the forum with no luck. 
I'll give another try on the production server when i find some free time.

Thanks for the tips!

**Comment by Dravion** [comment]
> I posted in the forum with no luck. I'll give another try on the production server when i find some free time.
> 
> Thanks for the tips!

Don't try to reason with this person, it's a fruitless enterprise.

**Comment by RvdHout** [comment]
[Dravion](https://github.com/Dravion), you completely are missing the point, your 5.6.8 LTS source code (eg: zip archive attached to the release page) is 5.7 ALPHA code, it is verified literally 100% identical

That has nothing to do with trying to smear your custom build, that is trying to get some clarity as without it your 5.6.8 LTS releases seems like nothing more then repacked and mislabeled 5.7 alpha release

**Comment by chmichael** [comment]
Well yes RvdHout is a bit agressive but we can't change a person can we ? :)

My wish is for the two of you to work together in order to improve this project and leave these kind of arguments!
I bet both of you are good persons! :)

As far Dravion build it seems RvdHout is right! Official 5.6.8 32 bit  build database version is "56xx" while Dravion build needs database version "5702". I guess he accidental did fork the 5.7 code without notice it OR Martin merged the 5.7 code into the main branch ?

**Comment by SorenRR** [comment]
Master is 5.7.x, it becomes obvious when you backtrack the timeline here https://github.com/hmailserver/hmailserver/network 
It would seem that branch 5.7 (new) is merged with 5.6.5 into master on Dec 27, 2015. If I'm reading the timeline correct. 5.6.x is on that date isolated into it's own branch.

**Comment by Dravion** [comment]
Master is since March 15, 2022  5.6.9 - at least this is what the git branches are showing. 
Could be possible that he cloned the 5,7 branch into 5.6x bc the Github Branch 5.7.x is stalled.
Also all recent Downloads from hMailServer Download page are .5.6.x as well.

**Comment by SorenRR** [comment]
Hmm... Not sure I follow your logic. Branch management in GitHub can be quite a challenge.

Branch **5.6.9**; Constants.h line 132: #define REQUIRED_DB_VERSION 5601
[Constants.h](https://github.com/hmailserver/hmailserver/blob/5.6.9/hmailserver/source/Server/Common/Application/Constants.h#L132)
[FormMain.cs](https://github.com/hmailserver/hmailserver/blob/5.6.9/hmailserver/source/Tools/DBUpdater/formMain.cs#L267-L270)

Branch **master**; Constants.h line 137: #define REQUIRED_DB_VERSION 5702.
[Constants.h](https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/Common/Application/Constants.h#L137)
[FormMain.cs](https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Tools/DBUpdater/formMain.cs#L268-L275)

> Master is since March 15, 2022 5.6.9 - at least this is what the git branches are showing. Could be possible that he cloned the 5,7 branch into 5.6x bc the Github Branch 5.7.x is stalled. Also all recent Downloads from hMailServer Download page are .5.6.x as well.

**Comment by Dravion** [comment]
Yep.
Maybe Martin can clarify why be returned from 5.7.x to 5.6.x branch while the Database version is still marked as 5.7.x.
It causes at least a bit of confusion.

**Comment by SorenRR** [comment]
![download](https://user-images.githubusercontent.com/8338115/159306054-2ce7094b-72bc-45c6-ad0a-47236511c7aa.jpg)

**Comment by RvdHout** [comment]
@[Dravion](https://github.com/Dravion)

Last try, compare:
https://build.hmailserver.com/viewType.html?buildTypeId=HMailServer_BuildHMailServer56&tab=buildTypeChangeLog

with:
https://build.hmailserver.com/viewType.html?buildTypeId=HMailServer_BuildHMailServer57&tab=buildTypeChangeLog

If master branch is 5.6.x as you claim can you explain why is it lacking all the recent commits, eg: SpamTestPTR and the IPv6 update for SpamTestHeloHost?

**Comment by martinknafve** [comment]
Hi guys. Sorry for the making it a bit nonintuitive guys. Let me try to clarify:

* Branch: master, Version: 5.7
* Branch: 5.6.9, Version:5.6.9
* Branch: 5.6.8, Version:5.6.8
* etc

I think this is a relatively common branching strategy (latest develop on master branch and then branch out when new releases are created). But of course there are many ways to do it and this is just one.

You can see the commits used for specific builds in TeamCity, if you log on as Guest.

* 5.6: https://build.hmailserver.com/viewLog.html?buildId=1270&buildTypeId=HMailServer_BuildHMailServer56&tab=buildChangesDiv
* 5.7: https://build.hmailserver.com/viewLog.html?buildId=1314&buildTypeId=HMailServer_BuildHMailServer57&tab=buildChangesDiv

![image](https://user-images.githubusercontent.com/71842/159479925-ec5389ec-e9ae-492f-98b8-e53efe29c322.png)

**Comment by Dravion** [comment]
> Hi guys. Sorry for the making it a bit nonintuitive guys. Let me try to clarify:
> 
> * Branch: master, Version: 5.7
> * Branch: 5.6.9, Version:5.6.9
> * Branch: 5.6.8, Version:5.6.8
> * etc

> * 5.6: https://build.hmailserver.com/viewLog.html?buildId=1270&buildTypeId=HMailServer_BuildHMailServer56&tab=buildChangesDiv
> * 5.7: https://build.hmailserver.com/viewLog.html?buildId=1314&buildTypeId=HMailServer_BuildHMailServer57&tab=buildChangesDiv
> 
> ![image](https://user-images.githubusercontent.com/71842/159479925-ec5389ec-e9ae-492f-98b8-e53efe29c322.png)

Hi Martin, 
Thanks for reaching out to us and clarifying this a little bit.

Maybe it's just me, but i have little bit of a trouble understanding (some) parts, maybe you can help me with this.

For example:
The Github Branch 5.7 is (according to this status page https://github.com/hmailserver/hmailserver/branches/stale )
a staled Branch without any activity for over 6 Years.

But on the other Hand and  according to this status page https://github.com/hmailserver/hmailserver/branches/active  
the Release Branch 5.6 and Branch 5.6.9 where updated within the last 7 days by you.

So, If you actively develop on Branch 5.7 and branch out Stable Releases and Betas to Branch 5.6.8 and 5.6.9, why is there no Development activity shown on the source 5.7 Development Branch for over 6 Years now in the first place?

Do you develop locally on your Machine on a private 5.7.x branch and "git push" your Release changes just out to origin/master (5.6.8 / 5.6.9)?  (that's the only thing i can imagine how this might work on your end at the Moment ;-) )

**Comment by RvdHout** [comment]
Geez, he literally just made clear 5.7 is the master branch, which is the active development branch and still you seem to argument that.

Yes there is an old leftover 5.7 branch, it originates from before 5.7 became the master branch but as you now know that is not the active development branch, FYI master branch is always active, unless archived. And you really told me to learn git?

**Comment by Dravion** [comment]
Ok, this makes sense. 
Maybe it's a good idea of deleting the old, staled 5.7 Branch to avoid any versioning misconceptions in the future.

**Comment by RvdHout** [comment]
There is also a old x64 branch, but that one didn't seem to confuse you, so your logic isn't very logic so to say...
But yes, maybe it is a good idea to delete the stale branches for 5.7 and x64

**Comment by chmichael** [comment]
Hey @martinknafve what's your though updating the boost libraries (1.7.8 now) and also make a 64-bit of the 5.6.9 Branch ?
I heard @RvdHout opinion i would like if you want to write yours too!

Thank you

**Comment by RvdHout** [comment]
Sure be like [Dravion](https://github.com/Dravion) and just ignore everything i told you earlier, Martin reply nowadays is something like this:

> Sorry, no such features will be added to hMailServer, due to lack of time.
> 
> (If someone wants to implement it they are free to do so and submit a pull request - if that arrives I'll consider reopening this)

**Comment by SorenRR** [comment]
The only reason to update Boost to latest version is if there is support for OpenSSL 3.x. There is still no word on when that will happen.

If you want 64-bit go for 5.7. 5.7 contains 5.6.8 PLUS a lot of community additions/fixes. Several users here use it in production so perhaps we can move it out of ALPHA status to BETA status.

> Hey @martinknafve what's your though updating the boost libraries (1.7.8 now) and also make a 64-bit of the 5.6.9 Branch ? I heard @RvdHout opinion i would like if you want to write yours too!
> 
> Thank you

**Comment by RvdHout** [comment]
Development, except for occasionally OpenSSL security updates are close to completely stopped for all 5.6.x branches, the only branch getting some updates, mainly through pull request are done in the active development branch (master branch, which is 5.7.x)

**Comment by chmichael** [comment]
So i close this issue due 5.7 will have the 64-bit support as the main branch!

Thank you all guys! :)

**Comment by RvdHout** [comment]
> @chmichael
> 
> I would give 5.7 another shot, because after examining the Dravion sources i can only conclude his so called 5.6.8 (x64) release is a complete fake and nothing more then a build made from the 5.7.x source and being labeled as 5.6.x

Exactly. If you where using 5.6.8 (x64) by Dravion with success and without crashes i really can not see why you shouldn't be able to use 5.7.0 (x64), now it's proven it is based on the same (source) code

**Comment by Dravion** [comment]
> > @chmichael
> > I would give 5.7 another shot, because after examining the Dravion sources i can only conclude his so called 5.6.8 (x64) release is a complete fake and nothing more then a build made from the 5.7.x source and being labeled as 5.6.x

Fake? I  followed Martins own Release naming method (he never Released a hMailServer a official Stable 5.7 64-Bit Release).
His releases are named as hMailServer **5.6.8** - Build 2574 and hMailServer **5.6.9** - Build 2587 (BETA) - I did the same: See: https://www.hmailserver.com/download

Also: Just a few days ago the Mystery why the old abandoned 5.7 Branch which is abandoned for 6 years now has nothing to do with the real current 5.7 Branch which is used by Martin to build  hMailServer 5.6.8 - Build 2574 and hMailServer 5.6.9 - Build 2587 (BETA), 

How ever, let the hard facts speak:
Martin - hMailServer 5.6.8 - Build 2574
file hMailServer.exe - hMailServer.exe: PE32 executable (GUI) Intel 80386, for MS Windows

Martin - hMailServer 5.6.9 - Build 2587 (BETA)
file hMailServer.exe - hMailServer.exe: PE32 executable (GUI) Intel 80386, for MS Windows

Source: https://www.hmailserver.com/download

Dravion - hMailServer 5.6.8 - hMailServer-5.6.8-B1-x64-LTS.exe
hMailServer.exe: PE32+ executable (GUI) **x86-64,** for MS Windows

file  hMailServer.exe
hMailServer.exe: PE32 executable (GUI) Intel 80386, for MS Windows

Source: https://github.com/Dravion/hmailserver/releases/tag/5.6.8
