### ISSUE TITLE
Installer throws 404 error for .NET 2.0 Download

### ISSUE THREAD

**Issue by tayler6000** [hmailserver/hmailserver#430]
This issue is related to #75.

The current latest installer throws an error when trying to  download the .NET 2.0 installer from Microsoft as it now throws a 404 error.  Undoubtedly due to the fact it reached end of extended support back in 2016.  Currently attempting to install .NET 3.5 (includes 2.0) from Windows Features which may work to satisfy the install.  As far as I could find, .NET 2.0 installers are no longer hosted by Microsoft, however it is possible to install Windows Features from both cmd and PowerShell, I would recommend implementing that into the hMailServer installer instead of relying on Microsoft web servers.

**Comment by martinknafve** [comment]
This issue won't be fixed in 5.6.x.
