### ISSUE TITLE
AUTH PLAIN exposes account password in log

### ISSUE THREAD

**Issue by RvdHout** [hmailserver/hmailserver#436]
@martinknafve 
AUTH PLAIN exposes account password in logfile in 5.6.x at least, and probably in 5.7 as well

```
"SMTPD" 15356 2564 "2022-07-03 19:46:05.173" "127.0.0.1" "RECEIVED: AUTH PLAIN 77+9dXNlcm5hbWVAZG9tYWluLmNvbe+/vVBAc3N3b3Jk"
"SMTPD" 15356 2564 "2022-07-03 19:46:05.177" "127.0.0.1" "SENT: 235 authenticated."
```

https://log.damnation.org.uk/
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=39121&p=240961#p240961

**Comment by RvdHout** [comment]
@martinknafve 
https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/SMTP/SMTPConnection.cpp#L226-L265

Is it looking for and splitting/replacing the wrong char?

As in the example above it looks like the username is wrapped inside Unicode replacement character, then followed by the password
```
	Unicode character	Oct	Dec	Hex	HTML
�	replacement character	0177775	65533	0xFFFD	&#65533;
```

**Comment by JensSpanier** [comment]
I don’t know if we should spread Fouche‘s credentials on more platforms. Maybe you can censor his credentials or use another example? I think it’s bad enough that they are visible in the forum.

**Comment by RvdHout** [comment]
> I don’t know if we should spread Fouche‘s credentials on more platforms. Maybe you can censor his credentials or use another example? I think it’s bad enough that they are visible in the forum.

Agreed, example modified

**Comment by OutbackMatt** [comment]
I've modified the forum entries too - please let me know if you can see them anywhere

**Comment by RvdHout** [comment]
@martinknafve could this be a suitable solution?
https://www.hmailserver.com/forum/viewtopic.php?p=241092#p241092

**Comment by RvdHout** [comment]
Another thingy... 
https://datatracker.ietf.org/doc/html/rfc4954

>       **Restrictions:**
>           After an AUTH command has been successfully completed, no more
>           AUTH commands may be issued in the same session.  After a
>           successful AUTH command completes, a server MUST reject any
>           further AUTH commands with a 503 reply.

In hmailserver you can repeat AUTH LOGIN or AUTH PLAIN commands after you successfully logged in

**Comment by martinknafve** [comment]
Merged
