### ISSUE TITLE
Don't fail server SSL certificate if it doesn't have a Certificate Distribution Point (CDP)

### ISSUE THREAD

**Issue by RobertCroteau** [hmailserver/hmailserver#439]
When verifying a server SSL certificate, if it doesn't have a CDP defined, the certificate verification will fail.  

Error is:
"Certificate verification failed for session 5. Expected host: smtpauth.sg.lab, Windows error code: -2146885614, Windows error message: The revocation function was unable to check revocation for the certificate."

Windows error code: -2146885614   CRYPT_E_NO_REVOCATION_CHECK

mainly, it's an issue with local CA certs with no CDP.  I've also read that it could  be the network that blocks CRL checks.

Is there a workaround (besides setting the CA cert with a CDP) ?  Or would that require some kind of setting that would need to be added to the code (and config)?

tx

**Comment by OutbackMatt** [comment]
> When verifying a server SSL certificate, if it doesn't have a CDP defined, the certificate verification will fail.

Isn't that the point of the verification check?

**Comment by RobertCroteau** [comment]
If you use a local CA to sign certs, that CA may not have a CDP.  The question is not whether there should be one in the local CA but if there's some workaround to that error, if not, could one be added.  We came upon that situation in our testing and we're trying to prevent the issue upstream in our solution if any our customer use certs that are signed by a local CA of theirs that has no CDP. (I know, it's not typical and shouldn't be that way but it could happen)

**Comment by RvdHout** [comment]
> Is there a workaround (besides setting the CA cert with a CDP) ? Or would that require some kind of setting that would need to be added to the code (and config)?

Turn off certificate verification 😏

**Comment by OutbackMatt** [comment]
> ... We came upon that situation in our testing and we're trying to prevent the issue upstream in our solution if any our customer use certs that are signed by a local CA of theirs that has no CDP. 

When do you expect that a customer use certificate will be used (let alone a self signed one)?

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, and this issue does not seem to have broad impact, the current behavior will not be changed.
