### ISSUE TITLE
Show First Name And Last Name

### ISSUE THREAD

**Issue by ALSULTAN** [hmailserver/hmailserver#443]
When sending mails within the same domain the first and last names not shows on the email the same way microsoft exchange does. it is just showing the email account. it would be very good to show the name of the sender instead of his email address.

**Comment by RvdHout** [comment]
What?

There isn't even a option to enter or store first and lastname, this is courtesy of the email client and has nothing to do with a mailserver

**Comment by ALSULTAN** [comment]
first and lastname are stored on hmail server database, so how is that being `courtesy`

**Comment by RvdHout** [comment]
Ah, now i see...in the advanced tab, in all honesty i never seen that before of filled that in and i have been using hMailServer for years, makes no sense either as this can be set by client (and normally is)

**Comment by RvdHout** [comment]
I have to come back slightly to this i think, these values can be used as macros in the signature, see:
https://github.com/hmailserver/hmailserver/pull/256/commits/05d91e7eadde77529fd78fe65388d1393ef2e2f1

**Comment by RvdHout** [comment]
@OutbackMatt

Maybe change that in the documentation, [hMailServer does not use this information](https://www.hmailserver.com/documentation/latest/?page=reference_account), except for signature macros

**Comment by OutbackMatt** [comment]
> @OutbackMatt
> 
> Maybe change that in the documentation, [hMailServer does not use this information](https://www.hmailserver.com/documentation/latest/?page=reference_account), except for signature macros

Done
