### ISSUE TITLE
No password request during installation

### ISSUE THREAD

**Issue by LokotoAi** [hmailserver/hmailserver#448]
Hello,

Just downloaded latest build hMailServer-5.6.8-B2574.exe
So, there is no "Specify main password" window during installation process. It just installed succesfully and asks for unknown password in administrator window.

**Comment by OutbackMatt** [comment]
You've previously had hMailserver installed on that computer

This type of question is better handled in the user forum please
https://www.hmailserver.com/forum/

This is the help document to get you going again
https://www.hmailserver.com/documentation/latest/?page=howto_change_administrator_password

**Comment by LokotoAi** [comment]
> You've previously had hMailserver installed on that computer

No, first install on clean system

**Comment by OutbackMatt** [comment]
did you follow the steps in the help document I linked to?
Removing the password from the hmailserver.ini, then reinstalling hmailserver again...

Feel free to include the contents of your hMailserver.ini if you are stuck

Again, this is FAR better handled in the user forum
