### ISSUE TITLE
hMailServer + Mautic

### ISSUE THREAD

**Issue by ulmeanu** [hmailserver/hmailserver#451]
Hi guys,

I'm not sure if I'm missing something, but..

Can I use hMailServer SMTP with Mautic in order to send unlimited emails? If yes, how? I haven't seen any tutorial on this yet.

**Comment by martinknafve** [comment]
Please read the documentation or ask in end-user forum. This issue tracker is intended for bugs, features, not generic questions.

But in short, hMailServer has no max limit on number of emails you can send, but if you send a lot of emails without a warmup process then receivers will likely consider you a spammer.
