### ISSUE TITLE
HServer require Framework.net 2.0 (not working with 3.5 or up version)

### ISSUE THREAD

**Issue by bovirus** [hmailserver/hmailserver#469]
Installing v. 5.6.8.2574 (stable) or 5.6.9.2607 (beta) is request Framework.net 2.0.

On Windows 10 and 11 I treid to downlaod fframework.net 2. by it install framwek.net 3.5 then I cannot continue installation of Hserver.
 
Please enable installation of HServer with Framework 3.5 or up.

Thanks.

**Comment by RvdHout** [comment]
You might want to check https://github.com/hmailserver/hmailserver/issues/430 https://github.com/hmailserver/hmailserver/issues/400 https://github.com/hmailserver/hmailserver/issues/302, https://github.com/hmailserver/hmailserver/issues/75 and https://github.com/hmailserver/hmailserver/issues/452

Anyways, install .NET 3.x BEFORE installing hMailServer. Problem solved.

**Comment by bovirus** [comment]
@RvdHout

Could be an idea toa dd this info on homne page to help teh suers about installation on Windows 10/11.

Thanks.

**Comment by RvdHout** [comment]
You could have searched as well, anyway i have **no say** in what is posted on the homepage whatsoever, i am just a user like you

**Comment by bovirus** [comment]
@RvdHout 

I searched and I didn't find the info requested.

For this I propose (to the admin) to add this important info.
