### ISSUE TITLE
Creating mail box with IMAM (SSL) and POP (SSL)

### ISSUE THREAD

**Issue by bovirus** [hmailserver/hmailserver#470]
Hi.

I want to install the server to test some send email using

POP TLS - port 993
POP (SSL) - port 995
IMAP (sslv1) - port 993

I didn't find info how to configure the settings to use the server in this context.

Thanks.

**Comment by SorenRR** [comment]
https://www.hmailserver.com/documentation/latest/?page=reference_tcpipport

**Comment by bovirus** [comment]
@SorenRR

Sorry but it's a generic guide.

I'm looking for specific guide how to create/set a server for IMAP with SSL.
