### ISSUE TITLE
"Settings" does not contain a definition for "IPv6PreferredEnabled"

### ISSUE THREAD

**Issue by PeetBL** [hmailserver/hmailserver#474]
I get 10 errors when compiling the solution hmailserver\source\Tools\hMailServer Tools.sln:
twice: "Settings" does not contain a definition for "IPv6PreferredEnabled"
four times: "FetchAccount" does not contain a definition for "MIMERecipientHeaders",
twice: "AntiSpam" does not contain a definition for "CheckPTR",
twice: "AntiSpam" does not contain a definition for "CheckPTR",

The identifiers are contained in “hMailServer.idl”.

I followed the ToDo exactly.

Creating the server Compile the solution hmailserver\source\Server\hMailServer\hMailServer.sln went without any problems.

Can someone help me, I have been using the hMailServer privately for years, I updated ClamVirus, and then I noticed that the mail was no longer being delivered. The known problem “INSTREAM”.

![grafik](https://github.com/hmailserver/hmailserver/assets/41011921/b306f728-edde-47e3-9e46-58cb34936bd9)

![grafik](https://github.com/hmailserver/hmailserver/assets/41011921/d58ff4fc-4eda-4792-ae04-ac276e1c871e)

![grafik](https://github.com/hmailserver/hmailserver/assets/41011921/5c360832-e5e5-4db6-8774-2d0dba1d478e)

**Comment by RvdHout** [comment]
Are hMailServer.sln and hMailServer Tools.sln build in same mode? eg: Debug and/or Release

**Comment by RvdHout** [comment]
I just downloaded the master zip package from github but can't reproduce your error(s)

**Comment by PeetBL** [comment]
> Are hMailServer.sln and hMailServer Tools.sln build in same mode? eg: Debug and/or Release
> 
> PS, you can always download the latest pre-built 5.7 alpha installer from https://build.hmailserver.com/login.html (login as guest)

Yes, i build in same mode, Relase

**Comment by PeetBL** [comment]
I downloaded the master zip package from github....

![grafik](https://github.com/hmailserver/hmailserver/assets/41011921/27a457e7-96d3-4258-83ec-964acac1dc71)

**Comment by PeetBL** [comment]
Now it works smoothly. I had installed various VS2019 packages that are no longer supported (Net SDK, Developerent Tools puls.NET). After uninstalling, everything ran without any problems. Greetings Peet
