### ISSUE TITLE
outgoing spamassassin check when authed enhancement please 

### ISSUE THREAD

**Issue by visualperception** [hmailserver/hmailserver#5]
Any chance of a hmailadmin setting to do spamassassin checks on authenticated user outgoing mail ? Currently it only happens if email client does NOT authenticate. Would also be very useful to have an outgoing spamassassin delete threshold which can then be different from incoming delete threshold.

Idea being to stop all users from sending out spam regardless of whether they are authenticated or not and thereby protect hmail IP from being blacklisted because users are sending spam.

See:

http://www.hmailserver.com/forum/viewtopic.php?f=2&p=163983&sid=28d3b9fee9802a8a15903963ee53201f#p163983

http://www.hmailserver.com/forum/viewtopic.php?f=2&t=26788&sid=28d3b9fee9802a8a15903963ee53201f

http://www.hmailserver.com/forum/viewtopic.php?f=6&p=163976&sid=28d3b9fee9802a8a15903963ee53201f#p163976

**Comment by martinknafve** [comment]
Since hMailServer is no longer being actively developed, enhancements will only be included if authored as a PR with automated tests.
