### ISSUE TITLE
[Question] Should account level forwarding set Return-Path to account address automatically ?

### ISSUE THREAD

**Issue by visualperception** [hmailserver/hmailserver#50]
I tested this yesterday as a user asked a question about gmail flagging fowarded messages as spam.
If you use account level forwarding the Return-Path header is left as the orginating senders email address. When you foward to gmail it will fail gmail spf checks if original sender has an spf record which doesn't include hmail ip/mx. Gmail is using the Return-Path for spf checks.

Fron an email client when you forward a mail the Return-Path is normally set to the email client user address so  gmail spf checks should be OK if that client domain has an spf record.

So question is, should hmail account level forwarding automatically change the Return-Path to the account address doing the forwarding  so it acts like an email client.
This should reduce amount of mail flagged as spam at gmail ?

You can get round this problem by using account level rule and setting return-Path header and then forward but if you always have to do that then forwarding may as well do it automatically.

**Comment by visualperception** [comment]
I think that having two action options in account level rules would be a good thing.
One would be "Forward" which would act like an email client would and use the forwarding accounts address in the smtp envelope (as per the change already made).

The second could be "Redirect" or "Relay" which would not modify the smtp envelope sender.

So users get the choice of how to handle their automatic forwarding.

**Comment by mini-me** [comment]
@martinknafve Not sure, but it seems that 5.6 b2145 still tries to forward mail with orignal From address. In delivery queue i see correct From addres, but in Message viewer - original. And global rule "send via route if From match..." not applies to the messages.

**Comment by leon42** [comment]
For the next version, please add a option to disable changing the sender's address when forwarding. I think this change has been causing headaches for a lot of people who forward to Gmail (and probably other servers) as noted here:

https://hmailserver.com/forum/viewtopic.php?f=7&t=27524&p=171844&hilit=gmail+refuses+messages

**Comment by OutbackMatt** [comment]
Back to the distribution lists and the FROM
Just checking some of the mailing lists that I get...

FROM is the author
Reply-To is set to the list address
To is always just the list address

This works well, although at times we all get vacation messages for some member who forgot to turn their subscriptions off. I found a few lurkers that way one Christmas....

**Comment by martinknafve** [comment]
It seems like the number of message classified as spam when this change was made increased quite a bit. In fact, if you follow Gmails best-practices, you are not supposed to change the From field when forwarding email like this. So in 5.6.2, this change will be reverted and a ini file setting will be added if someone wants to use the current behavior.

**Comment by leon42** [comment]
Ideally there would be a checkbox that could be selected per forwarded account. For example, I would prefer to only keep the original address when forwarding to Gmail. Changing the address is still a good idea when forwarding email for accounts that you know don't get much spam. Perhaps in a future release?

**Comment by OutbackMatt** [comment]
FWIW, I had to enable the ini setting, as I have had a heap of mail rejected by gMail the last few days. About 1 in 10 is getting rejected.

**Comment by Tragen** [comment]
I had to enable it because with SPF, this doesn't work at all.
