### ISSUE TITLE
Spam sender is not auto banned after permanent rejection

### ISSUE THREAD

**Issue by japi** [hmailserver/hmailserver#52]
This is a possible improvement, not necessarily a bug:
I have just seen some spam sender in my logs, who tried to send a mail again and again, every time resulting in "550 Rejected" because of a very high spam score (being the result of DNS blacklist checks)

The SMTP conversation went like this for over 20 minutes, generating around 20000 lines in the log:
[...]
"RECEIVED: RSET"
"SENT: 250 OK"
"RECEIVED: MAIL FROM:...@...
"DNS lookup: ..., Match: True"
"DNS lookup: ..., Match: True"
"DNS lookup: ..., Match: True"
"Total spam score: 60"
"SENT: 550 Rejected by ..."
"RECEIVED: RSET"
"SENT: 250 OK"
"RECEIVED: MAIL FROM:...@...
"DNS lookup: ..., Match: True"
"DNS lookup: ..., Match: True"
"DNS lookup: ..., Match: True"
"Total spam score: 60"
"SENT: 550 Rejected by ..."
[...]

Since this generates thousands of DNS Lookups (hopefully cached somewhere) and floods the log, I think it would be useful to have the option to ban an IP, once it is clear that every further spam check in the session will be ending in the same result (= if the spam score threshold is reached after the DNSBL Tests).

Best regards,
Jan

**Comment by martinknafve** [comment]
Since hMailServer is no longer being actively developed, enhancements will only be included if authored as a PR with automated tests.
