### ISSUE TITLE
[Question] Should using an email address with literal-domain format be supported in hmail ?

### ISSUE THREAD

**Issue by visualperception** [hmailserver/hmailserver#53]
I was playing with the idea of being able to send to a local domain user in hmail by using the literal-domain format, so

user@[123.123.123.123]

when sending from a real domain local user to a local domain user, the mail just hangs in the delivery queue.
 
Following RFC seems to suggest literal domain format should work.

http://tools.ietf.org/html/rfc5321#section-4.1.3

Is this meant to be supported in hmail or not ?

**Comment by martinknafve** [comment]
This is not something I'll add to hMailServer in the foreseeable feature.
