### ISSUE TITLE
Rules and Forwarding reporting Virus when none exists

### ISSUE THREAD

**Issue by visualperception** [hmailserver/hmailserver#54]
hmail 5.6-B2132

If I create an account level rule which has two forward actions to two different local addresses, one of the forwarded mails is reported as containing a virus by Microsoft Security Essentials which I'm using as my External Virus checker.

I tested both forwarding addresses one at a time and they both work. Also tested switching off MSE and both arrive OK as well as to original recipient. So its only when I put two forward actions, one immediately after the other that MSE throws a wobbly with one of them.
I don't know if this is an MSE problem or an hmail problem but it shouldn't happen.

The original mail just contained "test" in subject and in body and was addressed from and to a local address.

**Comment by paulmann** [comment]
The issue with MpCmdRun.exe reporting 'ghost' viruses during concurrent delivery is a well-known race condition when calling the CLI directly. I've built a PowerShell bridge that solves this by isolating each scan in a unique temporary file path and managing the process lifecycle more reliably than a direct CLI call.
It also handles the correct exit code mapping (Clean=0, Infected=2) which is often misconfigured. You can check the implementation here: [hMailServer-External-Antivirus](https://github.com/paulmann/hMailServer-External-Antivirus). This should stabilize your Defender integration significantly.
