### ISSUE TITLE
hMailserver is limited to 2GB memory usage

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#61]
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=26695
and
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=26317&p=160610#p160610

Seems to be a fix mentioned, not sure of it's accuracy or stability

Matt G

**Comment by martinknafve** [comment]
5.7 has been updated to use smarter memory management.
