### ISSUE TITLE
Use enabled / disabled icons on domain, accounts. aliases, distribution lists

### ISSUE THREAD

**Issue by visualperception** [hmailserver/hmailserver#68]
Is it possible to change the icon in hmailadmin to show whether a domain, account, alias or distribution list is enabled or disabled. When you have a lot of any of these it makes seeing what is live much simpler rather than having to check each one by opening it.
I thought this used to happen but it doesn't now.

**Comment by OutbackMatt** [comment]
These were in Bills Alpha builds -  http://www.hmailserver.com/forum/viewtopic.php?f=10&t=21420

Quote >> 2011-12-01
* NEW: Icons added to show disabled domains, accounts, aliases & dist lists in left tree to easily distinguish between enabled/disabled. (Appears to work)

Obviously never made it to official source
