### ISSUE TITLE
Relax install check for .NET 2.0 and include app.config file for later .NET versions

### ISSUE THREAD

**Issue by akoeplinger** [hmailserver/hmailserver#75]
I just installed hmailserver on Windows Server 2012R2, which doesn't ship with the old .NET 2.0 by default. The installer wouldn't let me continue, so I had to install .NET 2.0.

.NET 2.0 apps can easily run on later versions of the framework (such as .NET 4.5 that ships in Server 2012) by including an app.config with the appropriate `<supportedRuntime>` key: http://msdn.microsoft.com/en-us/library/jj152935(v=vs.110).aspx

Additionally, the installer would need to detect later versions of the framework, not just 2.0.

**Comment by visualperception** [comment]
version 3.5 includes 2.0.

**Comment by akoeplinger** [comment]
@visualperception yes, I know, that doesn't change the fact it isn't installed on Server 2012 by default :)

**Comment by OutbackMatt** [comment]
Even though 3.5 is meant to backwards compatinble with 2.0 I've found that I need to run the two command line statements here to install 2.0

https://www.hmailserver.com/forum/viewtopic.php?t=19906

**Comment by mburgermeister** [comment]
im sorry but it appears this fix requires visual studio.  
am i to understand i need to install visual studio and edit the registry so as to enable a framework that was released in 2005 for my window server 2012 machine?  and that this has been a known issue for a year and half?

**Comment by OutbackMatt** [comment]
This should NOT require Visual Studio, or a registry edit

In a command prompt run these two commands, and DotNet 2.0 should be installed, even on server core, and HyperV Server machines

Start /w ocsetup ServerCore-WOW64
Start /w ocsetup NetFx2-ServerCore-WOW64

I'm also pretty sure that Martin was working on this in January of 2016. WHich version of hMailserver did you install?

ALSO - this type of query is better handled on the user forum please https://www.hmailserver.com/forum/index.php

**Comment by mburgermeister** [comment]
thanks for your reply.  i'm attempting to install 5.6.5b2367.
i've figured it out: in server manager, add roles/features wizard, there is an option to enable .net 3.5 with includes .net 2.0
(btw, ocsetup seems has been deprecated.  those commands dont work in win serv 2012.)

now i'm out looking for the admin password which i was not asked to set during installation so i can connect to the db server.  :-/

**Comment by OutbackMatt** [comment]
Those commands certainly worked for me on HyperV2012 R2

With respect to the add roles and features, sometimes you need to remove the role and then re-add it.

With respect to your password issue >> use 2nd option here >https://www.hmailserver.com/documentation/latest/?page=howto_change_administrator_password

Again, this is better handled on the normal support forum please

**Comment by beleeleb** [comment]
Is there a way to install hMailServer on windows server 2012 with .net framework 4.7 without installing .net framework 3.5 and/or 2?

**Comment by OutbackMatt** [comment]
Please use the forum for this kind of discussion...but the answer is, sure, if you build it yourself, change the requirements, and fix any evolving issues (if any) . That's what Open Source is all about.

**Comment by warlocc** [comment]
This is still an issue, the linked fixes haven't worked in a long time.

**Comment by martinknafve** [comment]
This issue is addressed in 5.7, which no longer use .NET Framework 2.0.
