### ISSUE TITLE
PHPWebAdmin security issue

### ISSUE THREAD

**Issue by scomnetgate** [hmailserver/hmailserver#77]
The problem apair when in the same server we have more than one domain inch one with his domain admin user. Also we have one or more users with server admins rights. When the server admin account it is in the same domain with one user which have domain admin rights in the server, PHPWebAdmin allow the domain admin user to change the password and downgrade the user with server admin rights to domain user rights or normal user rights. By changing the password to the user with server admin rights the user with domain admin rights can take control of all server and all others domains. I think that the simplest way to change this is to make invisible server rights accounts to the domain rights accounts.

**Comment by martinknafve** [comment]
This issue will be fixed in hMailServer 5.6.1. A build will be available in ~30 minutes. Do you have time to give it a try?

**Comment by martinknafve** [comment]
hMailServer 5.6.1, build 2208 solves this issue:
https://hmailserver.com/download

The fix is done in the hMailServer COM API. When saving a server administrator account, the API will make sure that the user performing the operation is himself an server administrator.

**Comment by scomnetgate** [comment]
i will give it a try . Thank You.

**Comment by scomnetgate** [comment]
Tested. PHPWebAdmin no longer let domain user accounts to change server user accounts password. Still let them downgrade server user rights to domain or normal user right, but this is no longer a security issue. Thank You.

**Comment by martinknafve** [comment]
Thanks for your report. Next time I would appreciate if you use the Contact form on the website instead when there's a security-related issue. But thanks!

**Comment by scomnetgate** [comment]
Understood. I now is not an excuse but I only have done what I was instructed to do... But what you have write its common sense...The next time considered done...

**Comment by martinknafve** [comment]
No problem! We fixed it, that's the most important thing. Again, thanks!
