### ISSUE TITLE
Question about new feature

### ISSUE THREAD

**Issue by Olivercomputing** [hmailserver/hmailserver#78]
Papercut is a small desktop utility that acts as a very simple SMTP server - see [https://papercut.codeplex.com/] (https://papercut.codeplex.com/).

The problem is that it has to run under a logged in user, no option to run as a service. It would be useful if there were a way to use hmailserver in a similar fashion - capture any emails sent to it, no matter the destination, and forward them to one mailbox that can then be checked by POP3 or IMAP. I'm considering modifying the code to do so, but I'm not sure of the best approach, or whether this is so simple to do that maybe the primary developer could throw it in quickly? 

One idea is to permit having a '*' as a domain, acting as a wildcard for all domains. Then a catchall box for it would effectively accomplish the goal.

**Comment by OutbackMatt** [comment]
You don't need any domain in hMailserver for it to do that.

In fact with no domain, an SMTP relayer and a suitable IP range this is easily achieved and is useful for send mail from devices like scanners, and security appliances via an ISP that requires SSL
