### ISSUE TITLE
Add Tree Group View to Accounts and Aliases for logical grouping of many accounts and aliases

### ISSUE THREAD

**Issue by cshawky** [hmailserver/hmailserver#83]
hMailServer Administrator enhancement request:
1. Add a group/hierarchical group property to email accounts and aliases for logical association and organisation in the tree view.
2. Add ability to add local aliases (same domain) to a user's account from the user account properties.
3. Include a comment with the alias.
I'll clone the repository and have a dig around to see if it is within my programming capability to do this. My guess is that it will require schema / class improvements so is not straight forward.

**Comment by OutbackMatt** [comment]
I'd like to add a poll to this on the main forum >> https://www.hmailserver.com/forum/viewtopic.php?f=2&t=27868&p=172795&hilit=alias#p172795

**Comment by martinknafve** [comment]
I'm closing this, since this is so far down in the prio that it won't be done in the near future.

**Comment by cshawky** [comment]
OK thanks
