### ISSUE TITLE
Support ":;" as To header

### ISSUE THREAD

**Issue by Cattze2015** [hmailserver/hmailserver#84]
Example:
1. Input "You:other_user@myhmailserver.ru;" (no quotes) to Thunderbird's "To:" field, click "Send".
2. Error.

"An error occurred while sending mail. The mail server responded:  Unknown user.
Please check the message recipient Yother_user@myhmailserver.ru and try again."

":;" is a standard. Please support it.
http://www.mew.org/en/info/release/mew_3.html#anonymous

**Comment by martinknafve** [comment]
I don't follow. In Thunderbird, you enter "You:other_user@myhmailserver.ru;". What email address do you expect this email to be sent to?

**Comment by Cattze2015** [comment]
Are you read the documentation link I posted above?

---
3.19 Sending messages with anonymous receivers

You may occasionally wish to send a message to anonymous receivers.

For instance, please imagine that Pooh is trying to invite multiple friends to a party. Piglet should reply only to Pooh. However, Piglet might make a mistake of replying to other people if the addresses of all the invitees are listed in Cc:. Moreover, Pooh does not want to disclose the names of those who he invited until the day of the party.

To handle this, Mew makes use of ":;" for anonymous addresses. Please look at the following example.

To: party:piglet@example.org,roo@example.org;
From: Pooh <winnie-the-pooh@example.net>

Here, there is a colon (":") after the explanatory comment "party". This is followed by some addresses that are delimited by "," and terminated by ";". If you write addresses in this format, Mew sends the message to the addresses with them removed form the header. In this example, Piglet and Roo will receive the following message.

To: party:;
From: Pooh <winnie-the-pooh@example.net>

The receiver knows that the sender is Pooh, but will not know who else received the message. Also, the string "party:;" is not address, so the receiver cannot reply to it.

You should understand that enumerating many addresses on To: or Cc: is basically not a good practice anyway. If you often have the occasion to send messages a set group of people, you should create a mailing-list.

**Comment by OutbackMatt** [comment]
Isn't that what BCC is for?

Why would someone writing a mail client (mew.org is a mail client written for emacs) try to reinvent an existing RFC standard? Why would hMailserver want to emulate non RFC behaviour, when an existing alternative exists that is compliant.

**Comment by martinknafve** [comment]
This request does not really make any sense. hMailServer uses the envelope recipient address to determine who a message should be sent to, not the content of the To header. The request here applies to the content of the To header, which would make this a client issue, not a sever issue.
