### ISSUE TITLE
SpamAssassin Score + hMailServer Score

### ISSUE THREAD

**Issue by superman20** [hmailserver/hmailserver#87]
hMailServer will not add the SpamAssassin score to its own score unless the SpamAssassin score is greater than or equal to the SpamAssassin spam threshold (i.e., SpamAssassin tags it as spam and adds the X-Spam-Status: YES header)?  It seems more logical to always add the scores together and use the combined score as the final spam determination.

**Comment by martinknafve** [comment]
This won't be implemented, due to lack of time on my part.
