### ISSUE TITLE
Account message size limits are not properly handled

### ISSUE THREAD

**Issue by dswartz** [hmailserver/hmailserver#88]
If you look at the default for a domain, the 'max message size' is zero, which the online docs say means 'no limit'.  Yet, when copying my existing messages from dovecot to hmailserver, 3 were rejected due to being too large.  After digging through the code, I found that it in fact fetches the max message size from the SMTP settings (which defaults to 20MB).  Sounds wrong (and certainly confusing, since the average admin will be very confused as to why it is not working per the docs...)

**Comment by martinknafve** [comment]
I have clarified the behavior in the documentation:

If a setting is specified on domain level, this is used.
If not, the setting in the SMTP settings is used.

So the setting on domain-level lets you override the server-setting.

Updated the latest docs for domain settings and smtp settings.
