### ISSUE TITLE
SEND_FAILED_NOTIFICATION not showing some MACRO when inbox is full

### ISSUE THREAD

**Issue by yellcute** [hmailserver/hmailserver#90]
I have found some problem with my hMailServer. Currently it is running latest version 5.6.1-B2208. The server message file SEND_FAILED_NOTIFICATION is as follows:
# 

Your message did not reach some or all of the intended recipients.

Sent: %MACRO_SENT%
Subject: %MACRO_SUBJECT%

The following recipient(s) could not be reached:

%MACRO_RECIPIENTS%

The original message header is:
# %MACRO_ORIGINAL_HEADER%

This problem is occurred in case of the local user's inbox is full.

When there is more than one recipient and the first recipient's inbox is full the %MACRO_SENT% and %MACRO_SUBJECT% will return empty string. %MACRO_RECIPIENTS% is working properly. While %MACRO_ORIGINAL_HEADER% will show only 
# 

Content-Type: text/plain; charset="utf-8"
# MIME-Version: 1.0

This problem will not be happened if there is only one recipient. If there are more than one recipient and the first recipient inbox is not full, all %MACRO% will also be shown properly. From my test, it will be occurred only sending from email in local hmailserver to local hmailserver. 

It can be reproduced with the following condition.
email1@domain.com => inbox full
email2@domain.com => can accept new mail

Sending mail From: email2@domain.com To: email1@domain.com Cc: email2@domain.com

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, and this is a very old issue (which does not seem to affect many people), I will close this issue without action.
