### ISSUE TITLE
ERROR 554 with hms 5.6.2 Build 2227

### ISSUE THREAD

**Issue by kriztan** [hmailserver/hmailserver#92]
I've tested around with the latest version 5.6.2 and had the following problem with mails having attachments:
The sender receives:
`<"user.name@domain.de"@forwarding> (expanded from
    <user.name@domain.de>): host domain.de[123.123.123.123] said: 554
    Your message was received but it could not be saved. Please retry later.
    (in reply to end of DATA command)`
The address "user.name@domain.de" is a normal address and no alias. In the logfiles I get `"SENT: 554 Your message was received but it could not be saved. Please retry later.` and `Aborting save since the message is zero bytes.`

I switched back to hmailserver 5.6.1 Build 2208 without any problems.

**Comment by martinknafve** [comment]
I've sent attachnments using the same version without any errors. Have you seen it more than once? How large were the attachments?

Can you send an email to me and attach the logs? My address is martin@hmailserver.com

**Comment by kriztan** [comment]
I've tried it with different PDF files attached with sizes between 1 MB and 30 MB. None of these mails could be delivered. Mails without attachments are working fine.
The logs are on the way...

**Comment by martinknafve** [comment]
Fixed in final 5.6.2.
