### ISSUE TITLE
Add the OriginalAddress to the hmailserver_awstats.log

### ISSUE THREAD

**Issue by SteffenM-DE** [hmailserver/hmailserver#95]
In the hmailserver_awstats.log the sender and the recipients is logged. But If I forward an account to an other address I only see the new recipient and not the original recipient.

It would be very nice and helpful if this information is logged at the hmailserver_awstats.log too!

Regards, Steffen

**Comment by visualperception** [comment]
Also if mail is sent to an alias you only see the account it is posted to. It would be nice to see the alias account name it was sent to. Not sure how awstats log software will handle that though.

**Comment by martinknafve** [comment]
Since hMailServer is no longer being actively developed, enhancements will only be included if authored as a PR with automated tests.
