### ISSUE TITLE
Recommendation to change default data storage directory to ProgramData

### ISSUE THREAD

**Issue by ericnewton76** [hmailserver/hmailserver#98]
This pulls data out of the Program Files area, which is UAT controlled and problematic sometimes.

Also, ProgramData appears to be becoming the de-facto storage root.

I recommend changing the default during installation to this directory.

Of note, I've switched my installation to use it after installing and having Data placed under Program Files.   The only problem I've run into is the Backup routine.  In spite of changing hmailserver.ini, its still thinking that the Data is still in C:\Program Files (x86)\hMailServer\Data.  Possibly a new issue.

**Comment by OutbackMatt** [comment]
But ProgramData is a hidden directory by default. I think that will complicate life for a lot of non-admin users.

btw, what backup routine do you use? What does it say?

**Comment by ericnewton76** [comment]
Either way, it desperately needs to be removed from Program Files, since
this is an area that is rightly-so protected with UAC in order to protect
the application files from tampering.

ProgramData is a smart choice, especially if its hidden from non-admins.

**Comment by LeeThompson** [comment]
ProgramData is the recommended location for this kind of data.    I think it should be configurable by the admin with ProgramData being the default for new installs.   (Upgrades should keep whatever the current setting is or under Program Files  to not break legacy users.)

**Comment by martinknafve** [comment]
@ericnewton76 Can you tell me what actual issues you are experiencing with the current default configuration?

**Comment by LeeThompson** [comment]
None with Windows 2008R2 or Windows 7, but Microsoft is continuing to lock Program Files down and all the developer guildlines indicate that personal data should be under AppData and general data should be under ProgramData.

**Comment by OutbackMatt** [comment]
I seen windows 10 'updates' remove apps. I've not seen updates remove hMailserver yet, but I have seen other 'line of business' applications get removed automatically, including MYOB and specialised clinical software for doctors, and also paid versions of Antivirus software.

Seen Windows Updates remove stuff (without warning or consent) multiple times.

Anything to avoid that is welcomed...

**Comment by LeeThompson** [comment]
@OutbackMatt, yeah I've heard about that too.    What's happening is Windows 10 acts like it's a full OS upgrade (windows.old and everything) so Program Files is going to be affected by that.   The only way around *that* would be to install in it's own path (C:\hMailServer or something).     I'm not quite sure why Microsoft is doing it this way.

As for backing up if hMailServer used ProgramData. - Yes it is a hidden root (I wish it wasn't), my backup routines however, do back it up (with VSS).     Of course, hMailServer's native backup script can place the backup data wherever the administrator chooses.  (If only it didn't crash periodically but that's a different issue.)

**Comment by martinknafve** [comment]
This won't be implemented. I agree that the current implementation does not match current best practices, but changing the default would require quite a bit of testing.
